Update Monitor log ingestion and alerts page
SumoLogic/sumologic-documentation pull request #1001
Opened 2022-11-22 00:33 UTC by kimsauce

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2022-11-23 03:17 UTC, stacykor requested changes

2022-11-23 03:17 UTC, stacykor commented on docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
>  1. Schedule the query you just created in Setup. For details, see [Schedule a Search](../../alerts/scheduled-searches/schedule-search.md).
Schedule the query you just created in Query.

2022-11-23 03:17 UTC, stacykor commented on docs/alerts/monitors/add-monitor.md
>     * An **Outlier** is an unusual change or a spike in a time series of a key indicator. Use this detection method when you are alerting on KPIs that don't have well-defined constant thresholds for w
**Outlier** lets you detect an unusual change or a spike in a time series of a key indicator.

(Make it match the style for static).

2022-11-26 22:06 UTC, kimsauce commented on docs/manage/ingestion-volume/monitor-ingestion-receive-alerts.md
> +1. Schedule the query you created in the previous step. For details, see [Schedule a Search](../../alerts/scheduled-searches/schedule-search.md).
```suggestion
1. Schedule the query you created in the previous step (**Query**). For details, see [Schedule a Search](../../alerts/scheduled-searches/schedule-search.md).
```

2022-11-26 22:57 UTC, merged