docs(k8sinstr): update img and propagators info
SumoLogic/sumologic-documentation pull request #1034
Opened 2022-11-24 13:32 UTC by mat-rumian

## Purpose of this pull request

This pull request updates dotnet instrumentation img and list of default propagators.

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2022-11-24 16:54 UTC, stacykor approved these changes

2022-11-25 19:01 UTC, kimsauce requested changes
Minor fix

2022-11-25 19:01 UTC, kimsauce commented on docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/kubernetes.md
> +    * **OTEL_PROPAGATORS.** If not provided then operator sets the default value `tracecontext,baggage`. Some additional context propagators can be enabled (b3 - common for service meshes, xray - use
```suggestion
    * **OTEL_PROPAGATORS.** If not provided, the operator sets the default value `tracecontext,baggage`. Some additional context propagators can be enabled (b3 - common for service meshes, xray - used by AWS services).
```

2022-11-26 22:16 UTC, kimsauce approved these changes

2022-11-26 22:33 UTC, merged