updated-drop-down usage
SumoLogic/sumologic-documentation pull request #1130
Opened 2022-12-08 15:36 UTC by JainM6

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2022-12-08 15:56 UTC, kimsauce commented on docs/contributing/word-list.md
> +**Dropdown**. Use drop-down (Adjective). For e.g., Choose your favorite model from a drop-down menu. Use dropdown (Noun). For e.g., Select a source category from the dropdown. Do not use drop down (t
```suggestion
**Dropdown**.
   * Use drop-down (Adjective). Example: Choose your favorite model from a *drop-down* menu. 
   * Use dropdown (Noun). Example: Select a source category from the *dropdown*. Do not use drop down (two words).
```

2022-12-08 22:47 UTC, kimsauce commented
I defer to Marie on this -- having two separate uses for noun/adjective will be a heavy left.

2022-12-09 04:06 UTC, JainM6 commented
> I defer to Marie on this -- having two separate uses for noun/adjective will be a heavy left.

Thanks @MariePMcGarry @kimsauce for the suggestions. I have also added a note there that says the term should not be used at all and just use UI element. In ideal world, people use dropdown when it is used as a noun( these instances are very in technical docs); and 
drop-down or any other hyphenated words are applied only when used as an adjective (often found these scenarios in technical docs).

2022-12-09 17:42 UTC, MariePMcGarry commented
Sorry that I wasn't clear. My point was that although both `dropdown` and `drop-down` are used throughout the industry, we should settle on one usage or another. I say, since we've done a scrub to replace `dropdown` with `drop-down`, let's stick with that and move on. This was really just about consistency.

2022-12-09 18:26 UTC, kimsauce requested changes
see https://github.com/SumoLogic/sumologic-documentation/pull/1130#issuecomment-1343471171

2022-12-12 23:38 UTC, stacykor approved these changes

2022-12-13 04:57 UTC, merged