Release note for Circle CI
SumoLogic/sumologic-documentation pull request #1216
Opened 2022-12-22 06:23 UTC by nmohantyctr

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2022-12-22 06:43 UTC, kimsauce requested changes

2022-12-22 06:43 UTC, kimsauce commented on blog-service/2022-12-22-Circle-CI.md
> +:::
Broken note formatting

2022-12-22 06:43 UTC, kimsauce commented on blog-service/2022-12-22-Circle-CI.md
> +  - Circle CI
CircleCI is one word

2022-12-22 06:43 UTC, kimsauce commented on blog-service/2022-12-22-Circle-CI.md
> +title: Circle CI
Please add more descriptive title

2022-12-23 05:32 UTC, kimsauce requested changes
formatting/style edits

2022-12-23 05:39 UTC, kimsauce commented on blog-service/2022-12-22-Circle-CI.md
> +title: CircleCI job analytics
```suggestion
title: CircleCI Job Analytics
```

2022-12-23 05:39 UTC, kimsauce commented on blog-service/2022-12-22-Circle-CI.md
> +Now you can report CircleCI job analytics to your SumoLogic dashboard.
```suggestion
Now you can report CircleCI job analytics to your Sumo Logic dashboard.
```

2022-12-23 05:39 UTC, nmohantyctr commented on blog-service/2022-12-22-Circle-CI.md
> +:::
Fixed

2022-12-23 05:39 UTC, nmohantyctr commented on blog-service/2022-12-22-Circle-CI.md
> +title: Circle CI
Done

2022-12-23 05:41 UTC, kimsauce commented on blog-service/2022-12-22-Circle-CI.md
> +This command sends environment, team, and service information at the job level. Add this command to your job with the environment, team, or service custom-data values as parameters. This command will
```suggestion
You can now report CircleCI job analytics to your Sumo Logic dashboard using our new job-collector command, which sends environment, team, and service information at the job level. 

Add this command to your job with the environment, team, or service custom-data values as parameters. This command will run with the rest of the job's commands for sending the job log.
```

2022-12-23 05:44 UTC, kimsauce commented on blog-service/2022-12-22-Circle-CI.md
> +Also, the orb is now at sumologic/sumologic. The new orb repo is https://github.com/SumoLogic/sumologic-orb
```suggestion
To learn more, refer to the [Sumo Logic orb repo](https://github.com/SumoLogic/sumologic-orb#job-collector).
```

2022-12-23 05:48 UTC, nmohantyctr commented on blog-service/2022-12-22-Circle-CI.md
> +  - Circle CI
Corrected.

2022-12-23 05:51 UTC, kimsauce approved these changes
looks good!

2022-12-23 06:03 UTC, merged