RUM release note 12-27 - getOverriddenServiceName
SumoLogic/sumologic-documentation pull request #1236
Opened 2022-12-27 19:24 UTC by kimsauce

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2022-12-28 10:37 UTC, pbrzoska-sumo approved these changes

2022-12-28 16:50 UTC, njoy89 approved these changes

2022-12-28 16:56 UTC, MariePMcGarry requested changes
@kimsauce Our standard has been to not use abbreviations like e.g, i.e., or .etc in docs.

2022-12-28 22:34 UTC, kimsauce commented
@MariePMcGarry 
> Our standard has been to not use abbreviations like e.g, i.e., or .etc in docs.

fixed - can you pls re-review?

2022-12-29 20:35 UTC, stacykor commented on docs/apm/real-user-monitoring.md
>     * **Description** for the Source (optional).
```suggestion
   * **Description**. (Optional) description of the Source .
```

2022-12-29 20:35 UTC, MariePMcGarry commented on docs/apm/real-user-monitoring.md
> +   * **Service Name** (required): Add a **Service Name** of a text string to show for the service name in spans (for example, `bookings-web-app`). This setting is saved in the script for `name_of_you
```suggestion
   * **Service Name** (required): Add a **Service Name** of a text string to show for the service name in spans (for example, `bookings-web-app`). This setting is saved in the script for `name_of_your_web_service`.<br/><br/>To set up a service name dynamically (for example, to have different service names for micro-frontend packages), leverage the `getOverriddenServiceName` function inside your page code to overwrite the default service name (requires RUM script v4.2.0 or higher). Service names should be of low cardinality and should describe parts of your website above page level. Here's an example code leveraging that function:
```

2022-12-29 20:35 UTC, stacykor commented on docs/apm/real-user-monitoring.md
>     * **Source Host** and **Source Category** (optional): enter any string to tag the output collected from the source. These are [built-in metadata](/docs/search/get-started-with-search/search-basics
```suggestion
   * **Source Host** and **Source Category** : (Optional) Enter any string to tag the output collected from the source. These are [built-in metadata](/docs/search/get-started-with-search/search-basics/built-in-metadata.md) fields that allow you to organize your data. We recommend you specify a Source Category indicating the data is from a browser.<br/><img src={useBaseUrl('/img/rum/RUM-HTTP-Traces-Source.png')} alt="Real User Monitoring" width="300"/>
```

2022-12-29 20:36 UTC, stacykor commented on docs/apm/real-user-monitoring.md
> +   * **Application Name** (recommended): Add an **Application Name** tag of a text string to show for the app name in spans (for example, `bookings-app`). This groups services in the Application Serv
```suggestion
   * **Application Name**. (Recommended) Add an **Application Name** tag of a text string to show for the app name in spans (for example, `bookings-app`). This groups services in the Application Service View. If left blank, services will belong to a "default" application. See [Application Service Dashboards](/docs/apm/traces/working-with-tracing-data/service-map.md) for more information. This setting is saved in the script for `name_of_your_web_application`.
```

2022-12-29 20:36 UTC, stacykor commented on docs/apm/real-user-monitoring.md
> +   * **Service Name** (required): Add a **Service Name** of a text string to show for the service name in spans (for example, `bookings-web-app`). This setting is saved in the script for `name_of_you
```suggestion
   * **Service Name**. ( Required) Add a **Service Name** of a text string to show for the service name in spans (for example, `bookings-web-app`). This setting is saved in the script for `name_of_your_web_service`.<br/><br/>To set up a service name dynamically (e.g., to have different service names for micro-frontend packages), leverage the `getOverriddenServiceName` function inside your page code to overwrite the default service name (requires RUM script v4.2.0 or higher). Service names should be of low cardinality and should describe parts of your website above page level. Here's an example code leveraging that function:
```

2022-12-29 20:37 UTC, stacykor requested changes
Not big, but not our usual style for Optional and Required. Just making it consistent.

2022-12-29 21:02 UTC, merged