added a clear section for supported variables
SumoLogic/sumologic-documentation pull request #1266
Opened 2023-01-04 23:28 UTC by MariePMcGarry

### Variables

The enrichment server provides allows for these variables:

${IP}, ${MAC}, ${USERNAME}, and ${HOSTNAME} and custom entities

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-01-04 23:30 UTC, MariePMcGarry commented on docs/cse/integrations/insight-enrichment-server.md
> +${IP}, ${MAC}, ${USERNAME}, and ${HOSTNAME} and custom entities
```suggestion
${IP}, ${MAC}, ${USERNAME}, and ${HOSTNAME}, and for custom Entities, ${ENTITY}.
```

2023-01-04 23:30 UTC, MariePMcGarry commented on docs/cse/integrations/insight-enrichment-server.md
> +The enrichment server provides allows for these variables:
```suggestion
The Enrichment Server supports these variables:
```

2023-01-05 00:38 UTC, kimsauce requested changes
Hi @g-wattz , can you please apply Marie's edits on your end and resubmit?

2023-01-06 03:39 UTC, g-wattz approved these changes

2023-01-06 03:40 UTC, g-wattz commented
@kimsauce I have approved

2023-01-06 04:04 UTC, kimsauce commented
> @kimsauce I have approved

@g-wattz Marie's comments above are still showing as unresolved. You might have to add locally in your fork and re-submit.

2023-01-06 04:21 UTC, kimsauce approved these changes

2023-01-06 04:22 UTC, kimsauce commented
@g-wattz thank you! Last step - you just have to sync with main branch to get the latest updates, then you can merge.

2023-01-06 05:33 UTC, merged