[WIP] Traces and Quickstart IA
SumoLogic/sumologic-documentation pull request #1357
Opened 2023-01-14 20:45 UTC by kimsauce

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-01-21 20:47 UTC, kimsauce commented on docs/api/tracing.md
> +The Traces API allows you to browse traces collected in the system. You can execute queries to find traces matching provided search criteria as well as gather detailed information about individual tr
```suggestion
The Traces API allows you to browse traces collected in the system. You can execute queries to find traces matching provided search criteria as well as gather detailed information about individual traces and spans. For more information, see [View and investigate traces](/docs/apm/traces/View-and-investigate-traces).
```

2023-01-21 20:47 UTC, kimsauce commented on docs/api/tracing.md
> +The Span Analytics API allows you to browse spans collected in the system. You can execute queries to find individual spans matching provided search criteria as well as run aggregated span queries an
```suggestion
The Span Analytics API allows you to browse spans collected in the system. You can execute queries to find individual spans matching provided search criteria as well as run aggregated span queries and retrieve their results. For more information, see [Spans](/docs/apm/traces/spans.md).
```

2023-01-21 20:49 UTC, kimsauce commented on docs/apm/traces/spans.md
> +sidebar_label: Spans
```suggestion
sidebar_label: Analyze data on Span level
```

2023-01-21 20:50 UTC, kimsauce commented on docs/apm/traces/tracing-dashboards.md
> +sidebar_label: Tracing/APM Dashboards
```suggestion
```

2023-01-24 19:27 UTC, pbrzoska-sumo requested changes
1. Top level menu link should go to /docs/apm/ not to /docs/apm/traces/
2. set up traces collection should be first, then instrumenting. The latter one assumes the first one is done, so order is important
3. Set up traces collection should be called out in the menu, possibly on the same level as OT app instrumentation, similarly as we define that as sections in Transaction Tracing Setup page
4. Please move dashboards section above span analytics one
5. http://localhost:3000/docs/apm/real-user-monitoring/configure-data-collection/#step-3-search-traces-from-the-browser should be a separate section. We will ad more content there.

2023-01-24 23:30 UTC, kimsauce commented on docusaurus.config.js
> +                to: '/docs/alerts/.*',
```suggestion
                to: '/docs/alerts',
```

2023-01-25 10:41 UTC, pbrzoska-sumo approved these changes

2023-01-25 23:11 UTC, MariePMcGarry approved these changes

2023-01-25 23:26 UTC, merged