Update top.md
SumoLogic/sumologic-documentation pull request #1420
Opened 2023-01-20 06:52 UTC by stacykor

vestigial references to operators when they were a single page. part of PR1379

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

PR1379

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-01-20 06:57 UTC, JainM6 commented on docs/search/search-query-language/search-operators/top.md
> +Use the top operator with the [sort](/docs/search/search-query-language/search-operators/sort/) operator, to reduce the number of sorted results returned.
```suggestion
Use the top operator with the [sort](/docs/search/search-query-language/search-operators/sort/) operator to reduce the number of sorted results returned.
```
removed comma

2023-01-20 07:02 UTC, JainM6 requested changes
Minor edit

2023-01-20 20:49 UTC, kimsauce reviewed
approved w/Megha's suggestion

2023-01-21 06:29 UTC, kimsauce commented on docs/search/search-query-language/search-operators/top.md
> +Use the top operator with the [sort](/docs/search/search-query-language/search-operators/sort/) operator to reduce the number of sorted results returned.
```suggestion
Use the top operator with the [sort](/docs/search/search-query-language/search-operators/sort) operator to reduce the number of sorted results returned.
```

2023-01-21 06:29 UTC, kimsauce commented on docs/search/search-query-language/search-operators/top.md
> +We recommend you instead use the [topk](docs/search/search-query-language/search-operators/topk/) operator so you can take advantage of its additional functionality.
```suggestion
We recommend you instead use the [topk](/docs/search/search-query-language/search-operators/topk) operator so you can take advantage of its additional functionality.
```

2023-01-21 06:29 UTC, kimsauce approved these changes

2023-01-21 06:41 UTC, merged