netskope legacy collection
SumoLogic/sumologic-documentation pull request #1426
Opened 2023-01-20 10:32 UTC by JainM6

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [X ] Update Content - Revisions and updating sections
- [X ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-01-20 17:09 UTC, stacykor commented on docs/integrations/security-threat-detection/netskope-legacy-collection.md
> +
```suggestion
```

2023-01-20 17:11 UTC, stacykor commented on docs/integrations/security-threat-detection/netskope-legacy-collection.md
> +* **Application Usage:** Insights into application usage; specifically by devices, users, users and traffic patterns.
```suggestion
* **Application Usage.** Insights into application usage; specifically by devices, users, users and traffic patterns.
```

2023-01-20 17:11 UTC, stacykor commented on docs/integrations/security-threat-detection/netskope-legacy-collection.md
> +* **Security Alerts:** Visibility into Netskope security alerts and violations and the ability to identify effects of a breach.
```suggestion
* **Security Alerts.** Visibility into Netskope security alerts and violations and the ability to identify effects of a breach.  
```

2023-01-20 17:22 UTC, stacykor requested changes
Looks like an extra line in the steps. Please check.

2023-01-20 19:40 UTC, kimsauce commented on docs/integrations/security-threat-detection/netskope-legacy-collection.md
> +* Specify **Timestamp locator** as `\"timestamp\": (.*),`
```suggestion
   * Specify **Format** as `epoch`
   * Specify **Timestamp locator** as `\"timestamp\": (.*),`
```

2023-01-20 19:40 UTC, kimsauce commented on docs/integrations/security-threat-detection/netskope-legacy-collection.md
> +2. Add an [ HTTP Logs and Metrics Source](/docs/send-data/hosted-collectors/http-source/logs-metrics).
```suggestion
2. Add an [HTTP Logs and Metrics Source](/docs/send-data/hosted-collectors/http-source/logs-metrics).
```

2023-01-20 19:40 UTC, kimsauce commented on docs/integrations/security-threat-detection/netskope-legacy-collection.md
> +**To add a hosted collector and HTTP source, do the following:
```suggestion
To add a hosted collector and HTTP source, do the following:
```

2023-01-20 19:41 UTC, kimsauce commented on docs/integrations/security-threat-detection/netskope-legacy-collection.md
> +**To obtain a Netskope auth token, do the following:
```suggestion
To obtain a Netskope auth token, do the following:
```

2023-01-20 19:41 UTC, kimsauce commented on docs/integrations/security-threat-detection/netskope-legacy-collection.md
> +2. Go to the API portion of the Netskope, **Settings > Tools > Rest API**.
```suggestion
2. Go to the API portion of the Netskope, **Settings** > **Tools** > **Rest API**.
```

2023-01-20 19:42 UTC, kimsauce commented on docs/integrations/security-threat-detection/netskope-legacy-collection.md
> +4. Enable the cron job.
```suggestion
   1. Disable your cron job.
   2. Stop all existing collector processes.
   3. Run the following command to upgrade your collector: `pip install sumologic-netskope-collector --upgrade`
   4. Enable the cron job.
```

2023-01-20 19:45 UTC, kimsauce commented on docs/integrations/security-threat-detection/netskope.md
> +To collect logs from the Netskope platform, use the [new Cloud to Cloud Integration for Netskope](/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/Netskope-Source) to create the
```suggestion
To collect logs from the Netskope platform, use the [new Cloud to Cloud Integration for Netskope](/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/Netskope-Source) to create the source and use the same source category while installing the app. You can view the Netskope legacy collection method [here](/docs/integrations/security-threat-detection/netskope-legacy-collection/).
```

2023-01-21 03:33 UTC, JainM6 commented
> Looks like an extra line in the steps. Please check.

@stacykor Thank you for pointing this out. It's fixed.

2023-01-21 21:30 UTC, merged