changes-monitorsdoc
SumoLogic/sumologic-documentation pull request #1583
Opened 2023-02-07 09:28 UTC by JainM6

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [X ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-02-07 09:40 UTC, nmohantyctr approved these changes

2023-02-07 20:59 UTC, kimsauce commented on docs/alerts/monitors/create-monitor.md
> +`Alert and recovery require a minimum of <Count> data points for `at all times` evaluation windows`
```suggestion
`Alert and recovery require a minimum of <Count> data points for "at all times" evaluation windows`
```

This must be double quotes to match the UI (see screenshot below)
<img width="601" alt="Screenshot 2023-02-07 at 12 57 42 PM" src="https://user-images.githubusercontent.com/56411016/217364202-bbbcdc67-ab44-4bf4-a8c7-c9892e6a7b15.png">

2023-02-07 21:00 UTC, kimsauce requested changes
Leave line 185 as-is (replacing single quotes with double quotes will break the formatting)

2023-02-16 03:56 UTC, kimsauce approved these changes

2023-02-18 05:51 UTC, kimsauce commented on docs/alerts/monitors/create-monitor.md
> +:::  |
```suggestion
:::
```

2023-02-18 05:58 UTC, tarunk2 commented on docs/alerts/monitors/create-monitor.md
> +| Count | The minimum number of data points required within the 5-minute window to trigger an alert or recover from an alert. This means that if Sumo Logic receives fewer data points in a given windo
The window might not always be 5 mins. `The minimum number of data points required within the configured window.

2023-02-18 06:03 UTC, kimsauce commented on docs/alerts/monitors/create-monitor.md
> +| Count | The minimum number of data points required within the 5-minute window to trigger an alert or recover from an alert. This means that if Sumo Logic receives fewer data points in a given windo
```suggestion
| Count | The minimum number of data points required within the configured window to trigger an alert or recover from an alert. This means that if Sumo Logic receives fewer data points in a given window, no alert will be triggered (even if all those data points exceed the threshold).
```

2023-02-18 06:05 UTC, merged