Update Telegraf Collection Architecture documentation
SumoLogic/sumologic-documentation pull request #1702
Opened 2023-02-24 12:30 UTC by kkujawa-sumo

## Purpose of this pull request

Update Telegraf Collection Architecture documentation, Changes related to Helm Chart v3

Issue number: https://jira.kumoroku.com/jira/browse/SUMO-206934

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-02-24 13:22 UTC, swiatekm-sumo reviewed
Some minor phrasing adjustments.

2023-02-24 13:37 UTC, kkujawa-sumo commented on docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/telegraf-collection-architecture.md
> +Metrics collection using Telegraf Operator is made in following process:
It doesn't summarised :P

2023-02-24 15:27 UTC, kkujawa-sumo commented on docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/telegraf-collection-architecture.md
> +Metrics collection using Telegraf Operator is made in following process:
@kimsauce Could you help here?

2023-02-24 15:33 UTC, kkujawa-sumo commented on docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/telegraf-collection-architecture.md
> +1. [Sumo Logic Distribution for OpenTelemetry Collector](https://github.com/SumoLogic/sumologic-otel-collector) sends the metrics on to Sumo Logic.
changed

2023-02-24 15:33 UTC, kkujawa-sumo commented on docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/telegraf-collection-architecture.md
>  1. User add annotations to the pods where they want Telegraf to collect data from.
changed

2023-02-24 18:06 UTC, kimsauce commented on docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/telegraf-collection-architecture.md
> +Metrics collection using Telegraf Operator is made in following process:
@kkujawa-sumo @swiatekm-sumo  I think it is summarizing the information above it. How about both?

_To summarize, here's how to collect metrics using the Telegraf Operator:_

2023-02-24 18:07 UTC, kimsauce requested changes
minor suggestion

2023-02-27 08:30 UTC, kkujawa-sumo commented on docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/telegraf-collection-architecture.md
> +Metrics collection using Telegraf Operator is made in following process:
change to the form proposed by @kimsauce

2023-02-28 12:19 UTC, kkujawa-sumo commented
@kimsauce please take another look

2023-02-28 17:32 UTC, kimsauce commented on docs/send-data/collect-from-other-data-sources/collect-metrics-telegraf/telegraf-collection-architecture.md
> +2. [Sumo Logic Distribution for OpenTelemetry Collector](https://github.com/SumoLogic/sumologic-otel-collector) processes metrics, enriches metadata, and sends metrics to Sumo Logic.
```suggestion
2. The [Sumo Logic Distribution for OpenTelemetry Collector](https://github.com/SumoLogic/sumologic-otel-collector) processes metrics, enriches metadata, and sends metrics to Sumo Logic.
```

2023-02-28 17:33 UTC, kimsauce approved these changes

2023-03-01 09:02 UTC, merged