Change GitHub source configuration procedure
SumoLogic/sumologic-documentation pull request #1801
Opened 2023-03-06 13:09 UTC by astefanski-sumo

Change GitHub source configuration procedure to disable automatic timestamp parsing and use receipt time as _messageTime

img/integrations/app-develpoment/Field_GitHub.png referenced in this md file needs to be updated in line with this pull request. I could not find this file in repo to include replacement in this pull request. I'll provide the file on slack. 

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-03-06 13:10 UTC, astefanski-sumo commented
As discussed on #talk-apps: https://sumologic.slack.com/archives/C1PB1DMB3/p1678105949649269?thread_ts=1677659130.433209&cid=C1PB1DMB3

2023-03-06 13:11 UTC, astefanski-sumo commented
As I can see I can share image here. Below is replacment for Field_GitHub.png. 

![Field_GitHub](https://user-images.githubusercontent.com/108746237/223119537-666b4fae-d3e0-4b08-bd94-49cc7dcd3b44.png)

2023-03-06 13:14 UTC, JKashyap96 approved these changes
LGTM

2023-03-06 17:10 UTC, kimsauce requested changes
Minor style fix

2023-03-06 17:10 UTC, kimsauce commented on docs/integrations/app-development/github.md
> +    * Expand **Advanced Options for Logs (Optional)** section, then ***uncheck (disable)*** option **Extract timestamp information from log file entries** in **Timestamp Parsing**
```suggestion
        * **Field Name**. `_convertHeadersToFields`
        * **Value**. `true`
    * Expand **Advanced Options for Logs (Optional)** section, then **uncheck (disable)** option, then **Extract timestamp information from log file entries** in **Timestamp Parsing** 
```

2023-03-09 04:51 UTC, stacykor approved these changes

2023-03-11 21:49 UTC, stacykor commented
Builds. Just fails spell check.

2023-03-11 21:50 UTC, stacykor approved these changes

2023-03-11 21:50 UTC, merged