Update supported platforms for Kubernetes App and EKS control plane App
SumoLogic/sumologic-documentation pull request #1833
Opened 2023-03-10 15:31 UTC by kkujawa-sumo

## Purpose of this pull request

Update supported platforms for Kubernetes App and EKS control plane App

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-03-10 15:32 UTC, sumo-drosiek approved these changes

2023-03-10 17:07 UTC, stacykor requested changes
Not sure about pulling all of this into other reference docs. It sends the user back and forth. Any way we could just call this information from the other repository?

2023-03-10 17:07 UTC, stacykor commented on docs/integrations/containers-orchestration/kubernetes.md
> +The Sumo Logic Kubernetes App is compatible with [Sumo Logic Kubernetes Collection Helm Chart](https://github.com/SumoLogic/sumologic-kubernetes-collection).
```suggestion
The Sumo Logic Kubernetes App is compatible with the [Sumo Logic Kubernetes Collection Helm Chart](https://github.com/SumoLogic/sumologic-kubernetes-collection).
```

2023-03-10 17:07 UTC, stacykor commented on docs/integrations/containers-orchestration/kubernetes.md
> +List of supported platforms can be found [here](https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/main/docs#support-matrix).
```suggestion
A list of supported platforms can be found [here](https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/main/docs#support-matrix).
```

2023-03-13 07:34 UTC, kkujawa-sumo commented
> Not sure about pulling all of this into other reference docs. It sends the user back and forth. Any way we could just call this information from the other repository?

Unfortunately the only place where we update supported versions on time is https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/main/docs#support-matrix 🤷 

Now we have very old version mention in our documentation, Kuberentes 1.10 is no longer supported and for sure this version contains lots of changes comparing with newer versions of Kuberentes.

2023-03-15 05:36 UTC, JainM6 commented
@stacykor: Could you please review @kkujawa-sumo's response?  If there are no further changes, we can proceed with the update and close the request.

2023-03-15 18:12 UTC, kimsauce commented on docs/integrations/amazon-aws/eks-control-plane.md
> +List of supported platforms can be found [here](https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/main/docs#support-matrix).
```suggestion
The list of supported platforms can be found [here](https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/main/docs#support-matrix).
```

2023-03-15 18:12 UTC, kimsauce commented on docs/integrations/containers-orchestration/kubernetes.md
> +A list of supported platforms can be found [here](https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/main/docs#support-matrix).
```suggestion
The Sumo Logic Kubernetes App is compatible with the [Sumo Logic Kubernetes Collection Helm Chart](https://github.com/SumoLogic/sumologic-kubernetes-collection). A list of supported platforms can be found [here](https://github.com/SumoLogic/sumologic-kubernetes-collection/tree/main/docs#support-matrix).
```

2023-03-15 18:13 UTC, kimsauce approved these changes

2023-03-15 18:28 UTC, merged