Update update-aws-observability-stack.md
SumoLogic/sumologic-documentation pull request #1933
Opened 2023-03-23 03:42 UTC by stacykor

2.5.1 to 2.6.0

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-03-23 04:03 UTC, kimsauce commented on docs/observability/aws/deploy-use-aws-observability/update-aws-observability-stack.md
> +1. Select **Replace Current Template** and paste the URL - https://sumologic-appdev-aws-sam-apps.s3.amazonaws.com/aws-observability-versions/v2.6.0/sumologic_observability.master.template.yaml in the
```suggestion
1. Select **Replace Current Template**, paste the URL `https://sumologic-appdev-aws-sam-apps.s3.amazonaws.com/aws-observability-versions/v2.6.0/sumologic_observability.master.template.yaml` in the Amazon S3 URL option, and then select **Next**.
```

2023-04-04 16:05 UTC, kimsauce requested changes
Minor fix

2023-04-18 08:11 UTC, JainM6 commented
> Minor fix

I've fixed your suggestion.

2023-04-18 08:12 UTC, JainM6 approved these changes
Fixed suggestion, rest looks good.

2023-04-25 14:16 UTC, merged