Added Ciscomeraki
SumoLogic/sumologic-documentation pull request #1935
Opened 2023-03-23 10:50 UTC by JainM6

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ X] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-03-23 16:17 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-meraki-source.md
> +1. On the Collectors page, click **Add Source** next to a **HostedCollector**.
```suggestion
1. On the Collectors page, click **Add Source** next to a **Hosted Collector**.
```

2023-03-23 16:19 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-meraki-source.md
> +1. Select Cisco Meraki.<br/> <img src={useBaseUrl('img/send-data/cisco-meraki-sumo-source-select.png')} alt="cisco-meraki-sumo-source-select.png" width="150" />
I've swapped this out with a cleaner, hi-res image for you. And sized it down to look good.

```suggestion
1. Select Cisco Meraki.<br/> <img src={useBaseUrl('img/send-data/cisco-meraki-sumo-source-select.png')} alt="cisco-meraki-sumo-source-select.png" width="80" />
```

2023-03-23 16:20 UTC, kimsauce requested changes
I've swapped out logo with a cleaner, hi-res image for you. Other than that, looks great!

2023-03-24 13:42 UTC, JainM6 commented
> I've swapped out logo with a cleaner, hi-res image for you. Other than that, looks great!

Thanks Kim.

2023-03-24 18:43 UTC, kimsauce approved these changes

2023-03-24 18:57 UTC, merged