Minor formatting
SumoLogic/sumologic-documentation pull request #1958
Opened 2023-03-27 14:17 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-03-27 15:38 UTC, stacykor requested changes

2023-03-27 15:38 UTC, stacykor commented on docs/send-data/hosted-collectors/amazon-aws/amazon-cloudwatch-source-metrics.md
> +Here’s how tag filtering works.
```suggestion
Here’s how tag filtering works:
```

2023-03-27 15:38 UTC, stacykor commented on docs/send-data/hosted-collectors/amazon-aws/amazon-cloudwatch-source-metrics.md
>  * If you don't specify a tag filter for a namespace, the source will collect all metrics for the namespace.
```suggestion
*Specify a tag filter for a namespace **OR** else the source will collect **all** metrics for the namespace.
```

2023-03-27 15:38 UTC, stacykor commented on docs/send-data/hosted-collectors/amazon-aws/amazon-cloudwatch-source-metrics.md
>  * If you don't specify a tag filter for a namespace, the source will collect all metrics for the namespace.
Given the severity of the impact, make what they should do a command, and tell them why.

2023-03-29 21:20 UTC, stacykor approved these changes

2023-03-31 22:34 UTC, kimsauce commented
Closing - this was a test PR

2023-03-31 22:34 UTC, closed without merging