OTEL Collector docs edits
SumoLogic/sumologic-documentation pull request #1971
Opened 2023-03-28 20:31 UTC by kimsauce

## Purpose of this pull request

Changes carried over from **https://github.com/SumoLogic/sumologic-documentation/pull/1872**. To address:

- [Who is the target audience for Get Started > Quickstart](https://github.com/SumoLogic/sumologic-documentation/pull/1872#discussion_r1149842169)? Need to distinguish between new trial users and existing users that are setting up a new source. The OpenTelemetry data collection and onboarding has a slightly different workflow than what is mentioned in this page. We should modify it to match our new workflow.
- [For Send Data/Index: Not sure if we should have the "JSON Configuration" tile](https://github.com/SumoLogic/sumologic-documentation/pull/1872#discussion_r1149855985) since this talks about how to configure the source on the Installed/hosted collector. Should be a subtopic within Installed/Hosted Collector. We don't have a section here that talks about configuring the source on OpenTelemetry Collector.

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-03-28 21:19 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/data-source-configurations/additional-configurations-reference.md
> +<!--There is another processor called ResourceDetection/system. Should that also be used?-->
@sumoanema @arunpatyal @ajaiswals , can you confirm?

2023-03-28 21:36 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/data-source-configurations/additional-configurations-reference.md
> +<!-- Learn More should be a link to App Catalog page that explains how the Souce Configuration section works.-->
```suggestion
<!-- Learn More should be a link to App Catalog page that explains how the Source Configuration section works.-->
```

2023-03-29 06:09 UTC, angadrandhawa1 approved these changes

2023-03-29 19:57 UTC, stacykor requested changes
small edit

2023-03-29 19:57 UTC, stacykor commented on docs/get-started/quickstart.md
> +1. Go to **App Catalog** and click on the app you'd like to install.
```suggestion
1. Go to **App Catalog** and click the app you'd like to install.
```

2023-04-14 04:31 UTC, merged