CON-1761: public doc for microsoft graph identity protection
SumoLogic/sumologic-documentation pull request #1976
Opened 2023-03-29 10:34 UTC by milan-sumo

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-03-29 15:29 UTC, stacykor requested changes
Minor style stuff.

2023-03-29 15:29 UTC, stacykor commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +* Real-time monitoring: The app provides real-time monitoring of events related to the Microsoft Graph Identity Protection Source, allowing organizations to quickly detect potential security incident
```suggestion
* **Real-time monitoring.** The app provides real-time monitoring of events related to the Microsoft Graph Identity Protection Source, allowing you to quickly detect potential security incidents.
```

2023-03-29 15:29 UTC, stacykor commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +* Advanced analytics: The app includes a wide range of pre-built dashboards, and visualizations, that enable organizations to analyze their Microsoft Graph Identity Protection data in real-time, and
```suggestion
* **Advanced analytics.** The app includes a wide range of pre-built dashboards, and visualizations, that enable organizations to analyze their Microsoft Graph Identity Protection data in real-time, and gain insights into user behavior, sign-in patterns, and .risky detections. The App displays the distribution of risks by level, state, processing status, type, activity, etc which allows you to categorize risks by various criteria and helps to identify critical and frequently occurring risks.
```

2023-03-29 15:29 UTC, stacykor commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +* Investigation capabilities: The app provides advanced search and analytics capabilities that allow security teams to investigate security incidents, identify the root cause of security events, and
```suggestion
* **Investigation capabilities.** The app provides advanced search and analytics capabilities that allow security teams to investigate security incidents, identify the root cause of security events, and take steps to improve their organization's overall security posture.
```

2023-03-29 15:29 UTC, stacykor commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +This section explains how to collect logs from Microsoft Graph Identity Protection API and ingest them into Sumo Logic. Refer to the [Cloud-to-Cloud-Integration for Microsoft Graph Identity Protectio
```suggestion
This section explains how to collect logs from Microsoft Graph Identity Protection API and ingest them into Sumo Logic. For details, see [Cloud-to-Cloud-Integration for Microsoft Graph Identity Protection Source](/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/ms-graph-identity-protection-source/) to create the source and use the same source category while installing the app.
```

2023-03-30 05:16 UTC, milan-sumo commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +* Real-time monitoring: The app provides real-time monitoring of events related to the Microsoft Graph Identity Protection Source, allowing organizations to quickly detect potential security incident
Done

2023-03-30 05:16 UTC, milan-sumo commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +* Advanced analytics: The app includes a wide range of pre-built dashboards, and visualizations, that enable organizations to analyze their Microsoft Graph Identity Protection data in real-time, and
Done

2023-03-30 05:16 UTC, milan-sumo commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +* Investigation capabilities: The app provides advanced search and analytics capabilities that allow security teams to investigate security incidents, identify the root cause of security events, and
Done

2023-03-30 05:16 UTC, milan-sumo commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +This section explains how to collect logs from Microsoft Graph Identity Protection API and ingest them into Sumo Logic. Refer to the [Cloud-to-Cloud-Integration for Microsoft Graph Identity Protectio
Done

2023-03-31 19:41 UTC, kimsauce commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +**Sample Risky Users Log Message**
Redundant

```suggestion
**Sample Risky Users Log Message**
```

2023-03-31 19:42 UTC, kimsauce commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +**Sample Risk detections Log Message**
Redundant

```suggestion
```

2023-03-31 19:42 UTC, kimsauce commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +description: This Sumo Logic App for Microsoft Graph Identity Protection provides organizations with advanced security monitoring and analytics capabilities for their Microsoft Graph Identity Protect
```suggestion
description: The Sumo Logic App for Microsoft Graph Identity Protection provides organizations with advanced security monitoring and analytics capabilities for their Microsoft Graph Identity Protection data.
```

2023-03-31 19:44 UTC, kimsauce commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +:::
```suggestion
2. Select the version of the service you're using and click **Add to Library**. Version selection is available only for limited number of apps. For details, see the [Install the Apps from the Library](/docs/get-started/apps-integrations#install-apps-from-the-library).
```

2023-03-31 19:44 UTC, kimsauce commented on docs/integrations/microsoft-azure/microsoft-graph-identity-protection.md
> +###  Risk Detections
```suggestion
### Risk Detections
```

2023-03-31 19:44 UTC, kimsauce requested changes
minor changes

2023-03-31 20:31 UTC, kimsauce requested changes
style stuff

2023-04-03 15:46 UTC, kimsauce approved these changes

2023-04-03 15:47 UTC, merged