UPdate Documentation - No longer supporting Log Reduce/Log Compare operators in Monitor Creation.
SumoLogic/sumologic-documentation pull request #1979
Opened 2023-03-29 18:28 UTC by angadrandhawa1

## Purpose of this pull request

This pull request (PR) is to update the documentation to reflect that we no longer support the Log Reduce/Log Compare operators in Monitors. 

Issue number: 

## Select the type of change:

- [X] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-03-29 21:19 UTC, stacykor requested changes
can't have are and is

2023-03-29 21:19 UTC, stacykor commented on docs/alerts/monitors/index.md
> +* [Log Reduce](../../search/logreduce/logreduce-operator/)/ [Log Compare](../../search/logcompare/) operators are is not supported in Monitors. If your  query contains these operators, then you will
```suggestion
* [Log Reduce](../../search/logreduce/logreduce-operator/)/ [Log Compare](../../search/logcompare/) operators are not supported in Monitors. If your  query contains these operators, then you will not be able to create the monitor.  
```

2023-03-31 17:21 UTC, kimsauce commented on docs/alerts/monitors/index.md
> +* [Log Reduce](../../search/logreduce/logreduce-operator/)/ [Log Compare](../../search/logcompare/) operators are not supported in Monitors. If your  query contains these operators, then you will not
```suggestion
* [Log Reduce](../../search/logreduce/logreduce-operator/)/ [Log Compare](../../search/logcompare/) operators are not supported in Monitors. If your query contains these operators, you will not be able to create the monitor.  
```

2023-03-31 17:21 UTC, kimsauce approved these changes

2023-03-31 18:16 UTC, merged