SUMO-210897 - Release note for deactivation of unused access keys
SumoLogic/sumologic-documentation pull request #1981
Opened 2023-03-29 18:56 UTC by jpipkin1

## Purpose of this pull request

This pull request (PR) adds a release note to the [Service release notes](https://help.sumologic.com/release-notes-service/) for the release of the new feature to automatically deactivate access keys.

This is a companion PR to #1985.

Issue number: 
[SUMO-210897](https://jira.kumoroku.com/jira/browse/SUMO-210897)

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-03-29 19:10 UTC, stacykor requested changes

2023-03-29 19:10 UTC, stacykor commented on blog-service/2023-04-14-deactivation-of-unused-access-keys.md
> +By default API access keys will now automatically be deactivated if they have been unused for 30 days. This enhances the security of your account by reducing the risk of unauthorized access through i
Usually we preface the release note with "we'd like to announce" for releases and for behavior changes "We'd like to update you on the following change"

2023-03-29 21:40 UTC, jpipkin1 commented on blog-service/2023-04-14-deactivation-of-unused-access-keys.md
> +By default API access keys will now automatically be deactivated if they have been unused for 30 days. This enhances the security of your account by reducing the risk of unauthorized access through i
```suggestion
We'd like to announce that by default API access keys will now automatically be deactivated if they have been unused for 30 days. This enhances the security of your account by reducing the risk of unauthorized access through inactive access keys. This ensures that only active access keys can be used to access your account and its resources. 
```

2023-03-31 17:33 UTC, kimsauce approved these changes

2023-03-31 22:32 UTC, kimsauce commented on blog-service/2023-04-14-deactivation-of-unused-access-keys.md
> +import useBaseUrl from '@docusaurus/useBaseUrl';
Since there's no image, you don't need this

```suggestion
```

2023-03-31 22:32 UTC, kimsauce requested changes
minor fix

2023-04-03 15:20 UTC, jpipkin1 commented
Thanks for the review, @kimsauce. I made your requested change.

2023-04-03 15:50 UTC, kimsauce approved these changes

2023-04-04 16:11 UTC, stacykor approved these changes
LGTM

2023-05-03 22:17 UTC, kimsauce approved these changes

2023-05-19 17:32 UTC, kimsauce commented
Hi John! I saw this release note was date today. Will be moving out?

2023-05-19 18:31 UTC, jpipkin1 commented
Thanks for your vigilance, @kimsauce! I got word that the feature will go out on May 29. I updated [SUMO-210897](https://jira.kumoroku.com/jira/browse/SUMO-210897) with the new date.

2023-06-01 16:18 UTC, kimsauce commented on blog-service/2023-06-06-security.md
> +We're happy to announce that by default API access keys will now automatically be deactivated if they have been unused for 30 days. This enhances the security of your account by reducing the risk of
```suggestion
We're happy to announce that by default, API access keys will now automatically be deactivated if they have been unused for 30 days. This enhances the security of your account by reducing the risk of unauthorized access through inactive access keys. This ensures that only active access keys can be used to access your account and its resources. 
```

2023-06-01 18:04 UTC, jpipkin1 commented
On June 1, updated the release note per comments from @kevin-sumo submitted via Slack.

2023-06-20 18:50 UTC, merged