How to Use the Search Page index page.
SumoLogic/sumologic-documentation pull request #1989
Opened 2023-03-30 12:23 UTC by Melvin-CnC

Made changes as per the Open Source Docs Migration Plan.

## Purpose of this pull request

This pull request (PR) for changes to the How to Use the Search Page index page.

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-03-31 20:56 UTC, kimsauce commented on docs/search/get-started-with-search/search-page/index.md
> +  <p>2 Items.</p>
Needs a description

2023-03-31 20:57 UTC, kimsauce requested changes
missing field

2023-04-03 08:40 UTC, Melvin-CnC commented on docs/search/get-started-with-search/search-page/index.md
> +  <p>2 Items.</p>
Made changes to description.

2023-04-03 17:58 UTC, kimsauce approved these changes

2023-04-03 18:16 UTC, merged