CON-1832 Cisco Meraki Source - New Option
SumoLogic/sumologic-documentation pull request #2025
Opened 2023-04-05 14:56 UTC by carlos-castillo-jask

## Purpose of this pull request

We added the ability for users to choose if they want to collect network events or not with the source because of a known issue with large environments. 

Issue number: CON-1832

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-04-05 18:15 UTC, kimsauce requested changes
See comments

2023-04-05 21:31 UTC, carlos-castillo-jask commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-meraki-source.md
> +1. **Network Event Collection**. Enable or disable this option to collect information about your Meraki Networks, their network and wireless Air Marshal events.
Good catch. It is three separate things. I've pushed a change to clarify.

1. Metadata about the networks
2. Network events
3. Wireless Air Marsha Events

2023-04-06 15:33 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cisco-meraki-source.md
> +1. **Network Event Collection**. Enable or disable this option to collect information about your Meraki Networks, their network events and wireless Air Marshal events.
```suggestion
1. **Network Event Collection**. Enable or disable this option to collect information about your Meraki Networks, their network events, and wireless Air Marshal events.
```

2023-04-06 15:33 UTC, kimsauce approved these changes

2023-04-06 15:45 UTC, merged