cato-networks-c2c-docs
SumoLogic/sumologic-documentation pull request #2061
Opened 2023-04-11 12:39 UTC by JV0812

- Created C2C doc for Cato Networks
- CID added
- Card added in index page

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-04-11 14:03 UTC, JainM6 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cato-networks-source.md
> +    - Select **Event Feed Enabled**. <br/>After this, your account starts sending events to the Cato API server. <br/><img src={useBaseUrl('img/send-data/cato-c2c/cato-networks-enable-events-feed.png
```suggestion
    - Select **Event Feed Enabled**. After this, your account starts sending events to the Cato API server. <br/><img src={useBaseUrl('img/send-data/cato-c2c/cato-networks-enable-events-feed.png')} alt="cato-networks-enable-events-feed.png" width="700" />
```

2023-04-11 14:07 UTC, JainM6 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cato-networks-source.md
> +    - Select **Event Feed Enabled**. <br/>After this, your account starts sending events to the Cato API server. <br/><img src={useBaseUrl('img/send-data/cato-c2c/cato-networks-enable-events-feed.png
All C2Cs images are saved under the /img/send-data/. No need of separate folders.

2023-04-11 14:14 UTC, JainM6 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cato-networks-source.md
> +1. (Optional) Select a date that the API key Expires at. If you select an expiration date then you need to update the source configuration with a new API Key or else an unauthorized error will be rec
```suggestion
1. (Optional) Select a date when the API key expires. If you select an expiration date, then you need to update the source configuration with a new API key, or else an unauthorized error will be received.
```

2023-04-11 14:16 UTC, JainM6 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cato-networks-source.md
> +1. Click **Apply**. The API key is added and a popup window containing the new API key is displayed.
```suggestion
1. Click **Apply**. The API key is added, and a popup window containing the new API key is displayed.
```

2023-04-11 14:19 UTC, JainM6 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cato-networks-source.md
> +You cannot access the value for the API key once you close this window.
```suggestion
Note that the API key value will not be available after closing this window. Kindly ensure that you copy and securely save the API key before closing the window.
```

2023-04-11 14:26 UTC, JainM6 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cato-networks-source.md
> +To configure an Cato Networks Source:
```suggestion
To configure a Cato Networks Source:
```

2023-04-11 15:55 UTC, JainM6 requested changes
Some formatting changes.

2023-04-11 16:08 UTC, kimsauce submitted a review, later dismissed
Please apply mine & Megha's edits, then click "Re-request review".

2023-04-11 16:08 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cato-networks-source.md
> +1. Only account administrators with the Editor privilege can generate keys in the Cato Management Application (CMA).
@JV0812 as we discussed, these should be bulleted items (not numbered steps).

2023-04-12 06:03 UTC, JainM6 approved these changes
Thank you. Looks good to me.

2023-04-12 08:20 UTC, merged