Dashboard support on Infrequent tier
SumoLogic/sumologic-documentation pull request #2071
Opened 2023-04-12 16:19 UTC by hganapathy

## Purpose of this pull request

- Documentation for dashboard support on Infrequent Tier on Limited Availability
- This page should not be searchable in the help docs

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-04-12 16:39 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +Previously, dashboards were only supported in Sumo Logic’s Continuous data tier. Now, you can also setup dashboard panels that run against the Infrequent tier.
I'd rephrase it as:
Previously, dashboards were only supported in Sumo Logic's Continuous data tier. Now, you can also set up dashboard panels that run against the Infrequent tier, making it easier to include data from the Infrequent tier in the scope of dashboard panels.
```

2023-04-12 16:41 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +This means you can now include data from the Infrequent Tier in the scope of dashboard panels.
```suggestion
To use data from the Infrequent tier in your dashboard panels, you can use the following sample queries
```

2023-04-12 16:42 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +
```suggestion
```

2023-04-12 16:45 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +For example, you can use `_dataTier=Infrequent` in your query scope:
```suggestion
 * Use `_dataTier=Infrequent` in your query scope. 
```

2023-04-12 16:45 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +
```suggestion
```

2023-04-12 16:45 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +
```suggestion
```

2023-04-12 16:47 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +Or, you can select data in the Infrequent tier by specifying the Partition that contains it, like this:
```suggestion
Or select data in the Infrequent tier by specifying the Partition that contains it. For example:
```

2023-04-12 16:47 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +
```suggestion
```

2023-04-12 16:48 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +
```suggestion
```

2023-04-12 16:48 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +
```suggestion
```

2023-04-12 16:48 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +or
```suggestion
Or
```

2023-04-12 16:49 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +
```suggestion
```

2023-04-12 16:51 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +
```suggestion
```

2023-04-12 16:52 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +* **Top 50 Expensive Queries**. The top 50 expensive queries setup on Dashboards to run against Infrequent tier.
```suggestion
* **Top 50 Expensive Queries**. The top 50 expensive queries set up on Dashboards to run against the Infrequent tier.
```

2023-04-12 16:57 UTC, JainM6 requested changes
Minor formatting changes..

2023-04-13 04:44 UTC, hganapathy commented on docs/beta/infrequent-dashboard-support.md
> +Previously, dashboards were only supported in Sumo Logic’s Continuous data tier. Now, you can also setup dashboard panels that run against the Infrequent tier.
This seems to reiterate the same thing twice when I read it.

> ".. set up dashboard panels that run against the Infrequent tier"
> and "making it easier to include data from the Infrequent tier in the scope of dashboard panels"

Both of these to me appear like the same thing. Can we simplify the whole sentence instead to:

> "Previously, dashboards were only supported in Sumo Logic's Continuous data tier. This support enables you to also > set up dashboard panels to include data from the Infrequent tier."

2023-04-13 04:52 UTC, JainM6 commented on docs/beta/infrequent-dashboard-support.md
> +Previously, dashboards were only supported in Sumo Logic’s Continuous data tier. Now, you can also setup dashboard panels that run against the Infrequent tier.
Yes, we can. This looks good.

2023-04-13 04:55 UTC, JainM6 approved these changes

2023-04-13 05:23 UTC, merged