added metadata section
SumoLogic/sumologic-documentation pull request #2077
Opened 2023-04-13 10:15 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-04-13 14:06 UTC, JainM6 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
> +| --- | --- |
```suggestion
| :--- | :--- |
```

2023-04-13 14:08 UTC, JainM6 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
> +| --- | --- |
Columns should be left-aligned as per the style guide.

2023-04-13 14:09 UTC, JainM6 requested changes
Looks good. Just a minor correction.

2023-04-13 14:20 UTC, JV0812 commented
Comments fixed.

2023-04-13 18:35 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source.md
> +Metadata fields will be set, if the integration is configured with the SIEM forward option. See **Metadata Fields** table below:
```suggestion
The following **Metadata Fields** will be set if you configure your integration with the SIEM forward option.
```

2023-04-13 18:42 UTC, kimsauce requested changes
@JV0812 For consistency with the rest of the C2C docs, this should be placed as a step in the [Set up Citrix Cloud Source section](https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/citrix-cloud-source/#set-up-citrix-cloud-source).

Here's an example from another C2C doc:
<img width="634" alt="Screenshot 2023-04-13 at 11 40 22 AM" src="https://user-images.githubusercontent.com/56411016/231853406-8fa71310-9791-4fe6-9460-6f05930d1085.png">

2023-04-14 03:59 UTC, JV0812 commented
In some of the c2c doc, Metadata fields are mentioned as a H2 section. [This app](https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source/) has the exact `_siemparser` field and is a part of H2 and not the step.
Kindly suggest me which one to follow.

2023-04-18 21:51 UTC, kimsauce approved these changes

2023-04-18 22:08 UTC, merged