Collect from Other Data Sources index page.
SumoLogic/sumologic-documentation pull request #2079
Opened 2023-04-13 13:48 UTC by Melvin-CnC

Made changes as per the Open Source Docs Migration Plan

## Purpose of this pull request

This pull request (PR) for edits to the Collect from Other Data Sources index page.

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-04-13 14:02 UTC, Melvin-CnC commented
@kimsauce I haven't included the "Kubernetes Fluentd plugin" in the index edits as it was marked as a "Deprecated Solution". Hope that's ok?

2023-04-14 02:24 UTC, kimsauce commented on docs/send-data/collect-from-other-data-sources/index.md
> +      <p>Provide visibility for monitoring enterprise mobility management in your deployment.</p>
```suggestion
      <p>Provides visibility for monitoring enterprise mobility management in your deployment.</p>
```

2023-04-14 02:24 UTC, kimsauce commented on docs/send-data/collect-from-other-data-sources/index.md
> +      <a href="/docs/send-data/collect-from-other-data-sources/collect-ruby-on-rails-logs"><img src={useBaseUrl('img/icons/traces.png')} alt="icon" width="40"/><h4>Ruby on Rails</h4></a>
```suggestion
      <a href="/docs/send-data/collect-from-other-data-sources/collect-ruby-on-rails-logs"><img src={useBaseUrl('img/icons/operations/collect.png')} alt="icon" width="40"/><h4>Ruby on Rails</h4></a>
```

2023-04-14 02:25 UTC, kimsauce requested changes
Two minor fixes!

2023-04-18 22:44 UTC, kimsauce approved these changes

2023-04-18 22:55 UTC, merged