removed data volume legacy app docs
SumoLogic/sumologic-documentation pull request #2087
Opened 2023-04-14 08:51 UTC by JKashyap96

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

https://jira.kumoroku.com/jira/browse/SUMO-218042

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-04-14 09:15 UTC, JV0812 approved these changes

2023-04-14 09:22 UTC, JKashyap96 commented
Why did the test fail?

error trace:
Error:  Unable to build website for locale en.
Error:  Error: You are trying to create client-side redirections to invalid paths.

2023-04-14 11:30 UTC, JKashyap96 commented
Once this [JIRA](https://jira.kumoroku.com/jira/browse/SUMO-218042) for app release gets implemented, the docs can be deleted.

2023-04-14 17:23 UTC, kimsauce requested changes
@JKashyap96 @JV0812 because you're deleting a doc, you also need to do the following (prevents broken URLs and possible confusion for customers, upholds our SEO): 

- Set up a 301 in cid-redirects.json from the legacy URL to new URL
- Find all instances of the legacy URL in the and replace them with the new URL
- In the newer Data Volume doc, add a note saying the legacy app has been deprecated

Let me know if I can help with these!

2023-04-14 22:23 UTC, kimsauce commented
> Thanks @kimsauce! Could you please help @JV0812 make the changes? Also, the app has been deleted from the production environments, so we can merge this.

@JKashyap96 thank you for the update! @JV0812 , I've created guidance [here](https://help.sumologic.com/docs/contributing/remove-doc/) on how to do it.

2023-04-17 18:21 UTC, kimsauce commented on cid-redirects.json
> +  "/cid/1017": "/docs/integrations/sumo-apps/data-volume-legacy : /docs/integrations/sumo-apps/data-volume",
```suggestion
  "/cid/1017": "/docs/integrations/sumo-apps/data-volume-legacy" : "/docs/integrations/sumo-apps/data-volume",
```

2023-04-17 18:21 UTC, kimsauce commented on cid-redirects.json
> +  "/cid/5194": "/docs/integrations/sumo-apps/data-volume-legacy :/docs/integrations/sumo-apps/data-volume",
Need to put each URL in quotes (this should've broken your local build)

```suggestion
  "/cid/5194": "/docs/integrations/sumo-apps/data-volume-legacy" : "/docs/integrations/sumo-apps/data-volume",
```

2023-04-17 18:25 UTC, kimsauce commented on cid-redirects.json
> +  "/cid/5194": "/docs/integrations/sumo-apps/data-volume-legacy :/docs/integrations/sumo-apps/data-volume",
You need to replace the URL, not add to it

```suggestion
  "/cid/5194": "/docs/integrations/sumo-apps/data-volume",
```

2023-04-18 16:41 UTC, kimsauce approved these changes

2023-04-18 16:54 UTC, merged