Rapid7-c2c
SumoLogic/sumologic-documentation pull request #2114
Opened 2023-04-17 11:17 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-04-17 18:30 UTC, kimsauce submitted a review, later dismissed
- Minor formatting fixes
- You have the same logo twice - can you remove one instance, and then use the other one throughout the docs?

2023-04-17 18:31 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/rapid7-source.md
> +| --- | --- |
```suggestion
| :--- | :--- |
```

2023-04-17 18:31 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/rapid7-source.md
> +## Meta-data Fields
```suggestion
## Metadata Fields
```

2023-04-17 18:32 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/rapid7-source.md
> +
extra line

```suggestion
```

2023-04-17 18:32 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/rapid7-source.md
> +description: Learn how to collect asset and vulnerabilities from Rapid7 InsightVM
```suggestion
description: Learn how to collect assets and vulnerabilities from Rapid7 InsightVM.
```

2023-04-18 05:43 UTC, JainM6 approved these changes
LTGM

2023-04-18 16:27 UTC, kimsauce requested changes
It looks like you still have two logos attached. Can you delete one, @JV0812 ?

<img width="843" alt="Screenshot 2023-04-18 at 9 26 34 AM" src="https://user-images.githubusercontent.com/56411016/232842658-83406938-9386-477a-a824-4ff74c88c068.png">

2023-04-19 05:12 UTC, merged