Shareable message
SumoLogic/sumologic-documentation pull request #2123
Opened 2023-04-18 10:10 UTC by JainM6

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [X ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-04-18 16:23 UTC, kimsauce commented on docs/search/get-started-with-search/search-basics/share-message-link.md
> +3. Find the message you want to share and right-click on it. Then, select **Copy link to message**. <br/> <img src={useBaseUrl('/img/search/get-started-search/search-basics/select-message.png')} alt=
Titlecased to match how it appears in the UI

```suggestion
3. Find the message you want to share and right-click on it. Then, select **Copy Link to Message**. <br/> <img src={useBaseUrl('/img/search/get-started-search/search-basics/select-message.png')} alt="icon" width="800"/>
```

2023-04-18 16:24 UTC, kimsauce requested changes
Looks great! Just a minor tweak.

2023-04-19 05:36 UTC, JV0812 commented on docs/search/get-started-with-search/search-basics/share-message-link.md
> +2. Once the search results are generated, navigate to the **Message** tab. <br/> <img src={useBaseUrl('/img/search/get-started-search/search-basics/copy-message.png')} alt="copy-message" width="900"/
**Messages** tab.

2023-04-19 07:16 UTC, JainM6 commented on docs/search/get-started-with-search/search-basics/share-message-link.md
> +2. Once the search results are generated, navigate to the **Message** tab. <br/> <img src={useBaseUrl('/img/search/get-started-search/search-basics/copy-message.png')} alt="copy-message" width="900"/
```suggestion
2. Once the search results are generated, navigate to the **Messages** tab. <br/> <img src={useBaseUrl('/img/search/get-started-search/search-basics/copy-message.png')} alt="copy-message" width="900"/>
```

2023-04-19 07:16 UTC, JainM6 commented on docs/search/get-started-with-search/search-basics/share-message-link.md
> +You can share a link to a specific message in the Sumo Logic search table, which allows you to quickly and easily share important information. To share a message link to a search, after your query ha
```suggestion
You can share a link to a specific message in the Sumo Logic search table, which allows you to quickly and easily share important information. To share a message link to a search, after your query has run, click **Messages** tab beneath the search query box.
```

2023-04-19 07:39 UTC, JV0812 approved these changes

2023-04-19 10:08 UTC, merged