update recources.md
SumoLogic/sumologic-documentation pull request #2133
Opened 2023-04-19 06:36 UTC by JV0812

Added meta-data tag table and minor updates related to AWSO.

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-04-19 07:06 UTC, kimsauce commented on docs/observability/aws/deploy-use-aws-observability/resources.md
> +### Meta-data Tags
no dash please

```suggestion
### Metadata Tags
```

2023-04-19 07:07 UTC, kimsauce commented on docs/observability/aws/deploy-use-aws-observability/resources.md
> +The Meta-data tags applied on Sumo Logic Sources.
```suggestion
The metadata tags applied on Sumo Logic Sources.
```

2023-04-19 07:07 UTC, kimsauce submitted a review, later dismissed
minor fixes

2023-04-19 17:19 UTC, kimsauce commented on docs/observability/aws/deploy-use-aws-observability/resources.md
> +   <td>Lambda Log Forwarder ( AWS CloudWatch logs)
```suggestion
   <td>Lambda Log Forwarder (AWS CloudWatch logs)
```

2023-04-19 17:20 UTC, kimsauce requested changes
grammar

2023-04-20 12:23 UTC, JainM6 approved these changes
LTGM

2023-04-24 14:00 UTC, JainM6 approved these changes
LTGM

2023-04-25 14:37 UTC, merged