minor update
SumoLogic/sumologic-documentation pull request #2135
Opened 2023-04-19 08:01 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-04-19 08:04 UTC, JainM6 commented on docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
>  1. Install the latest version of [jq](https://github.com/stedolan/jq/wiki/Installation) command-line JSON parser. This is required for running the fields.sh batch file.
```suggestion
1. Install the latest version of [jq](https://github.com/stedolan/jq/wiki/Installation) command-line JSON parser. This is required for running the `fields.sh` batch file.
```

2023-04-19 08:26 UTC, JainM6 commented on docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
> +If you have already set up the solution with CloudFormation in the past and want to move to Terraform, we recommend you to follow the below instruction:
```suggestion
If you have already set up the solution with CloudFormation in the past and want to move to Terraform, we recommend you follow the below instructions:
```

2023-04-19 08:27 UTC, JainM6 requested changes
Formatting.

2023-04-19 17:18 UTC, kimsauce commented on docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md
> +1. Install Sumo Logic Python SDK using the following command. Click [here](https://pypi.org/project/sumologic-sdk/) to know more.
```suggestion
1. Install Sumo Logic Python SDK using the following command. Click [here](https://pypi.org/project/sumologic-sdk/) to learn more.
```

2023-04-19 17:18 UTC, kimsauce requested changes
grammar

2023-04-20 12:24 UTC, JainM6 approved these changes
LTGM

2023-04-20 16:56 UTC, kimsauce approved these changes

2023-04-20 17:09 UTC, merged