Update Send Data page - add links to Kubernetes Solution
SumoLogic/sumologic-documentation pull request #2136
Opened 2023-04-19 08:06 UTC by kkujawa-sumo

## Purpose of this pull request

Update Send Data page - add links to Kubernetes Solution

Issue number:  https://jira.kumoroku.com/jira/browse/SUMO-215431

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-04-19 08:19 UTC, JainM6 commented on docs/send-data/kubernetes.md
> +This guide is the same used for setting up collection for our [comprehensive Kubernetes solution](/docs/observability/kubernetes).
```suggestion
This is the same guide used for setting up a collection for our [comprehensive Kubernetes solution](/docs/observability/kubernetes). 
```

2023-04-19 08:20 UTC, JainM6 requested changes
Looks good, just a minor correction.

2023-04-19 08:25 UTC, JainM6 requested changes
This path needs to be fixed - docs/send-data/collect-from-other-data-sources/kubernetes/. I see that this file exists under the collect-from-other-data-sources, but you have removed it.

2023-04-19 09:07 UTC, kkujawa-sumo commented
>This path needs to be fixed - docs/send-data/collect-from-other-data-sources/kubernetes/. I see that this file exists under the collect-from-other-data-sources, but you have removed it.

@JainM6 My intention is to move the file from `docs/send-data/collect-from-other-data-sources/kubernetes.md` to `docs/send-data/kubernetes.md`. I see that there are other references in docs to `send-data/collect-from-other-data-sources/kubernetes` which are not fixed now. I'll fix them.

2023-04-19 21:10 UTC, kimsauce requested changes
Hi @kkujawa-sumo , I don't think Kubernetes belongs at the Send Data root level. This is reserved for high-level collector categories, not sources. Is there another Send Data section this could be placed under? 

For such a big move, we'd also need to get buy-in from collection PMs.

Additionally, when you move a doc, you need to [follow all of these steps](https://help.sumologic.com/docs/contributing/remove-doc/).

2023-04-20 09:18 UTC, kkujawa-sumo commented
@kimsauce what do you think about correction? This will only add the link to Kubernetes page in sidecar menu and the link on Send Data page. Is it better?

2023-04-20 16:09 UTC, kimsauce commented on docs/send-data/index.md
> +  <a href="/docs/send-data/kubernetes"><img src={useBaseUrl('img/icons/operations/kubernetes.png')} alt="icon" width="40"/><h4>Kubernetes</h4></a>
```suggestion
  <a href="/docs/send-data/collect-from-other-data-sources/kubernetes"><img src={useBaseUrl('img/icons/operations/kubernetes.png')} alt="icon" width="40"/><h4>Kubernetes</h4></a>
```

2023-04-20 16:10 UTC, kimsauce commented
> @kimsauce what do you think about correction? This will only add the link to Kubernetes page in sidecar menu and the link on Send Data page. Is it better?

That's perfect - great idea, thank you! Just approved.

2023-04-20 16:22 UTC, kimsauce approved these changes

2023-04-20 16:34 UTC, merged