Doc - Support for Infrequent Tier SLOs.
SumoLogic/sumologic-documentation pull request #2213
Opened 2023-04-27 05:29 UTC by hganapathy

Created a doc for support of SLOs on Infrequent Tier. This doc should not be searchable
Also, removed Beta tag on Infrequent Tier Dashboard support page.

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-04-27 07:43 UTC, JainM6 commented on docs/manage/partitions-data-tiers/infrequent-tier-slo-support.md
> +* Use `_dataTier=Infrequent` in your query scope. For example:
1. Use `_dataTier=Infrequent` in your query scope. This ensures that your query only searches for data in the Infrequent tier. For example:

2023-04-27 07:44 UTC, JainM6 commented on docs/manage/partitions-data-tiers/infrequent-tier-slo-support.md
> +* Use `_dataTier=Infrequent` in your query scope. For example:
```suggestion
* Use `_dataTier=Infrequent` in your query scope. This ensures that your query only searches for data in the Infrequent tier. For example:
```

2023-04-27 07:50 UTC, JainM6 commented on docs/manage/partitions-data-tiers/infrequent-tier-slo-support.md
> +* Or select data in the Infrequent tier by specifying the Partition that contains it. For example:
```suggestion
* Or, use `_index` parameter to specify the Partition that contains the data you want to access. For example:
```

2023-04-27 07:52 UTC, JainM6 commented on docs/manage/partitions-data-tiers/infrequent-tier-slo-support.md
> +  Or, run the following query:
```suggestion
  Or, you can also search across multiple indices by using the `OR` operator. For example:
```

2023-04-27 07:53 UTC, JainM6 commented on docs/manage/partitions-data-tiers/infrequent-tier-slo-support.md
> +Sumo Logic provides a dashboard you can use to monitor the Infrequent tier consumption by SLOs.
```suggestion
Sumo Logic provides a dashboard to monitor the Infrequent tier consumption by SLOs.
```

2023-04-27 07:55 UTC, JainM6 commented on docs/manage/partitions-data-tiers/infrequent-tier-slo-support.md
> +You can download the JSON for the dashboard [here](https://sumologic-app-data.s3.amazonaws.com/Infrequent_SLO.json). For information about importing dashboards and other content see [Import Content i
```suggestion
You can download the JSON for the dashboard [here](https://sumologic-app-data.s3.amazonaws.com/Infrequent_SLO.json). For information about importing dashboards and other content, see [Import Content in the Library](/docs/get-started/library#import-content).
```

2023-04-27 08:04 UTC, JainM6 requested changes
Thanks Harrish for submitting the PR.  There are some minor formatting changes.

2023-05-01 23:26 UTC, kimsauce commented
@hganapathy for the [infrequent-tier-dashboard-support](https://help.sumologic.com/docs/manage/partitions-data-tiers/infrequent-tier-dashboard-support) doc, can you confirm its production status? Looks like you removed the Beta tag, but you still want it hidden?

2023-05-02 06:45 UTC, hganapathy commented
@Kim Pohas ***@***.***> this is already production ready but we
won't enable this for customers since this is on a limited availability
capacity. We don't want to term these as beta because scan charges incurred
by enabling these features will be charged to customers. But at the same
time, since its LA, we don't want it publicly visible.

On Tue, May 2, 2023 at 4:57 AM Kim ***@***.***> wrote:

> @hganapathy <https://github.com/hganapathy> for the
> infrequent-tier-dashboard-support
> <https://help.sumologic.com/docs/manage/partitions-data-tiers/infrequent-tier-dashboard-support>
> doc, can you confirm its production status? Looks like you removed the Beta
> tag, but you still want it hidden?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SumoLogic/sumologic-documentation/pull/2213#issuecomment-1530556945>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZF3UIPRTYOWVTGOUNIA4NTXEBBETANCNFSM6AAAAAAXNK3KF4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-02 20:57 UTC, kimsauce commented
> @kim this is already production ready but we won't enable this for customers since this is on a limited availability capacity. We don't want to term these as beta because scan charges incurred by enabling these features will be charged to customers. But at the same time, since its LA, we don't want it publicly visible.

@hganapathy Thank you for clarifying! Would it be ok if we added an LA note? Something like this?

_This feature is available on a Limited Availability (LA) basis. This means that while the feature is production-ready and fully supported, implementation is done by customer request only. If you'd like this enabled in your environment, contact your Sumo Logic account representative. The GA release of this feature will be announced in our [Release Notes](/release-notes-service)._

2023-05-02 20:58 UTC, kimsauce reviewed
Question re: LA

2023-05-03 05:10 UTC, hganapathy commented
I think we shouldn't add any such note at this point. I should have given a
bit more context. Our goal with Data Tiers is to drive towards the Data
Tiers v2 (Flex) world and move away from Continuous/Infrequent/Frequent
tier world. However, this move is going to take time and we expect that
customers will still want a cost efficient way to manage their budget (ie)
send more logs into Infrequent tier.

However, since Infrequent previously did not support functions like
Dashboard, Monitors etc, there was a potential churn risk for customers who
opt to move their data to Infrequent because they don't derive enough
value. Hence, we will start supporting these features on a case by case
basis. Meaning, we will only activate these features for customers who are
a churn risk and that will be decided by a committee.

These features will never become GA and we will never proactively let any
customer know that these features are available. Hence the limited
availability and need to hide the pages. Happy to jump on a call and
explain.

On Wed, May 3, 2023 at 2:28 AM Kim ***@***.***> wrote:

> ***@***.**** commented on this pull request.
>
> Question re: LA
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SumoLogic/sumologic-documentation/pull/2213#pullrequestreview-1409879964>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZF3UIPN3G5LWUDBXQIZUXDXEFYQFANCNFSM6AAAAAAXNK3KF4>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-03 23:23 UTC, kimsauce approved these changes

2023-05-03 23:28 UTC, merged