Metrics Operators Index
SumoLogic/sumologic-documentation pull request #2383
Opened 2023-05-17 11:26 UTC by Melvin-CnC

Made changes as per the Open Source Docs Migration Plan.

## Purpose of this pull request

This pull request (PR) to edit the Metrics Operators Index under Metrics.

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-05-17 12:09 UTC, Melvin-CnC commented
@kimsauce 
Seems like a Docusaurus issue. I'm troubleshooting it. Will ask Jagadish or Megha for help.

2023-05-17 20:27 UTC, kimsauce commented on docs/metrics/metrics-operators/index.md
> +  <a href="/docs/apm/real-user-monitoring/delta/"><img src={useBaseUrl('img/icons/metrics.png')} alt="icon" width="40"/><h4>delta</h4></a>
```suggestion
  <a href="/docs/metrics/metrics-operators/delta/"><img src={useBaseUrl('img/icons/metrics.png')} alt="icon" width="40"/><h4>delta</h4></a>
```

2023-05-17 20:27 UTC, kimsauce commented on docs/metrics/metrics-operators/index.md
> +    <a href="/docs/apm/real-user-monitoring/parse/"><img src={useBaseUrl('img/icons/metrics.png')} alt="icon" width="40"/><h4>parse</h4></a>
```suggestion
    <a href="/docs/metrics/metrics-operators/parse/"><img src={useBaseUrl('img/icons/metrics.png')} alt="icon" width="40"/><h4>parse</h4></a>
```

2023-05-17 20:28 UTC, kimsauce commented on docs/metrics/metrics-operators/index.md
> +    <a href="/docs/metrics/metrics-operators/histogram_quantile"><img src={useBaseUrl('img/icons/metrics.png')} alt="icon" width="40"/><h4>histogram_quantile</h4></a>
```suggestion
    <a href="/docs/metrics/metrics-operators/histogram-quantile"><img src={useBaseUrl('img/icons/metrics.png')} alt="icon" width="40"/><h4>histogram_quantile</h4></a>
```

2023-05-17 20:28 UTC, kimsauce requested changes
broken links

2023-05-18 15:37 UTC, kimsauce commented on docs/metrics/metrics-operators/index.md
> +  <a href="/docs/metrics/metrics-operators/count">  <img src={useBaseUrl('img/icons/metrics.png')} alt="icon" width="40"/><h4>count</h4></a>
```suggestion
  <a href="/docs/metrics/metrics-operators/count"><img src={useBaseUrl('img/icons/metrics.png')} alt="icon" width="40"/><h4>count</h4></a>
```

2023-05-18 15:37 UTC, kimsauce approved these changes

2023-05-18 15:56 UTC, merged