Zoom source doc update
SumoLogic/sumologic-documentation pull request #2442
Opened 2023-05-23 05:19 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-05-23 09:02 UTC, JainM6 commented on docs/send-data/hosted-collectors/webhook-sources/zoom.md
>  1. Click **Continue**, to copy the **Secret Token** value. <br/><img src={useBaseUrl('img/send-data/secret-token.png')} alt="secret-token" width="500"/>
```suggestion
1. Click **Continue** to copy the **Secret Token** value. <br/><img src={useBaseUrl('img/send-data/secret-token.png')} alt="secret-token" width="500"/>
```

2023-05-23 09:03 UTC, JainM6 submitted a review, later dismissed
Minor fix

2023-05-23 16:11 UTC, kimsauce commented on docs/send-data/hosted-collectors/webhook-sources/zoom.md
> +1. Go back to the page in the Zoom Marketplace which you left open in the step 1(#setup-and-configuration).
```suggestion
1. Go back to the page in the Zoom Marketplace that you left open in [step 1](#setup-and-configuration).
```

2023-05-23 16:11 UTC, kimsauce requested changes
quick fix

2023-05-24 02:38 UTC, kimsauce approved these changes

2023-05-24 02:52 UTC, merged