Cato networks app
SumoLogic/sumologic-documentation pull request #2444
Opened 2023-05-23 11:20 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-05-23 15:49 UTC, kimsauce commented on docs/integrations/saas-cloud/cato-networks.md
> + time: "1682856852500"
```suggestion
   account_id: "1714",
   action: "Succeeded",
   api_name: "eventsFeed",
   api_type: "query",
   authentication_type: "APIKEY",
   event_count: "1",
   event_sub_type: "ApiKey",
   event_type: "Connectivity",
   internalId: "9jlo",
   key_name: "Peter",
   login_type: "API",
   src_country: "Ireland",
   src_country_code: "IE",
   src_ip: "128.200.100.1",
   src_is_site_or_vpn: "API",
   src_site: "US",
   time: "1682856852500"
```

2023-05-23 15:51 UTC, kimsauce requested changes
great job! just minor formatting stuff.

2023-05-24 04:43 UTC, JV0812 commented on docs/integrations/saas-cloud/cato-networks.md
> +```
Thanks for catching this Kim, I have added the line break.

2023-05-24 04:46 UTC, kimsauce approved these changes

2023-05-24 05:16 UTC, merged