Update collect-logs.md
SumoLogic/sumologic-documentation pull request #2501
Opened 2023-05-26 22:49 UTC by ajaiswals

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-05-27 18:16 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +You can find the full list of receivers on our [Sumologic OpenTelemetry Collector page](https://github.com/SumoLogic/sumologic-otel-collector/tree/main#components).
```suggestion
You can find the full list of receivers on our [Sumo Logic OpenTelemetry Collector page](https://github.com/SumoLogic/sumologic-otel-collector/tree/main#components).
```

2023-05-27 18:17 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> + 3. Export    : Send data to authenticated Sumologic organization.
```suggestion
Following configuration demonstrates: 
1. Collect. How to collect logs stored in /var/log/syslog and /var/log/audit/audit.log.
2. Transform. Set `_sourceCatetgory` field to `application_logs_prod`.
3. Export. Send data to authenticated Sumo Logic organization.
```

2023-05-27 18:18 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +      - Windows : Restart-Service -Name OtelcolSumo
```suggestion
1. Create a file in folder /etc/otelcol-sumo/conf.d  with name for your choice, sample_app_configuration.yaml.
2. Paste the above content.
3. Restart collector with following command:
   - For Linux:
     ```
     systemctl restart otelcol-sumo
     ```
   - Windows:
     ```
     Restart-Service -Name OtelcolSumo
     ```
```

2023-05-27 18:19 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +
```suggestion
```

2023-05-27 18:19 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +
```suggestion
* __processors__: 
  * `resource/1` Name of the processor that uses `attributes` to add `_sourceCategory` field with value `application_logs_prod`.
* __exporters__: 
  *  `sumologic` Sends data to registered Sumologic Organization.  Auto-configured in sumologic.yaml during installation using script.
```

2023-05-27 18:21 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> + 3. Export : Send data to authenticated Sumologic organization
See https://github.com/SumoLogic/sumologic-documentation/pull/2501/files#r1208088856 for formatting

2023-05-27 18:21 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +      - Linux : systemctl restart otelcol-sumo
```suggestion
1. Create a file in folder /etc/otelcol-sumo/conf.d  with name for your choice, sample_syslog_configuration.yaml.
2. Paste the above content.
3. Restart collector with following command:
      - Linux: `systemctl restart otelcol-sumo`
```

2023-05-27 18:22 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +      - Restart-Service -Name OtelcolSumo
```suggestion
1. Create a file in folder /etc/otelcol-sumo/conf.d  with name sample_windows.yaml.
2. Paste the above content.
3. Restart collector with following command: `Restart-Service -Name OtelcolSumo`.
```

2023-05-27 18:23 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +
```suggestion
Following configuration demonstrates:
1. Collect. Collect Application, Security and System channels. 
2. Transform. Set `_sourceCatetgory` field to "windows_event_log_prod".
3. Export. Send data to authenticated Sumo Logic organization.
```

2023-05-27 18:25 UTC, kimsauce requested changes
formatting - otherwise, content looks great. thank you for your help!

2023-05-31 07:20 UTC, astencel-sumo submitted a review, later dismissed

2023-05-31 07:20 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +        - memory_limiter
Memory limiter should be the first processor in the processors pipeline.

2023-05-31 07:20 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +  filelog/custom_files:
The trailing spaces should be removed.

2023-05-31 07:20 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +    include_file_path: true
Why changing this from `include_file_path_resolved: true` to `include_file_path: true`?
Why is the `include_file_name: false` being removed?

2023-05-31 07:20 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +        - filelog/1
The name `filelog/1` is different from the `filelog/custom_files` defined above. The collector will fail to start with this config.

2023-05-31 07:20 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +    logs/pipeline1:
`pipeline` - Is it a name we want to use? Perhaps we want to use something more descriptive?

2023-05-31 07:20 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +        - resource/1
The name `resource/1` is different from the above defined `resource/processor`.

2023-05-31 07:20 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +  resource/processor1:
Do we want to use this name `processor1`? I'd prefer something more descriptive.

2023-05-31 07:23 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +     udp:
```suggestion
    udp:
```

2023-05-31 07:23 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +    listen_address: "127.0.0.1:514"
```suggestion
      listen_address: "127.0.0.1:514"
```

2023-05-31 08:36 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +              sumologic
```suggestion
        - sumologic
```

2023-05-31 08:36 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +        - resource/syslog:
```suggestion
        - resource/syslog
```

2023-05-31 08:39 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> -## Windows Log Event Receiver
Why is the section "Windows Log Event Receiver" removed?

2023-05-31 08:40 UTC, astencel-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> -## Windows Log Event Receiver
Oh, sorry, missed it - the section is just moved up.

2023-06-09 17:15 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +  *  `logs/pipeline1:` Pipeline glues together what data to collect(receiver), how to process the data(processors) and where to send logs(exporter).
```suggestion
  * `logs/pipeline1:` Pipeline glues together what data to collect(receiver), how to process the data(processors) and where to send logs(exporter).
```

2023-06-12 09:39 UTC, astencel-sumo commented
@kimsauce I've reworked this PR after a chat with Arpit.

2023-06-12 15:12 UTC, perk-sumo commented on docs/send-data/opentelemetry-collector/data-source-configurations/collect-logs.md
> +1. **Collect**: How to collect logs stored in /var/log/syslog and /var/log/audit/audit.log
```suggestion
1. **Collect**: How to collect logs stored in `/var/log/syslog` and `/var/log/audit/audit.log`
```

2023-06-12 15:13 UTC, perk-sumo approved these changes
Two nits, other than that LGTM.

2023-06-13 04:19 UTC, kimsauce approved these changes

2023-06-13 10:59 UTC, merged