Update CyberARK EPM docs
SumoLogic/sumologic-documentation pull request #2511
Opened 2023-05-30 08:56 UTC by paulina-kruczek-sumo

## Purpose of this pull request

This pull request (PR) updates CyberARK EPM docs with the new endpoint information.

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-05-30 17:07 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cyberark-source.md
> +1. **Collect policy audit raw events**. This option enables the C2C Source to collect policy audit raw events from the CyberArk EPM (Endpoint Privilege Manager).
No need to define EPM acronym again (it's defined in line 12).

```suggestion
1. **Collect policy audit raw events**. This option enables the C2C Source to collect policy audit raw events from the CyberArk EPM.
```

2023-05-30 17:07 UTC, kimsauce requested changes
Minor fix

2023-06-01 15:59 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cyberark-source.md
> +The integration with CyberArk EPM's API allows for retrieving administrative, detailed raw, policy audit and policy audit raw events from every set in the environment. The [API documentation](https:/
```suggestion
The integration with CyberArk EPM's API allows for retrieving administrative, detailed raw, policy audit, and policy audit raw events from every set in the environment. The [API documentation](https://docs.cyberark.com/Product-Doc/OnlineHelp/EPM/Latest/en/Content/LandingPages/LPDeveloper.htm) provides guidance on accessing and utilizing this information. This integration facilitates retrieving various audit events, including administrative actions, policy violations, and application usage, to generate alerts, reports, and remediation actions that enhance the organization's security posture.
```

2023-06-02 15:54 UTC, paulina-kruczek-sumo commented
@kimsauce We waited with the documentation until changes release. Now it can be merged.

2023-06-02 16:35 UTC, kimsauce commented
> @kimsauce We waited with the documentation until changes release. Now it can be merged.

perfect! thank you for the update.

2023-06-02 16:50 UTC, merged