Tweaks to "About the Automation Service"
SumoLogic/sumologic-documentation pull request #2586
Opened 2023-06-08 13:54 UTC by jpipkin1

## Purpose of this pull request

This pull request (PR) makes minor updates to this article:
https://help.sumologic.com/docs/cse/automation-service/about-automation-service/#support-and-compliance

Tweaks made:
- Adds a "Data retention" section.
- Adds a statement that Terraform doesn't support creating or modifying integrations, playbooks, or actions.

Issue number:  None

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-06-08 14:06 UTC, JainM6 commented on docs/cse/automation-service/about-automation-service.md
> +The Sumo Logic Terraform provider also supports automations, but does not support the ability to create or modify integrations, playbooks, nor actions. For more information about Terraform, see the [
```suggestion
The Sumo Logic Terraform provider also supports automation, but does not support the ability to create or modify integrations, playbooks, or actions. For more information about Terraform, see the [Sumo Logic Terraform](https://registry.terraform.io/providers/SumoLogic/sumologic/latest/docs) documentation.
```

2023-06-08 14:12 UTC, JainM6 commented on docs/cse/automation-service/about-automation-service.md
> +The Sumo Logic Terraform provider also supports automations, but does not support the ability to create or modify integrations, playbooks, nor actions. For more information about Terraform, see the [
Just a quick fix.

2023-06-08 14:12 UTC, JainM6 approved these changes
just minor changes.

2023-06-08 14:13 UTC, JainM6 requested changes
Minor changes

2023-06-08 18:09 UTC, jpipkin1 commented
Thanks for the review, @JainM6!

2023-06-09 13:26 UTC, jpipkin1 commented
@JainM6, could you check again and approve if it's ready?

2023-06-09 13:28 UTC, JainM6 approved these changes

2023-06-09 13:32 UTC, JainM6 commented
> @JainM6, could you check again and approve if it's ready?

 Thanks @jpipkin1. Sorry, I completely missed re-reviewing this one.

2023-06-09 13:54 UTC, merged

2023-06-09 14:05 UTC, jpipkin1 commented
Thank you, @JainM6!