Next-Gen apps docs & release notes (GA: week ending 6/23)
SumoLogic/sumologic-documentation pull request #2587
Opened 2023-06-08 15:59 UTC by kevin-sumo

Docs and release notes for our Next-Gen Apps release.

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-06-08 16:34 UTC, jpipkin1 commented on blog-service/2023-06-15-next-gen-apps.md
> +* When an update to an installed App becomes available these new apps will provide a badge noting their is an update available. An upgrade can then be applied with a simple click within the App Catal
```suggestion
* When an update to an installed App becomes available, these new apps will provide a badge noting there is an update available. An upgrade can then be applied with a simple click within the App Catalog.  
```

2023-06-08 16:34 UTC, jpipkin1 commented on blog-service/2023-06-15-next-gen-apps.md
> +* Additional filter options making it easy to find your installed or upgradeable Apps.
```suggestion
* Additional filter options make it easy to find your installed or upgradeable Apps. 
```

2023-06-08 16:41 UTC, jpipkin1 requested changes
@kevin-sumo, I made a few more suggestions. 

Also, I think you should make "apps" lowercase when the word stands by itself. Capitalize the word only when it is part of an actual proper noun, like Classic Apps, Next-Gen Apps, and App Catalog.

2023-06-12 18:32 UTC, jpipkin1 commented
Thanks for changing "Apps" to "apps" where appropriate, @kevin-sumo. Looks great.

2023-06-12 18:32 UTC, jpipkin1 approved these changes

2023-06-14 22:42 UTC, kimsauce commented on blog-service/2023-06-15-next-gen-apps.md
> +Over the coming year Sumo Logic will also be making additional improvements within the Applications Catalog to assist with better search, filtering, upgrade notifications, and management. Please look
```suggestion
Over the coming year, Sumo Logic will be making additional improvements within the Apps Catalog to assist with better search, filtering, upgrade notifications, and management. Stay tuned for these future updates. 
```

2023-06-15 18:04 UTC, kimsauce commented on docs/get-started/apps-integrations.md
> +
```suggestion
```

2023-07-05 16:31 UTC, merged