TRIDENT-18109 - Add note on extracted fields
SumoLogic/sumologic-documentation pull request #2589
Opened 2023-06-08 21:33 UTC by jpipkin1

## Purpose of this pull request

This pull request (PR) adds a note to this article:
https://help.sumologic.com/docs/cse/rules/write-match-rule/

It also adds text to "with a summary" fields in other articles, because it bugged me that we had no text there. 

Issue number: 
[TRIDENT-18109](https://jasklabs.atlassian.net/browse/TRIDENT-18109)

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-06-08 21:34 UTC, jpipkin1 commented
We'll hold off publishing this one until [TRIDENT-18108](https://jasklabs.atlassian.net/browse/TRIDENT-18108) is closed. Customers can't use the example in the note until that ticket is resolved.

2023-06-09 15:29 UTC, kimsauce commented on docs/cse/rules/write-aggregation-rule.md
> +1. **with the summary**.  Enter a brief summary describing what causes the Rule to create a Signal.
```suggestion
1. **with the summary**. Enter a brief summary describing what causes the Rule to create a Signal.
```

2023-06-09 15:29 UTC, kimsauce commented on docs/cse/rules/write-chain-rule.md
> +1. **with the summary.**  Enter a brief summary describing what causes the Rule to create a Signal.
```suggestion
1. **with the summary.** Enter a brief summary describing what causes the Rule to create a Signal.
```

2023-06-09 15:29 UTC, kimsauce requested changes
minor fixes

2023-06-09 18:36 UTC, jpipkin1 commented
Thanks for the review, @kimsauce.

2023-06-21 14:41 UTC, jpipkin1 commented
@kimsauce, I made your suggested changes. Could you give approval to this one so it's ready to go whenever Dev gets [APP-2464](https://jasklabs.atlassian.net/browse/APP-2464) resolved?

2023-06-21 19:33 UTC, kimsauce approved these changes

2023-06-21 20:16 UTC, jpipkin1 commented
Thanks, @kimsauce!

2023-07-06 19:06 UTC, merged