Deleted Zscalar web security ad IIS-10 app docs
SumoLogic/sumologic-documentation pull request #2605
Opened 2023-06-12 08:28 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-06-12 16:25 UTC, kimsauce commented on docs/integrations/security-threat-detection/zscaler-internet-access.md
> +This section provides instructions on how to install the Zscaler Internet Access app, and provides examples of each of the dashboards. The preconfigured searches and dashboards provides you an easy-t
```suggestion
This section describes how to install the Zscaler Internet Access app, and provides examples of each of the dashboards. The preconfigured searches and dashboards provides you an easy-to-access visual insights into your data.
```

2023-06-12 16:25 UTC, kimsauce approved these changes

2023-06-12 16:29 UTC, kimsauce requested changes
You're still missing the old-to-new redirects. See https://help.sumologic.com/docs/contributing/remove-doc/#step-1-create-a-301-redirect.

2023-06-13 05:37 UTC, JV0812 commented
Thanks Kim, I have updated this accordingly.

2023-06-13 05:46 UTC, kimsauce approved these changes

2023-06-13 05:47 UTC, kimsauce commented
> Thanks Kim, I have updated this accordingly.

Awesome, thank you - you are fast 🚗

2023-06-14 05:54 UTC, merged