Add links to the new "Automation Examples" and "App Central" articles
SumoLogic/sumologic-documentation pull request #2609
Opened 2023-06-12 19:45 UTC by jpipkin1

## Purpose of this pull request

This pull request (PR) adds links to direct readers to these two new articles:
- https://help.sumologic.com/docs/cse/automation-service/automation-service-examples/
- https://help.sumologic.com/docs/cse/automation-service/automation-service-app-central/

Issue number: None

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-06-12 20:19 UTC, kimsauce commented on docs/cse/automation-service/automation-service-integration-framework.md
> +Following are example definition and action files for integrations. To see an explanation of the file contents, see [Integration framework file formats](/docs/cse/automation-service/automation-servic
```suggestion
Following are example definition and action files for integrations. To see an explanation of the file contents, see [Integration framework file formats](#integration-framework-file-formats) above. To see integration definition and action files used in a working integration, see [Configure a custom integration](/docs/cse/automation-service/automation-service-examples#advanced-example-configure-a-custom-integration).
```

2023-06-12 20:20 UTC, kimsauce commented on docs/cse/automation-service/automation-service-playbooks.md
> +The following procedure describes how to view playbooks already installed in your environment. To add more playbooks, [create a playbook](/docs/cse/automation-service/automation-service-playbooks/#cr
```suggestion
The following procedure describes how to view playbooks already installed in your environment. To add more playbooks, [create a playbook](#create-a-new-playbook), or [install playbooks from App Central](/docs/cse/automation-service/automation-service-app-central/#install-a-playbook-from-app-central).
```

2023-06-12 20:20 UTC, kimsauce commented on docs/cse/automation-service/automation-service-playbooks.md
> +Before you create your own playbook, first [view playbooks](/docs/cse/automation-service/automation-service-playbooks/#view-playbooks) to make sure there isn't one already that does what you want to
```suggestion
Before you create your own playbook, first [view playbooks](#view-playbooks) to make sure there isn't one already that does what you want to accomplish, and also check to see if you can [install a playbook from App Central](/docs/cse/automation-service/automation-service-app-central/#install-a-playbook-from-app-central) that does what you need.
```

2023-06-12 20:21 UTC, kimsauce requested changes
minor fixes

2023-06-12 22:05 UTC, jpipkin1 commented
Thanks for fixing those oopsies, @kimsauce.

2023-06-13 00:13 UTC, kimsauce approved these changes

2023-06-13 00:30 UTC, merged