Sumo 216336 - Doc for RBAC for indexes
SumoLogic/sumologic-documentation pull request #2620
Opened 2023-06-13 18:47 UTC by jpipkin1

## Purpose of this pull request

This pull request (PR) adds a closed beta article:
https://help.sumologic.com/docs/manage/users-roles/roles/rbac-for-indexes

It also cleans up image and link coding in some other roles articles.

Issue number: [SUMO-216336](https://jira.kumoroku.com/jira/browse/SUMO-216336)

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-06-13 18:47 UTC, jpipkin1 commented
This PR is in draft until all SME review comments are in.

2023-06-23 14:20 UTC, jpipkin1 commented
This PR is ready for review.

2023-06-23 17:29 UTC, kimsauce commented on docs/manage/users-roles/roles/construct-search-filter-for-role.md
> +Typically however, a Sumo user will have multiple roles. If a user has multiple roles, Sumo ORs the several role filters and prepends that expression to the user’s queries with an AND, as discussed i
I'd maybe format like this to make it clear you're talking about code

```suggestion
Typically however, a Sumo user will have multiple roles. If a user has multiple roles, Sumo `OR`s the several role filters and prepends that expression to the user’s queries with an `AND`, as discussed in [Multiple role filters and filter precedence](#multiple-role-filters-and-filter-precedence).
```

2023-06-23 17:31 UTC, kimsauce commented on docs/manage/users-roles/roles/create-manage-roles.md
> +1. **Search Filter**. Use this option to control what log data users with this role can access. A search filter for a role defines what log data a user with that role can access. You can define a sea
```suggestion
1. **Search Filter**. Use this option to control what log data users with this role can access. A search filter for a role defines what log data a user with that role can access. You can define a search filter using keywords, wildcards, metadata fields, and logical operators. Sumo prepends the search filter to each query that a user with the role runs. The search filter is invisible to the user, but limits the log results that are returned. See [Construct a Search Filter for a Role](/docs/manage/users-roles/roles/construct-search-filter-for-role) for details and examples on constructing search filters for roles. The simple role filter below prevents users from viewing logs from Sources that include "billing" in their name (`!_source="billing"`).
```

2023-06-23 17:32 UTC, kimsauce commented on docs/manage/users-roles/roles/rbac-for-indexes.md
> +1. If you choose **Allow few indexes** or **Deny few indexes**, choose the indexes in the **Select Indexes** box that appears.<br/><img src={useBaseUrl('img/users-roles/index-based-filter.png')} alt=
```suggestion
1. If you choose **Allow few indexes** or **Deny few indexes**, choose the indexes in the **Select Indexes** box that appear.<br/><img src={useBaseUrl('img/users-roles/index-based-filter.png')} alt="Index based filter" style={{border: '1px solid black'}} width="400"/>
```

2023-06-23 17:33 UTC, kimsauce requested changes
minor suggestions

2023-06-23 18:31 UTC, jpipkin1 commented
Thanks for the review, @kimsauce.

2023-06-23 18:42 UTC, kimsauce approved these changes

2023-06-23 19:01 UTC, merged