Updated aws-ec2-inventory docs
SumoLogic/sumologic-documentation pull request #2625
Opened 2023-06-14 10:28 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-06-14 18:24 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cse-aws-ec-inventory-source.md
> +1. **Processing Rules for Logs (Optional)**. Configure any desired filters, such as allowlist, denylist, hash, or mask, as described in Create a Processing Rule.
```suggestion
1. **Processing Rules for Logs (Optional)**. Configure any desired filters, such as allowlist, denylist, hash, or mask, as described in [Create a Processing Rule](/docs/send-data/collection/processing-rules/create-processing-rule/).
```

2023-06-14 18:28 UTC, jpipkin1 approved these changes
@JV0812, I had only one comment. I approved on the assumption you'll make that change.

2023-06-14 21:46 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cse-aws-ec-inventory-source.md
> +A CSE AWS EC2 Inventory Source goes through the following states when created:
```suggestion
The CSE AWS EC2 Inventory Source tracks errors, reports its health, and start-up progress. You’re informed, in real-time, if the Source is having trouble connecting, if there's an error requiring user action, or if it is healthy and collecting by utilizing Health Events.

The CSE AWS EC2 Inventory Source goes through the following states when created:
```

2023-06-14 21:47 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cse-aws-ec-inventory-source.md
> +| config | JSON Object | Yes | Contains the configuration parameters for the Source. | na |
```suggestion
| config | JSON Object | Yes | Contains the configuration parameters for the Source. | n/a |
```

2023-06-14 21:47 UTC, kimsauce commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cse-aws-ec-inventory-source.md
> +```json title="JSON example for Role Based Authentication"
```suggestion
```json title="JSON example for Role-Based Authentication"
```

2023-06-14 21:49 UTC, kimsauce requested changes
minor formatting

2023-06-27 06:47 UTC, kimsauce approved these changes

2023-07-03 06:32 UTC, merged