windoes otel app - adding security log related dashboard doc update
SumoLogic/sumologic-documentation pull request #2692
Opened 2023-06-29 05:48 UTC by sumoanema

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [X] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-06-29 08:33 UTC, JV0812 commented on docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
> +* Monitor Successful and Failed logins by the user and track their locations with successful and failed login attempts.
```suggestion
* Monitor successful and failed logins by the user and track their locations with successful and failed login attempts.
```

2023-06-29 08:40 UTC, JV0812 commented on docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
> +* Monitor RDP (Remote Desktop) reconnect events.
```suggestion
* Monitor RDP reconnect events.
```

2023-06-29 08:43 UTC, JV0812 commented on docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
> +* Track if there are failed login outliers to identify mischievous login activities.
```suggestion
* Track failed login outliers to identify mischievous login activities.
```

2023-06-29 08:48 UTC, sumoanema commented
@JV0812 applied the suggestion.  Could you please review.

2023-06-29 08:54 UTC, JV0812 approved these changes

2023-06-29 18:26 UTC, kimsauce commented on docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
> +The **Windows - Overview** dashboard provides insights into fatal or warning messages, policy changes system restarts and changes to administrative groups.
```suggestion
The **Windows - Overview** dashboard provides insights into fatal or warning messages, policy changes, system restarts, and changes to administrative groups.
```

2023-06-29 18:26 UTC, kimsauce requested changes
minor fix

2023-06-30 18:38 UTC, kimsauce commented on docs/integrations/hosts-operating-systems/opentelemetry/windows-opentelemetry.md
> +Following are the [fields](/docs/manage/fields/) which will be created as part of Windows App install if not already present.
```suggestion
Following are the [fields](/docs/manage/fields/) that will be created as part of Windows App install if not already present. 
```

2023-06-30 18:39 UTC, kimsauce approved these changes

2023-07-04 05:06 UTC, JV0812 commented
The intent of this PR is covered i PR: https://github.com/SumoLogic/sumologic-documentation/pull/2705. So closing this PR.

2023-07-04 05:06 UTC, closed without merging

2023-07-05 19:50 UTC, jpipkin1 commented
@JV0812, since you closed this PR with unmerged commits, you may want to delete the branch. (Scroll down to the "Closed with unmerged commits" box and click "Delete branch".)