Log Level GA (7/11)
SumoLogic/sumologic-documentation pull request #2704
Opened 2023-06-29 23:16 UTC by kimsauce

## Purpose of this pull request

GA - Log level detection feature

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-07-05 19:58 UTC, jpipkin1 requested changes
@kimsauce, since beta is complete, [log-level](https://github.com/SumoLogic/sumologic-documentation/pull/2704/files#diff-3eaef3edc9480eee9ed9d32ac7bcb0d3bcc76892bd85bf38905ed4ca528e270b) file needs to be added to sidebars.ts.

2023-07-05 19:59 UTC, kimsauce commented
> @kimsauce, since beta is complete, [log-level](https://github.com/SumoLogic/sumologic-documentation/pull/2704/files#diff-3eaef3edc9480eee9ed9d32ac7bcb0d3bcc76892bd85bf38905ed4ca528e270b) needs to be added to sidebars.ts.

great catch!

2023-07-05 20:01 UTC, kimsauce commented on sidebars.ts
> +            'cse/automation-service/automation-service-app-central',
```suggestion
            'cse/automation-service/automation-service-app-central', 
```

2023-07-05 20:02 UTC, kimsauce commented on sidebars.ts
> +            'cse/automation-service/automation-service-app-central',
```suggestion
            'cse/automation-service/automation-service-app-central',
```

2023-07-05 21:01 UTC, jpipkin1 approved these changes
Looks good, @kimsauce. Approved.

2023-07-05 21:22 UTC, jpipkin1 commented
@kimsauce, it looks like this PR is a duplicate of PR #2567.

2023-07-05 21:35 UTC, kimsauce commented
> @kimsauce, it looks like this PR is a duplicate of PR #2567.

Oh yeah, I saw that this morning! Just merged the two together.

2023-07-10 04:22 UTC, tarunk2 commented on blog-service/2023-07-14-log-search.md
> +title: July 14, 2023 (Search)
```suggestion
title: July 10, 2023 (Search)
```

2023-07-10 04:53 UTC, tarunk2 approved these changes

2023-07-10 05:19 UTC, merged