TRIDENT-18006 - MITRE coverage
SumoLogic/sumologic-documentation pull request #2718
Opened 2023-07-04 19:29 UTC by jpipkin1

## Purpose of this pull request

This pull request (PR) adds a new article:
https://help.sumologic.com/docs/cse/administration/mitre-coverage/

Issue number:  [TRIDENT-18006](https://sumologic.atlassian.net/browse/TRIDENT-18006)

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-07-05 13:59 UTC, jpipkin1 commented
This PR is in draft until all SME comments are done.

2023-07-05 20:09 UTC, kimsauce commented on docs/cse/administration/mitre-coverage.md
> +Click **Rules** at the bottom of the panel to get links to all the rules that contribute to coverage for the tactic/technique.
```suggestion
When you click a square in the tactics/techniques matrix, details about coverage for that tactic/technique display in a panel. The panel has a full description of the tactic/technique, with an assessment of your coverage (**None**, **Low**, **Medium**, and **High**). A coverage of **None** does not mean you have no coverage; it only means you might not have enough rules to adequately cover the tactic/technique.

Click **Rules** at the bottom of the panel to get links to all the rules that contribute to coverage for the tactic/technique.  
```

2023-07-05 20:10 UTC, kimsauce requested changes
one minor thing

2023-07-05 20:59 UTC, jpipkin1 commented
Good suggestion, @kimsauce.

2023-07-05 21:04 UTC, kimsauce approved these changes

2023-08-15 13:55 UTC, jpipkin1 commented
@pkazmir-sumo, could you review this PR?

2023-10-02 17:45 UTC, merged