JumpCloud Directory Insights C2C doc
SumoLogic/sumologic-documentation pull request #2721
Opened 2023-07-05 12:45 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-07-05 19:07 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
> +When you create an JumpCloud Directory Insights source, it goes through the following stages:
```suggestion
When you create a JumpCloud Directory Insights source, it goes through the following stages:
```

2023-07-05 19:07 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
> +When you create an JumpCloud Directory Insights source, you add it to a Hosted Collector. Before creating the source, identify the Hosted Collector you want to use or create a new Hosted Collector. F
```suggestion
When you create a JumpCloud Directory Insights source, you add it to a Hosted Collector. Before creating the source, identify the Hosted Collector you want to use or create a new Hosted Collector. For instructions, see [Configure a Hosted Collector](/docs/send-data/hosted-collectors/configure-hosted-collector).
```

2023-07-05 19:08 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
> +To configure a Code42 Incydr Source:
```suggestion
To configure a JumpCloud Directory Insights source:
```

2023-07-05 19:12 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
> +Sources can be configured using UTF-8 encoded JSON files with the Collector Management API. See [how to use JSON to configure Sources](/docs/send-data/use-json-configure-sources) for details. 
```suggestion
Sources can be configured using UTF-8 encoded JSON files with the Collector Management API. See [Use JSON to Configure Sources](/docs/send-data/use-json-configure-sources) for details. 
```

2023-07-05 19:13 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
> +| `config` | JSON Object  | Yes | Contains the [configuration-parameters](#config-parameters) of the Source. | n/a |
```suggestion
| `config` | JSON Object  | Yes | Contains the [configuration parameters](#config-parameters) of the Source. | n/a |
```

2023-07-05 19:13 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
> +| `name` | String | Yes | Type the desired name of the Source and it must be unique per Collector. This value is assigned to the `metadata field _source`.  | modifiable |
```suggestion
| `name` | String | Yes | Type the desired name of the Source. It must be unique per Collector. This value is assigned to the `metadata field _source`.  | modifiable |
```

2023-07-05 19:15 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
> +## Set up and Configuration
```suggestion
## Setup and Configuration
```

2023-07-05 19:16 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
> +## Data Source
```suggestion
## Data source
```

2023-07-05 19:16 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
> +### Error Types
```suggestion
### Error types
```

2023-07-05 19:16 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
> +### Restarting your Source
```suggestion
### Restarting your source
```

2023-07-05 19:17 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jumpcloud-directory-insights-source.md
> +### JSON Example
```suggestion
### JSON example
```

2023-07-05 19:17 UTC, jpipkin1 requested changes
This article looks very good, @JV0812! I had only a few minor comments.

2023-07-06 05:10 UTC, JV0812 commented
Thanks John! I have incorporated your comments.

2023-07-06 14:43 UTC, jpipkin1 approved these changes
It looks good, @JV0812! Approved.

2023-07-07 10:07 UTC, merged