Lat Arriving Metrics Doc changes
SumoLogic/sumologic-documentation pull request #2800
Opened 2023-07-19 21:20 UTC by angadrandhawa1

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-07-19 21:21 UTC, angadrandhawa1 commented
Do Not auto merge.

2023-07-19 21:30 UTC, angadrandhawa1 commented on docs/send-data/hosted-collectors/http-source/otlp.md
> +1. Metrics reported with a timestamp older than 24 hours ago or newer than 24 hours in the future from the time they are reported are dropped. Please make sure that the Metrics sent HTTP Endpoint hav
```suggestion
1. Metrics reported with a timestamp older than 24 hours ago or newer than 24 hours in the future from the time they are reported are dropped. Please make sure that the Metrics sent to OTLP Endpoint have appropriate timestamps.
```

2023-07-19 21:30 UTC, angadrandhawa1 commented on docs/send-data/hosted-collectors/http-source/logs-metrics/upload-metrics.md
> +1. Metrics reported with a timestamp older than 24 hours ago or newer than 24 hours in the future from the time they are reported are dropped. Please make sure that the Metrics sent HTTP Endpoint hav
```suggestion
1. Metrics reported with a timestamp older than 24 hours ago or newer than 24 hours in the future from the time they are reported are dropped. Please make sure that the Metrics sent to HTTP Endpoint have appropriate timestamps.
```

2023-07-19 22:53 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/http-source/logs-metrics/index.md
> +
```suggestion
:::note
* Metrics reported with a timestamp older than 24 hours ago or newer than 24 hours in the future from the time they are reported are dropped. Please make sure that the Metrics sent to HTTP Endpoint have appropriate timestamps.
* Sumo Logic enforces limits on the volume of metrics and associated metadata you ingest. For more information, see Data Limits for Metrics. 
:::
```

2023-07-19 22:57 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/http-source/logs-metrics/upload-metrics.md
> +2. Sumo Logic enforces limits on the volume of metrics and associated metadata you ingest. For more information, see Data Limits for Metrics.
```suggestion
* Metrics reported with a timestamp older than 24 hours ago or newer than 24 hours in the future from the time they are reported are dropped. Please make sure that the Metrics sent to HTTP Endpoint have appropriate timestamps.
* Sumo Logic enforces limits on the volume of metrics and associated metadata you ingest. For more information, see [Data Limits for Metrics](/docs/metrics/manage-metric-volume/data-limits-for-metrics).
```

2023-07-19 22:58 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/http-source/otlp.md
> +:::
```suggestion
:::note
* Metrics reported with a timestamp older than 24 hours ago or newer than 24 hours in the future from the time they are reported are dropped. Please make sure that the Metrics sent to OTLP Endpoint have appropriate timestamps.
* Sumo Logic enforces limits on the volume of metrics and associated metadata you ingest. For more information, see [Data Limits for Metrics](/docs/metrics/manage-metric-volume/data-limits-for-metrics).
:::
```

2023-07-19 23:00 UTC, jpipkin1 commented on docs/send-data/installed-collectors/sources/streaming-metrics-source.md
> +Metrics reported with a timestamp older than 24 hours ago or newer than 24 hours in the future from the time they are reported are dropped. Please make sure that the Metrics sent to the Streaming Met
```suggestion
Metrics reported with a timestamp older than 24 hours ago or newer than 24 hours in the future from the time they are reported are dropped. Make sure that the Metrics sent to the Streaming Metrics source have appropriate timestamps.
```

2023-07-19 23:02 UTC, jpipkin1 requested changes
@angadrandhawa1, I have just a few updates for you. Click the **Commit suggestion** button to make the updates. Then I will approve the PR.

In the future, if you have repeating information that will appear in multiple articles, consider [reusing content](https://help.sumologic.com/docs/contributing/style-guide/#reusing-content).

2023-07-20 12:46 UTC, aszczepaniksumo commented
Let's close this PR as a duplicate, as I moved changes from this PR to a different one (which includes more doc updates & release notes).
https://github.com/SumoLogic/sumologic-documentation/pull/2804

2023-07-20 14:01 UTC, jpipkin1 commented
Closing this PR because it it replaced by PR #2804 per @aszczepaniksumo.

2023-07-20 14:01 UTC, closed without merging

2023-07-20 14:02 UTC, jpipkin1 commented
Closing this PR because it it replaced by PR #2804 per @aszczepaniksumo.