Updated Gmail Trace Logs Source doc
SumoLogic/sumologic-documentation pull request #2820
Opened 2023-07-24 05:36 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-07-24 13:10 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source.md
> +1. **Dataset ID**. Enter the The Dataset ID is the project-wise unique identifier for your dataset.
```suggestion
1. **Dataset ID**. Enter the ID. The Dataset ID is the project-wise unique identifier for your dataset. 
```

2023-07-24 13:11 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/gmail-tracelogs-source.md
> +1. **Private Key**. Enter the private key of Service Account JSON, it is a security key which is required for authentication. You can find this from the Google Cloud Console.
```suggestion
1. **Private Key**. Enter the private key of Service Account JSON. This is a security key which is required for authentication. You can find this from the Google Cloud Console.
```

2023-07-24 13:14 UTC, jpipkin1 requested changes
This is very good, @JV0812. I found only a few little things.

2023-07-25 09:18 UTC, JV0812 commented
Thanks John. I have incorporated your comments.

2023-07-25 14:28 UTC, jpipkin1 approved these changes

2023-07-25 14:43 UTC, merged