zoom source doc updated
SumoLogic/sumologic-documentation pull request #2845
Opened 2023-07-27 05:47 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-07-27 17:23 UTC, kimsauce commented on docs/send-data/hosted-collectors/webhook-sources/zoom.md
> +| `URL` | String | No | Assigned by Sumo Logic for Zoom Source. | Used to set up Event Based Notifications with Zoom. This value is created and assigned by Sumo Logic when the Source is created. |
```suggestion
| `URL` | String | No | Assigned by Sumo Logic for Zoom Source. | Used to set up event-based notifications with Zoom. This value is created and assigned by Sumo Logic when the Source is created. |
```

2023-07-27 17:23 UTC, kimsauce requested changes
small fix

2023-08-01 17:06 UTC, kimsauce approved these changes

2023-09-18 16:02 UTC, rishiyemme approved these changes

2023-09-20 11:03 UTC, merged