Update Search URL to include parameterized search
SumoLogic/sumologic-documentation pull request #2866
Opened 2023-08-01 05:51 UTC by manashar4

This update adds the documentation around existing capability of Search URL to support Parameterized Search

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-08-01 15:28 UTC, jpipkin1 commented on docs/search/get-started-with-search/build-search/use-url-to-run-search.md
> +The custom URL that launches this log query in the Sumo Logic Search page would be similar to the following. The exact URL would depend on your Sumo Logic account endpoint, as listed in [Sumo Logic E
```suggestion
The custom URL that launches this log query in the Sumo Logic Search page would be similar to the following. The exact URL would depend on your Sumo Logic account endpoint, as listed in [Sumo Logic Endpoints by Deployment and Firewall Security](/docs/api/getting-started#sumo-logic-endpoints-by-deployment-and-firewall-security). 
```

2023-08-01 15:29 UTC, jpipkin1 commented on docs/search/get-started-with-search/build-search/use-url-to-run-search.md
> +### Templatized Query URL
```suggestion
### Templatized query URL
```

2023-08-01 15:29 UTC, jpipkin1 commented on docs/search/get-started-with-search/build-search/use-url-to-run-search.md
> +### Standard Query URL
```suggestion
### Standard query URL
```

2023-08-01 15:31 UTC, jpipkin1 requested changes
This PR looks great, @manashar4. I had a few minor suggestions. If you like them, click the "Commit suggestion" button. After you have resolved all the comments, I will approve the PR.

2023-08-01 15:34 UTC, jpipkin1 commented
@manashar4, also click the "sign your name here" link in the **cla-bot** box above and follow the directions.

2023-08-03 02:42 UTC, kimsauce approved these changes

2023-08-03 13:46 UTC, jpipkin1 approved these changes

2023-08-03 14:01 UTC, merged