Update entity group for inventory
SumoLogic/sumologic-documentation pull request #2910
Opened 2023-08-08 16:10 UTC by jpipkin1

## Purpose of this pull request

This pull request (PR) updates the following article with a new **Inventory Key** field:
https://help.sumologic.com/docs/cse/records-signals-entities-insights/create-an-entity-group/

Issue number: Asana ticket [Document Entity groups enhancement](https://app.asana.com/0/1183741177809740/1205206983224230/f)

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-08-08 20:27 UTC, kimsauce commented on docs/cse/records-signals-entities-insights/create-an-entity-group.md
> +You can use the the `/entity-group-configuration` API to create, read, update and delete Entity Groups. For more information, see [Cloud SIEM APIs](/docs/cse/administration/cse-apis).
```suggestion
You can use the `/entity-group-configuration` API to create, read, update and delete Entity Groups. For more information, see [Cloud SIEM APIs](/docs/cse/administration/cse-apis).
```

2023-08-08 20:27 UTC, kimsauce requested changes
minor fix

2023-08-08 20:51 UTC, jpipkin1 commented
Thanks for the review, @kimsauce!

2023-08-08 21:38 UTC, kimsauce approved these changes

2023-08-15 13:44 UTC, jpipkin1 commented
@pkazmir-sumo, could you review this PR?

2023-08-15 21:36 UTC, AngelATX commented
Screenshots are a little out of date, might need to update them now. Here is what it looks like now:
<img width="561" alt="Screenshot 2023-08-15 at 4 35 05 PM" src="https://github.com/SumoLogic/sumologic-documentation/assets/104445515/a0591438-dcbd-4ac2-b4e9-4b30f2d6d89b">

Also didn't see much mention of the

2023-08-15 22:06 UTC, jpipkin1 commented
Thanks for letting me know, @AngelATX. I'll update the screenshots to the latest version available in the CSE Sandbox.

2023-08-16 17:43 UTC, AngelATX approved these changes
Looks good to me.

2023-08-16 18:22 UTC, jpipkin1 commented
Thanks for the review, @AngelATX.

2023-08-17 17:27 UTC, merged