AWS amplify apps doc added
SumoLogic/sumologic-documentation pull request #2920
Opened 2023-08-10 14:13 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-08-10 15:58 UTC, kimsauce reviewed
Hi @JV0812 , it looks like their most recent logo is orange now (example [here](https://twitter.com/AWSAmplify)). Were the devs going to use this older red one in our UI?

2023-08-11 13:28 UTC, JV0812 commented
@kimsauce this logo is taken from the [AWS](https://aws.amazon.com/architecture/icons/) itself. And we are using the same icon in our App catalog.

2023-08-11 14:40 UTC, jpipkin1 commented on docs/integrations/amazon-aws/aws-amplify.md
> +* Collect CloudWatch Metrics with namespace AWS/AmplifyHosting using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-met
```suggestion
* Collect CloudWatch Metrics with namespace AWS/AmplifyHosting using [AWS Kinesis Firehose for Metrics](/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source/) source. For AWS/AmplifyHosting metrics and dimensions refer to [AWS Amplify CloudWatch metrics](https://docs.aws.amazon.com/amplify/latest/userguide/access-logs.html#monitoring-with-cloudwatch).
```

2023-08-11 14:40 UTC, jpipkin1 commented on docs/integrations/amazon-aws/aws-amplify.md
> +* AWS Amplify stores access logs for all the apps you host in Amplify. Collect **Access Logs** using [Amazon S3](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-s3-source/)
```suggestion
* AWS Amplify stores access logs for all the apps you host in Amplify. Collect **Access Logs** using [Amazon S3](/docs/send-data/hosted-collectors/amazon-aws/aws-s3-source/) source.
```

2023-08-11 14:41 UTC, jpipkin1 commented on docs/integrations/amazon-aws/aws-amplify.md
> +* AWS Amplify is integrated with AWS CloudTrail, a service that provides a record of actions taken by a user, role, or an AWS service in Amplify. CloudTrail captures all API calls for Amplify as even
```suggestion
* AWS Amplify is integrated with AWS CloudTrail, a service that provides a record of actions taken by a user, role, or an AWS service in Amplify. CloudTrail captures all API calls for Amplify as events. The calls captured include calls from the Amplify console and code calls to the Amplify API operations. If you create a trail, you can enable continuous delivery of CloudTrail events to an Amazon S3 bucket, including events for Amplify. Collect [AWS CloudTrail Logs](https://docs.aws.amazon.com/amplify/latest/userguide/logging-using-cloudtrail.html) using [AWS CloudTrail](/docs/send-data/hosted-collectors/amazon-aws/aws-cloudtrail-source/) source.
```

2023-08-11 14:42 UTC, jpipkin1 requested changes
Minor updates.

2023-08-11 14:52 UTC, JV0812 commented
Thanks for your review John. I have incorpotated your comments.

2023-08-11 15:00 UTC, jpipkin1 approved these changes

2023-08-11 18:06 UTC, kimsauce commented on docs/integrations/amazon-aws/aws-amplify.md
> +AWS Amplify is a set of purpose-built tools and features that enables frontend web and mobile developers to quickly and easily build full-stack applications on AWS. For further details refer to [AWS
```suggestion
AWS Amplify is a set of purpose-built tools and features that enables frontend web and mobile developers to quickly and easily build full-stack applications on AWS. For more details, refer to the [AWS documentation](https://docs.aws.amazon.com/amplify/latest/userguide/welcome.html).
```

2023-08-11 18:06 UTC, kimsauce commented on docs/integrations/amazon-aws/aws-amplify.md
> +
```suggestion
* AWS Amplify stores access logs for all the apps you host in Amplify. Collect **Access Logs** using [Amazon S3](/docs/send-data/hosted-collectors/amazon-aws/aws-s3-source/) source.
```

2023-08-16 17:10 UTC, merged