Postman integration doc
SumoLogic/sumologic-documentation pull request #2924
Opened 2023-08-11 11:18 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-08-11 14:19 UTC, jpipkin1 commented on docs/integrations/webhooks/postman.md
> +The Sumo Logic integration for Postman ingests Postman events into Sumo Logic through an outgoing webhook available in Postman. For more information on supported events that are ingested through the
```suggestion
The Sumo Logic integration for Postman ingests Postman events into Sumo Logic through an outgoing webhook available in Postman. For more information on supported events that are ingested through the Postman webhook, refer to [Postman documentation](https://learning.postman.com/docs/integrations/webhooks/).
```

2023-08-11 14:20 UTC, jpipkin1 commented on docs/integrations/webhooks/postman.md
> +1. In the Sumo Logic portal, create a new [Hosted Collector](https://help.sumologic.com/docs/send-data/hosted-collectors/configure-hosted-collector/) or use an existing one. Then add a [HTTP Logs and
```suggestion
1. In the Sumo Logic portal, create a new [Hosted Collector](/docs/send-data/hosted-collectors/configure-hosted-collector/) or use an existing one. Then add an [HTTP Logs and Metrics Source](/docs/send-data/hosted-collectors/http-source/logs-metrics#configure-an-httplogs-and-metrics-source). 
```

2023-08-11 14:21 UTC, jpipkin1 commented on docs/integrations/webhooks/postman.md
> +Follow the below steps to configure the Postman Webhook:
```suggestion
Follow the below steps to configure the Postman webhook:
```

2023-08-11 14:22 UTC, jpipkin1 commented on docs/integrations/webhooks/postman.md
> +1. Enter Webhook form data as follows:
```suggestion
1. Enter webhook form data as follows:
```

2023-08-11 14:23 UTC, jpipkin1 commented on docs/integrations/webhooks/postman.md
> +- For detailed information about webhook creation, refer [Postman Documentation](https://learning.postman.com/docs/integrations/webhooks/).
```suggestion
- For detailed information about webhook creation, refer to [Postman documentation](https://learning.postman.com/docs/integrations/webhooks/).
```

2023-08-11 14:24 UTC, jpipkin1 commented on docs/integrations/webhooks/postman.md
> +- For support, contact [Postman support center](https://support.postman.com/hc/en-us).
```suggestion
- For support, contact the [Postman support center](https://support.postman.com/hc/en-us). 
```

2023-08-11 14:24 UTC, jpipkin1 requested changes
@JV0812, I mostly have minor updates.

2023-08-11 14:32 UTC, JV0812 commented
@jpipkin1 Thanks for your review John. I have fixed your comments.

2023-08-11 14:35 UTC, jpipkin1 approved these changes

2023-08-11 14:36 UTC, jpipkin1 commented
Approved, @JV0812.

I just now noticed you need to create a hub page for "Webhooks" in the left nav.  But in my opinion it's not essential. You can do that later if you want.

2023-08-11 14:39 UTC, JV0812 commented
Yes John. I will create it later. 
There will be around 100 webhooks apps docs added to this folder, so I thought I can create the webhooks hub page once all the apps are added. By this we can reduce the continuous update of this page whenever a new app is added.

2023-08-11 18:22 UTC, kimsauce commented on docs/integrations/webhooks/postman.md
> +3. Copy and save the endpoint URL of source.
```suggestion
2. Configure **Source Category** in the HTTP Source. For example, configure as `webhook/postman` for the Postman app.
3. Copy and save the endpoint URL of source.
```

2023-08-11 18:29 UTC, kimsauce reviewed
@JV0812 I've swapped out image with hi-res version

2023-08-11 18:32 UTC, kimsauce commented on sidebars.ts
> +          'integrations/webhooks/postman',
```suggestion
          'integrations/webhooks/buddy',
          'integrations/webhooks/postman',
```

2023-08-11 19:17 UTC, jpipkin1 commented
@kimsauce, your sidebar change is causing the build to fail ([details](https://github.com/SumoLogic/sumologic-documentation/actions/runs/5835987239/job/15828632478?pr=2924)):
> Error:  Error: Invalid sidebar file at "sidebars.ts".

2023-08-11 19:22 UTC, kimsauce commented on sidebars.ts
> +          'integrations/webhooks/buddy',
```suggestion
```

2023-12-21 08:16 UTC, closed without merging

2023-12-21 08:16 UTC, JV0812 commented
The intent of this PR is covered through a consolidated PR.