Initial checkin for 10 AWS specific doc only app pages.
SumoLogic/sumologic-documentation pull request #2948
Opened 2023-08-17 09:40 UTC by npande

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-08-17 09:58 UTC, JV0812 commented on docs/integrations/amazon-aws/amazon-appflow.md
> +* Collect CloudWatch Metrics with namespace AWS/AppFlow using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-so
```suggestion
* Collect CloudWatch Metrics with namespace AWS/AppFlow using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source/) source. For AWS/AppFlow metrics and dimensions refer to [Amazom AppFlow CloudWatch metrics](https://docs.aws.amazon.com/appflow/latest/userguide/monitoring-cloudwatch.html).
```

2023-08-17 09:58 UTC, JV0812 commented on docs/integrations/amazon-aws/amazon-appflow.md
> +
```suggestion
```

2023-08-17 10:00 UTC, JV0812 commented on docs/integrations/amazon-aws/amazon-appstream2.md
> +* Collect CloudWatch Metrics with namespace AWS/AppStream using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-
```suggestion
* Collect CloudWatch Metrics with namespace AWS/AppStream using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source/) source. For AWS/AppStream metrics and dimensions refer to [Amazon AppStream 2.0 CloudWatch metrics](https://docs.aws.amazon.com/appstream2/latest/developerguide/monitoring.html#monitoring-with-cloudwatch).
```

2023-08-17 10:01 UTC, JV0812 commented on docs/integrations/amazon-aws/amazon-athena.md
> +
```suggestion
```

2023-08-17 10:01 UTC, JV0812 commented on docs/integrations/amazon-aws/amazon-athena.md
> +* Collect CloudWatch Metrics with namespace AWS/Athena using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-sou
```suggestion
* Collect CloudWatch Metrics with namespace AWS/Athena using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source/) source. For AWS/Athena metrics and dimensions refer to [Amazon Athena CloudWatch metrics](https://docs.aws.amazon.com/athena/latest/ug/query-metrics-viewing.html#athena-cloudwatch-metrics-table).
```

2023-08-17 10:02 UTC, JV0812 commented on docs/integrations/amazon-aws/amazon-cloudfront.md
> +
```suggestion
```

2023-08-17 10:02 UTC, JV0812 commented on docs/integrations/amazon-aws/amazon-cloudfront.md
> +* Collect CloudWatch Metrics with namespace [AWS/CloudFront](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/monitoring-using-cloudwatch.html) using [AWS Kinesis Firehose for Metri
```suggestion
* Collect CloudWatch Metrics with namespace [AWS/CloudFront](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/monitoring-using-cloudwatch.html) using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source/) source. For AWS/CloudFront metrics and dimensions refer to [Amazon CloudFront CloudWatch metrics](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/programming-cloudwatch-metrics.html).
```

2023-08-17 10:03 UTC, JV0812 commented on docs/integrations/amazon-aws/aws-apprunner.md
> +
```suggestion
```

2023-08-17 10:03 UTC, JV0812 commented on docs/integrations/amazon-aws/aws-apprunner.md
> +* Collect CloudWatch Metrics with namespace AWS/AppRunner using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-
```suggestion
* Collect CloudWatch Metrics with namespace AWS/AppRunner using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source/) source. For AWS/AppRunner metrics and dimensions refer to [AWS App Runner CloudWatch metrics](https://docs.aws.amazon.com/apprunner/latest/dg/monitor-cw.html).
```

2023-08-17 10:04 UTC, JV0812 commented on docs/integrations/amazon-aws/aws-appsync.md
> +
```suggestion
```

2023-08-17 10:04 UTC, JV0812 commented on docs/integrations/amazon-aws/aws-appsync.md
> +* Collect CloudWatch Metrics with namespace AWS/AppSync using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-so
```suggestion
* Collect CloudWatch Metrics with namespace AWS/AppSync using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source/) source. For AWS/AppSync metrics and dimensions refer to [AWS AppSync CloudWatch metrics](https://docs.aws.amazon.com/appsync/latest/devguide/monitoring.html#cw-metrics).
```

2023-08-17 10:04 UTC, JV0812 commented on docs/integrations/amazon-aws/aws-backup.md
> +
```suggestion
```

2023-08-17 10:05 UTC, JV0812 commented on docs/integrations/amazon-aws/aws-backup.md
> +* Collect CloudWatch Metrics with namespace AWS/Backup using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-sou
```suggestion
* Collect CloudWatch Metrics with namespace AWS/Backup using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source/) source. For AWS/Backup metrics and dimensions refer to [AWS Backup CloudWatch metrics](https://docs.aws.amazon.com/aws-backup/latest/devguide/cloudwatch.html#monitoring-metrics-with-cloudwatch).
```

2023-08-17 10:05 UTC, JV0812 commented on docs/integrations/amazon-aws/aws-certificate-manager.md
> +
```suggestion
```

2023-08-17 10:06 UTC, JV0812 commented on docs/integrations/amazon-aws/aws-certificate-manager.md
> +* Collect CloudWatch Metrics with namespace AWS/CertificateManager using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose
```suggestion
* Collect CloudWatch Metrics with namespace AWS/CertificateManager using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source/) source. For AWS/CertificateManager metrics and dimensions refer to [AWS Certificate Manager CloudWatch metrics](https://docs.aws.amazon.com/acm/latest/userguide/cloudwatch-metrics.html).
```

2023-08-17 10:19 UTC, JV0812 commented on docs/integrations/amazon-aws/aws-chatbot.md
> +AWS Chatbot is an AWS service that enables DevOps and software development teams to use messaging program chat rooms to monitor and respond to operational events in their AWS Cloud. AWS Chatbot proce
```suggestion
AWS Chatbot is an AWS service that enables DevOps and software development teams to use messaging program chat rooms to monitor and respond to operational events in their AWS Cloud. AWS Chatbot processes AWS service notifications from Amazon Simple Notification Service (Amazon SNS) and forwards them to chat rooms so teams can analyze and act on them immediately, regardless of location.
```

2023-08-17 10:19 UTC, JV0812 commented on docs/integrations/amazon-aws/aws-chatbot.md
> +* Collect CloudWatch Metrics with namespace AWS/Chatbot using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-so
```suggestion
* Collect CloudWatch Metrics with namespace AWS/Chatbot using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source/) source. For AWS/Chatbot metrics and dimensions refer to [AWS Chatbot CloudWatch metrics](https://docs.aws.amazon.com//chatbot/latest/adminguide/monitoring-cloudwatch.html#available-cloudwatch-metrics).
```

2023-08-17 10:21 UTC, JV0812 commented on docs/integrations/amazon-aws/aws-private-certificate-authority.md
> +AWS Private CA enables creation of private certificate authority (CA) hierarchies, including root and subordinate CAs, without the investment and maintenance costs of operating an on-premises CA. You
```suggestion
AWS Private CA enables the creation of private certificate authority (CA) hierarchies, including root and subordinate CAs, without the investment and maintenance costs of operating an on-premises CA. Your private CAs can issue end-entity X.509 certificates useful in scenarios including:
```

2023-08-17 10:22 UTC, JV0812 commented on docs/integrations/amazon-aws/aws-private-certificate-authority.md
> +* Collect CloudWatch Metrics with namespace AWS/ACMPrivateCA using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metri
```suggestion
* Collect CloudWatch Metrics with namespace AWS/ACMPrivateCA using [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source/) source. For AWS/ACMPrivateCA metrics and dimensions refer to [AWS Private Certificate Authority CloudWatch metrics](https://docs.aws.amazon.com/privateca/latest/userguide/PcaCloudWatch.html).
```

2023-08-17 11:07 UTC, JV0812 approved these changes
LGTM

2023-08-18 06:02 UTC, kimsauce requested changes
@npande , there are several instances where you'll need to convert docs links to relative links. I've commented on a few but there are more.

2023-08-18 06:02 UTC, kimsauce commented on docs/integrations/amazon-aws/amazon-appflow.md
> +* Collect [AWS CloudTrail Logs](https://docs.aws.amazon.com/appflow/latest/userguide/appflow-cloudtrail-logs.html) using the [AWS CloudTrail](https://help.sumologic.com/docs/send-data/hosted-collecto
```suggestion
* Collect [AWS CloudTrail Logs](https://docs.aws.amazon.com/appflow/latest/userguide/appflow-cloudtrail-logs.html) using the [AWS CloudTrail](/docs/send-data/hosted-collectors/amazon-aws/aws-cloudtrail-source/) source. Amazon AppFlow is integrated with AWS CloudTrail, a service that provides a record of actions taken by a user, role, or AWS service in Amazon AppFlow. CloudTrail captures all API calls for Amazon AppFlow as events, which includes calls from the Amazon AppFlow console and code calls to the Amazon AppFlow API operations. If you create a trail, you can enable continuous delivery of CloudTrail events to an Amazon S3 bucket, including events for Amazon AppFlow. 
```

2023-08-18 06:02 UTC, kimsauce commented on docs/integrations/amazon-aws/amazon-appflow.md
> +* Collect [AWS CloudTrail Logs](https://docs.aws.amazon.com/appflow/latest/userguide/appflow-cloudtrail-logs.html) using the [AWS CloudTrail](https://help.sumologic.com/docs/send-data/hosted-collecto
```suggestion
* Collect [AWS CloudTrail Logs](https://docs.aws.amazon.com/appflow/latest/userguide/appflow-cloudtrail-logs.html) using the [AWS CloudTrail](/docs/send-data/hosted-collectors/amazon-aws/aws-cloudtrail-source/) source. Amazon AppFlow is integrated with AWS CloudTrail, a service that provides a record of actions taken by a user, role, or AWS service in Amazon AppFlow. CloudTrail captures all API calls for Amazon AppFlow as events, which includes calls from the Amazon AppFlow console and code calls to the Amazon AppFlow API operations. If you create a trail, you can enable continuous delivery of CloudTrail events to an Amazon S3 bucket, including events for Amazon AppFlow. 
```

2023-08-18 06:02 UTC, kimsauce commented on docs/integrations/amazon-aws/amazon-appstream2.md
> +* Collect **CloudWatch Metrics** with namespace `AWS/AppStream` using the [AWS Kinesis Firehose for Metrics](https://help.sumologic.com/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehos
```suggestion
* Collect **CloudWatch Metrics** with namespace `AWS/AppStream` using the [AWS Kinesis Firehose for Metrics](/docs/send-data/hosted-collectors/amazon-aws/aws-kinesis-firehose-metrics-source/) source. For `AWS/AppStream` metrics and dimensions, refer to [Amazon AppStream 2.0 CloudWatch metrics](https://docs.aws.amazon.com/appstream2/latest/developerguide/monitoring.html#monitoring-with-cloudwatch).
```

2023-08-18 06:02 UTC, kimsauce commented on docs/integrations/amazon-aws/amazon-appstream2.md
> +* Collect [AWS CloudTrail Logs](https://docs.aws.amazon.com/appstream2/latest/developerguide/logging-using-cloudtrail.html) using the [AWS CloudTrail](https://help.sumologic.com/docs/send-data/hosted
```suggestion
* Collect [AWS CloudTrail Logs](https://docs.aws.amazon.com/appstream2/latest/developerguide/logging-using-cloudtrail.html) using the [AWS CloudTrail](/docs/send-data/hosted-collectors/amazon-aws/aws-cloudtrail-source/) source. Amazon AppStream 2.0 is integrated with AWS CloudTrail, a service that provides a record of actions taken by a user, role, or AWS service in AppStream 2.0. CloudTrail captures API calls for AppStream 2.0 as events, which include calls from the AppStream 2.0 console and code calls to the AppStream 2.0 API operations. If you create a trail, you can enable continuous delivery of CloudTrail events to an Amazon S3 bucket, including events for AppStream 2.0. 
```

2023-08-18 08:25 UTC, npande commented
> @npande , there are several instances where you'll need to convert docs links to relative links. I've commented on a few but there are more.

We are having README.md in the apps repo , we cannot use relative paths. We are using the content of same README.md file in the docs repo. Can docs team update relative links in the documentation repo?

2023-08-18 12:45 UTC, JV0812 commented
I will take care of this action. While I update the index page I will update these links too.

2023-08-23 10:17 UTC, merged