gcp doc only app - bigtable
SumoLogic/sumologic-documentation pull request #2978
Opened 2023-08-23 17:46 UTC by sumoanema

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [X] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-08-24 14:40 UTC, jpipkin1 commented
I added Google Cloud Bigtable to the left nav with this commit: "[Add Bigtable app to sidebar](https://github.com/SumoLogic/sumologic-documentation/pull/2978/commits/2377e1f1d5f0a79ccb11b50e63acc63fa8a456b2)".

2023-08-24 14:52 UTC, jpipkin1 requested changes
@sumoanema, the Bigtable article is incomplete. It should follow this template: https://github.com/SumoLogic/sumologic-documentation/blob/main/docs/contributing/templates/partner-app.md

Could you take another pass at it? Take a look at other articles in the Google apps section for examples of how to write an app article:
https://help.sumologic.com/docs/integrations/google/

I'm placing this PR in draft mode until you have it ready for another review.

2023-08-24 18:30 UTC, kimsauce commented on docs/integrations/google/cloud-bigtable.md
> +Bigtable is a fully managed wide-column and key-value NoSQL database service for large analytical and operational workloads. For further details refer [GCP documentation](https://cloud.google.com/big
```suggestion
Bigtable is a fully managed wide-column and key-value NoSQL database service for large analytical and operational workloads. For further details, see the [Google Cloud Bigtable documentation](https://cloud.google.com/bigtable/docs/overview).
```

2023-08-24 18:32 UTC, kimsauce commented on docs/integrations/google/cloud-bigtable.md
> +You can collect the logs for Sumo Logic's Google Cloud Bigtable integration by following the below steps.
```suggestion
Follow the below steps to start collecting logs for using the Sumo Logic integration for Google Cloud Bigtable.
```

2023-08-25 09:29 UTC, sumoanema commented
@kimsauce - the changes in this PR are for doc only apps. I have made the changes in the md file based on the feedback I got from @npande (who was working on AWS doc only apps and has merged the following docs : https://github.com/SumoLogic/sumologic-documentation/pull/2948) . Based on the same pattern I am doing it for GCP in this PR. Based on your feedback on the single md file here, I will add all the other md file to the same PR for other GCP doc only apps.

2023-08-25 13:55 UTC, jpipkin1 commented
Thanks for the clarification, @sumoanema. I apologize for not realizing that this article would be formatted like the ones in PR [#2948](https://github.com/SumoLogic/sumologic-documentation/pull/2948). I'll adjust my reviews for these "doc only apps".

2023-08-25 14:02 UTC, jpipkin1 commented on sidebars.ts
> +          'integrations/google/cloud-bigtable',
Move `cloud-bigtable` between `cloud-audit` and 'cloud-firewall` so that the it is in alphabetical order.

2023-08-25 14:10 UTC, jpipkin1 commented on sidebars.ts
>            'integrations/google/cloud-audit',
```suggestion
          'integrations/google/app-engine',
          'integrations/google/bigquery',
          'integrations/google/cloud-audit',
          'integrations/google/cloud-bigtable',
```

2023-08-25 14:11 UTC, jpipkin1 approved these changes
Looks good, @sumoanema! Approved.

2023-08-25 14:14 UTC, jpipkin1 commented
@sumoanema, I see that this PR has a "do-not-merge" label. Just let us know when you want us to merge it.

2023-08-25 19:36 UTC, kimsauce commented on docs/integrations/google/cloud-bigtable.md
> +description: Learn about the collection process for the Google Cloud Bigtable service.
```suggestion
description: Learn about the Sumo Logic collection process for the Google Cloud Bigtable service.
```

2023-08-29 11:43 UTC, JV0812 commented on docs/integrations/google/cloud-alloydb-for-postgresql.md
> +
```suggestion
```

2023-08-29 11:43 UTC, JV0812 commented on docs/integrations/google/cloud-alloydb-for-postgresql.md
> +You can collect the logs for Sumo Logic's Google Cloud AlloyDB for PostgreSQL integration by following the below steps.
```suggestion

You can collect the logs for Sumo Logic's Google Cloud AlloyDB for PostgreSQL integration by following the below steps.
```

2023-08-29 11:46 UTC, JV0812 commented on docs/integrations/google/cloud-alloydb-for-postgresql.md
> +* Collect **Platform Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). AlloyDB platform logs include logs related to [pgAudit]
```suggestion
* Collect **Platform Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). AlloyDB platform logs include logs related to [pgAudit](https://cloud.google.com/alloydb/docs/pgaudit/about) and instance log which includes - PostgreSQL database logs, container logs for dataplane agents, and internal dogfish logs. To enabled pgAudit logs, refer to the [GCP documentation](https://cloud.google.com/alloydb/docs/pgaudit/enable-audit). While creating the sync in GCP, as part of the **Choose logs to include in sink** section, you can use the below query:
```

2023-08-29 12:07 UTC, JV0812 commented on docs/integrations/google/cloud-alloydb-for-postgresql.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs are accessed based on the [permissions and roles](https://cloud.google.com/alloydb/docs/audit-logging#audit_log_permissions), to enable logging for Google AlloyDB refer to [Google documentation](https://cloud.google.com/alloydb/docs/audit-logging#enabling_audit_logging). For more detail, on AlloyDB operations being audited, refer to [audited operations](https://cloud.google.com/alloydb/docs/audit-logging#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 12:08 UTC, JV0812 commented on docs/integrations/google/cloud-api-gateway.md
> +You can collect the logs and metrics for Sumo Logic's Google Cloud API Gateway integration by following the below steps.
```suggestion

You can collect the logs and metrics for Sumo Logic's Google Cloud API Gateway integration by following the below steps.
```

2023-08-29 12:14 UTC, JV0812 commented on docs/integrations/google/cloud-api-gateway.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs can be accessed based on [permissions and roles](https://cloud.google.com/api-gateway/docs/audit-logging#audit_log_permissions), to enable logging for Google API Gateway refer to [Google documentation](https://cloud.google.com/api-gateway/docs/audit-logging#enabling_audit_logging). For more detail, on API Gateway operations being audited refer to [audited operations](https://cloud.google.com/api-gateway/docs/audit-logging#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 12:15 UTC, JV0812 commented on docs/integrations/google/cloud-apis.md
> +
```suggestion
```

2023-08-29 12:15 UTC, JV0812 commented on docs/integrations/google/cloud-apis.md
> +You can collect the metrics for Sumo Logic's Google Cloud API's integration by following the below steps.
```suggestion

You can collect the metrics for Sumo Logic's Google Cloud API's integration by following the below steps.
```

2023-08-29 12:17 UTC, JV0812 commented on docs/integrations/google/cloud-apis.md
> +* Collect **GCP Metrics** using the [GCP Metric](/docs/send-data/hosted-collectors/google-source/gcp-metrics-source/) source. Note that in the Services dropdown, you'll need to select **Cloud APIs**.
```suggestion
* Collect **GCP Metrics** using the [GCP Metric](/docs/send-data/hosted-collectors/google-source/gcp-metrics-source/) source. Make sure that you select **Cloud APIs** in the Services dropdown. For Google Cloud API metrics and dimensions, refer to [Google API metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-serviceruntim).
```

2023-08-29 12:19 UTC, JV0812 commented on docs/integrations/google/cloud-armor.md
> +You can collect the logs for Sumo Logic's Google Cloud Armor integration by following the below steps.
```suggestion

You can collect the logs for Sumo Logic's Google Cloud Armor integration by following the below steps.
```

2023-08-29 12:21 UTC, JV0812 commented on docs/integrations/google/cloud-armor.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs can be accessed based on the [permissions and roles](https://cloud.google.com/armor/docs/audit-logging#audit_log_permissions) required for accessing audit logs, to enable logging for Google Armor refer to [Google documentation](https://cloud.google.com/armor/docs/audit-logging#enabling_audit_logging). For more detail, on Cloud Armor operations being audited refer to [audited operations](https://cloud.google.com/armor/docs/audit-logging#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 12:22 UTC, JV0812 commented on docs/integrations/google/cloud-armor.md
> +* Collect **Platform Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Google Cloud Armor logs are part of the Cloud Load Bala
```suggestion
* Collect **Platform Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Google Cloud Armor logs are part of the Cloud Load Balancing logs. To enable these logs, follow the instruction [here](https://cloud.google.com/armor/docs/request-logging). For collecting request logs, copy the query from log explorer which you get after following [these](https://cloud.google.com/armor/docs/request-logging#view-logs) steps and while creating the sync in GCP, as part of the **Choose logs to include in sink** section, you can use the same query.
```

2023-08-29 12:23 UTC, JV0812 commented on docs/integrations/google/cloud-auto-scaler.md
> +You can collect the logs and metrics for Sumo Logic's Google Cloud Auto Scaler integration by following the below steps.
```suggestion

You can collect the logs and metrics for Sumo Logic's Google Cloud Auto Scaler integration by following the below steps.
```

2023-08-29 12:25 UTC, JV0812 commented on docs/integrations/google/cloud-auto-scaler.md
> +* Collect **Platform Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source).When you enable autoscaling, the autoscaler makes scalin
```suggestion
* Collect **Platform Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). When you enable autoscaling, the [autoscaler](https://cloud.google.com/compute/docs/autoscaler/viewing-autoscaler-logs) makes scaling decisions based on the options that you specify. Each scaling decision is logged by Cloud Logging which can be collected. While creating the sync in GCP, as part of the **Choose logs to include in sink** section, you can use the following query:
```

2023-08-29 12:26 UTC, JV0812 commented on docs/integrations/google/cloud-auto-scaler.md
> +* Collect **GCP Metrics** using the [GCP Metric](/docs/send-data/hosted-collectors/google-source/gcp-metrics-source/) source. Note that in the Services dropdown, you'll need to select **Auto Scaler**
```suggestion
* Collect **GCP Metrics** using the [GCP Metric](/docs/send-data/hosted-collectors/google-source/gcp-metrics-source/) source. Make sure that you select **Auto Scaler** from the **Services** dropdown. For Google Auto Scaler metrics and dimensions, refer to [Google Auto Scaler metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-autoscaler).
```

2023-08-29 12:27 UTC, JV0812 commented on docs/integrations/google/cloud-backup-for-gke.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs can be accessed based on the [permissions and roles](https://cloud.google.com/kubernetes-engine/docs/add-on/backup-for-gke/how-to/audit-logging#audit_log_permissions) required for accessing audit logs, to enable logging for Google Backup for GKE refer to [Google documentation](https://cloud.google.com/kubernetes-engine/docs/add-on/backup-for-gke/how-to/audit-logging). For more detail, on Backup for GKE operations being audited refer to [audited operations](https://cloud.google.com/kubernetes-engine/docs/audit-logging#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 12:28 UTC, JV0812 commented on docs/integrations/google/cloud-backup-for-gke.md
> +* Collect **Platform Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Here are the details of [platforms logs for Backup for
```suggestion
* Collect **Platform Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Here are the details of [platforms logs for Backup for GKE](https://cloud.google.com/kubernetes-engine/docs/add-on/backup-for-gke/how-to/platform-logging-backup-for-gke). While creating the sync in GCP, as part of the **Choose logs to include in sink** section, you can use the following query:
```

2023-08-29 12:28 UTC, JV0812 commented on docs/integrations/google/cloud-bigquery-bi-engine.md
> +You can collect the logs for Sumo Logic's Google Cloud Bigquery BI engine integration by following the below steps.
```suggestion

You can collect the logs for Sumo Logic's Google Cloud Bigquery BI engine integration by following the below steps.
```

2023-08-29 12:28 UTC, JV0812 commented on docs/integrations/google/cloud-bigquery-bi-engine.md
> +* Collect **Platform Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). While creating the sync in GCP, as part of the **Choose
```suggestion
* Collect **Platform Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). While creating the sync in GCP, as part of the **Choose logs to include in sink** section, you can use the following query:
```

2023-08-29 12:30 UTC, JV0812 commented on docs/integrations/google/cloud-bigtable.md
> +* Collect **Platform Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Bigtable platform logs include logs related to Bigtable
```suggestion
* Collect **Platform Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Bigtable platform logs include logs related to Bigtable instance, cluster, tables and backup. While creating the sync in GCP, as part of the **Choose logs to include in sink** section, you can use the following query:
```

2023-08-29 12:31 UTC, JV0812 commented on docs/integrations/google/cloud-bigtable.md
> +* Collect **GCP Metrics** using the [GCP Metric](/docs/send-data/hosted-collectors/google-source/gcp-metrics-source/) source. Note that in the Services dropdown, you'll need to select **Bigtable**. F
```suggestion
* Collect **GCP Metrics** using the [GCP Metric](/docs/send-data/hosted-collectors/google-source/gcp-metrics-source/) source. make sure that you select **Bigtable** from the **Services** dropdown. For Google Bigtable metrics and dimensions, refer to [Google Bigtable metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-bigtable).
```

2023-08-29 12:32 UTC, JV0812 commented on docs/integrations/google/cloud-certificate-authority-service.md
> +
```suggestion
```

2023-08-29 12:34 UTC, JV0812 commented on docs/integrations/google/cloud-certificate-authority-service.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs can be accessed based on the [permissions and roles](https://cloud.google.com/certificate-authority-service/docs/audit-logging#audit_log_permissions) required for accessing audit logs, to enable logging for Google Certificate Authority Service, refer to [Google documentation](https://cloud.google.com/certificate-authority-service/docs/audit-logging#enabling_audit_logging). For more detail on Certificate Authority Service operations being audited, refer to [audited operations](https://cloud.google.com/certificate-authority-service/docs/audit-logging#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 12:35 UTC, JV0812 commented on docs/integrations/google/cloud-certificate-manager.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs can be accessed based on the [permissions and roles](https://cloud.google.com/certificate-manager/docs/audit-logging#audit_log_permissions). To enable logging for Google Certificate Manager, refer to [Google documentation](https://cloud.google.com/certificate-manager/docs/audit-logging#enabling_audit_logging). For more detail on Certificate Manager operations being audited, refer to [audited operations](https://cloud.google.com/certificate-manager/docs/audit-logging#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 12:41 UTC, JV0812 commented on docs/integrations/google/cloud-composer.md
> +Cloud Composer is a managed Apache Airflow service that helps you create, schedule, monitor and manage workflows.  For more details, refer to the [GCP documentation](https://cloud.google.com/composer
```suggestion
Cloud Composer is a managed Apache Airflow service that helps you create, schedule, monitor and manage workflows.  For more details, refer to the [GCP documentation](https://cloud.google.com/composer/docs/how-to)
```
```suggestion
Cloud Composer is a managed Apache Airflow service that helps you create, schedule, monitor and manage workflows.  For more details, refer to the [GCP documentation](https://cloud.google.com/composer/docs/how-to)
```
```suggestion
Cloud Composer is a managed Apache Airflow service that helps you create, schedule, monitor, and manage workflows.  For more details, refer to the [GCP documentation](https://cloud.google.com/composer/docs/how-to)
```

2023-08-29 12:42 UTC, JV0812 commented on docs/integrations/google/cloud-composer.md
> +You can collect the logs and metrics for Sumo Logic's Google Cloud Composer integration by following the below steps.
```suggestion

You can collect the logs and metrics for Sumo Logic's Google Cloud Composer integration by following the below steps.
```

2023-08-29 12:44 UTC, JV0812 commented on docs/integrations/google/cloud-composer.md
> +* Collect **Platform Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Composer platform logs include streaming logs. [Here](h
```suggestion
* Collect **Platform Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Composer platform logs include [streaming logs](https://cloud.google.com/composer/docs/composer-2/view-logs#streaming). While creating the sync in GCP, as part of the **Choose logs to include in sink** section, you can use the following query:
```

2023-08-29 12:47 UTC, JV0812 commented on docs/integrations/google/cloud-dataflow.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs can be accessed based on the [permissions and roles](https://cloud.google.com/dataflow/docs/audit-logging#audit_log_permissions). To enable logging for Google Dataflow, refer to [Google documentation](https://cloud.google.com/dataflow/docs/audit-logging#enabling_audit_loggin). For more detail on Dataflow operations being audited, refer to [audited operations](https://cloud.google.com/dataflow/docs/audit-logging#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 12:48 UTC, JV0812 commented on docs/integrations/google/cloud-dataflow.md
> +* Collect **Platform Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). [Here](https://cloud.google.com/dataflow/docs/guides/lo
```suggestion
* Collect **Platform Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). [Here](https://cloud.google.com/dataflow/docs/guides/logging#log-types) are the log types collected as pipeline logs. By default, only log lines marked INFO and higher will be sent to Cloud Logging. While creating the sync in GCP, as part of the **Choose logs to include in sink** section, you can use the following query:
```

2023-08-29 12:49 UTC, JV0812 commented on docs/integrations/google/cloud-dataproc-metastore.md
> +Dataproc Metastore is a fully managed, highly available, autohealing, serverless, Apache Hive metastore (HMS) that runs on Google Cloud.  For more details, refer to the [GCP documentation](https://cl
```suggestion
Dataproc Metastore is a fully managed, highly available, autohealing, serverless, and Apache Hive metastore (HMS) that runs on Google Cloud. For more details, refer to the [GCP documentation](https://cloud.google.com/dataproc-metastore/docs/overview)
```

2023-08-29 12:49 UTC, JV0812 commented on docs/integrations/google/cloud-dataproc-metastore.md
> +You can collect the logs for Sumo Logic's Google Cloud Dataproc Metastore integration by following the below steps.
```suggestion

You can collect the logs for Sumo Logic's Google Cloud Dataproc Metastore integration by following the below steps.
```

2023-08-29 12:50 UTC, JV0812 commented on docs/integrations/google/cloud-dataproc-metastore.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs can be accessed based on the [permissions and roles](https://cloud.google.com/dataproc-metastore/docs/audit-logging#audit_log_permissions). To enable logging for Google Dataproc Metastore, refer to [Google documentation](https://cloud.google.com/dataproc-metastore/docs/audit-logging#enabling_audit_logging). For more detail on Dataproc Metastore operations being audited, refer to [audited operations](https://cloud.google.com/dataproc-metastore/docs/audit-logging#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 12:50 UTC, JV0812 commented on docs/integrations/google/cloud-dataproc-metastore.md
> +* Collect **Platform Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Platform logs include serevice logs and [Metadata feder
```suggestion
* Collect **Platform Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Platform logs include service logs and [Metadata federation](https://cloud.google.com/dataproc-metastore/docs/hms-federation). While creating the sync in GCP, as part of the **Choose logs to include in sink** section, you can use the following query:
```

2023-08-29 12:51 UTC, JV0812 commented on docs/integrations/google/cloud-dataproc.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs can be accessed based on the [permissions and roles](https://cloud.google.com/dataproc/docs/guides/audit-logging#audit_log_permissions). To enable logging for Google Dataproc, refer to [Google documentation](https://cloud.google.com/dataproc/docs/guides/audit-logging#enabling_audit_logging). For more detail on Dataproc operations being audited, refer to [audited operations](https://cloud.google.com/dataproc/docs/guides/audit-logging#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 12:54 UTC, JV0812 commented on docs/integrations/google/cloud-datastore.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs can be accessed based on the [permissions and roles](https://cloud.google.com/datastore/docs/audit-logging#audit_log_permissions) required for accessing audit logs. To enable logging for Google Datastore, refer to [Google documentation](https://cloud.google.com/datastore/docs/audit-logging#enabling_audit_logging). For more detail on Datastore operations being audited, refer to [audited operations](https://cloud.google.com/datastore/docs/audit-logging#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 12:54 UTC, JV0812 commented on docs/integrations/google/cloud-datastore.md
> +* Collect **Platform Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Datastore platform logs include logs related to datasto
```suggestion
* Collect **Platform Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Datastore platform logs include logs related to datastore database and datastore index. Query to get these logs is same to that of Audit logs for Datastore.
```

2023-08-29 12:55 UTC, JV0812 commented on docs/integrations/google/cloud-datastore.md
> +* Collect **GCP Metrics** using the [GCP Metric](/docs/send-data/hosted-collectors/google-source/gcp-metrics-source/) source. Note that in the Services dropdown, you'll need to select **Datastore**.
```suggestion
* Collect **GCP Metrics** using the [GCP Metric](/docs/send-data/hosted-collectors/google-source/gcp-metrics-source/) source. Make sure that you select **Datastore** from the **Services** dropdown. For Google Datastore metrics and dimensions, refer to [Google Datastore metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-datastore).
```

2023-08-29 13:05 UTC, JV0812 commented on docs/integrations/google/cloud-datastream.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs can be accessed based on the [permissions and roles](https://cloud.google.com/datastream/docs/audit-logging#audit_log_permissions). To enable logging for Google Datastream, refer to [Google documentation](https://cloud.google.com/datastream/docs/audit-logging#enabling_audit_logging). For more detail on Datastream operations being audited, refer to [audited operations](https://cloud.google.com/datastream/docs/audit-logging#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 13:06 UTC, JV0812 commented on docs/integrations/google/cloud-deploy.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs can be accessed based on the [permissions and roles](https://cloud.google.com/deploy/docs/audit-logs#access). To enable logging for Google Deploy, refer to [Google documentation](https://cloud.google.com/deploy/docs/audit-logs#enable). For more detail on Deploy operations being audited, refer to [audited operations](https://cloud.google.com/deploy/docs/audit-logs#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 13:07 UTC, JV0812 commented on docs/integrations/google/cloud-filestore.md
> +Filestore instances are fully managed file servers on Google Cloud that can be connected to Compute Engine VMs, GKE clusters and external datastores. For more details, refer to the [GCP documentation
```suggestion
Filestore instances are fully managed file servers on Google Cloud that can be connected to Compute Engine VMs, GKE clusters, and external datastores. For more details, refer to the [GCP documentation](https://cloud.google.com/filestore/docs/overview)
```

2023-08-29 13:08 UTC, JV0812 commented on docs/integrations/google/cloud-filestore.md
> +* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Refer to the [permissions and roles](https://cloud.google.
```suggestion
* Collect **Audit Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). These Audit Logs can be accessed based on the [permissions and roles](https://cloud.google.com/filestore/docs/audit-logging#audit_log_permissions). To enable logging for Google Filestore, refer to [Google documentation](https://cloud.google.com/filestore/docs/audit-logging#enabling_audit_logging). For more detail on Filestore operations being audited, refer to [audited operations](https://cloud.google.com/filestore/docs/audit-logging#audited_operations). While creating the sync in GCP, as part of the **Choose logs to include in sink** section you can use the following query:
```

2023-08-29 13:09 UTC, JV0812 commented on docs/integrations/google/cloud-filestore.md
> +* Collect **GCP Metrics** using the [GCP Metric](/docs/send-data/hosted-collectors/google-source/gcp-metrics-source/) source. Note that in the Services dropdown, you'll need to select **Cloud Filesto
```suggestion
* Collect **GCP Metrics** using the [GCP Metric](/docs/send-data/hosted-collectors/google-source/gcp-metrics-source/) source. Make sure that you select **Cloud Filestore** from the **Services** dropdown. For Google Filestore metrics and dimensions, refer to [Google Filestore metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-file).
```

2023-08-29 13:09 UTC, JV0812 commented on docs/integrations/google/cloud-firebase.md
> +You can collect the logs and metrics for Sumo Logic's Google Cloud Firebase integration by following the below steps.
```suggestion

You can collect the logs and metrics for Sumo Logic's Google Cloud Firebase integration by following the below steps.
```

2023-08-29 13:14 UTC, JV0812 commented on docs/integrations/google/cloud-firebase.md
> +where resource_type can be replaced with resource type of respective firebase product to fetch platform logs. And to filter audit logs, resource_type can be replaced with "audited_resource" and servi
```suggestion
Where `resource_type` can be replaced with resource type of respective firebase product to fetch platform logs. And to filter audit logs, resource_type can be replaced with "audited_resource" and service_name can be replaced with service name of respective firebase product. These queries can then be separated by an "or" condition.
```

2023-08-29 13:15 UTC, JV0812 commented on docs/integrations/google/cloud-firebase.md
> +* Collect **GCP Metrics** using the [GCP Metric](/docs/send-data/hosted-collectors/google-source/gcp-metrics-source/) source. Note that in the Services dropdown, you'll need to select **Firebase**. F
```suggestion
* Collect **GCP Metrics** using the [GCP Metric](/docs/send-data/hosted-collectors/google-source/gcp-metrics-source/) source. Make sure that you select **Firebase** from the **Services** dropdown. For Google Firebase metrics and dimensions, refer to [Google Firebase metrics](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-firebasedatabase).
```

2023-08-29 13:18 UTC, JV0812 commented on docs/integrations/google/cloud-firestore.md
> +* Collect **Platform Logs** using [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Firestore platform logs include logs related to firesto
```suggestion
* Collect **Platform Logs** using the [Google Cloud Platform source](/docs/send-data/hosted-collectors/google-source/google-cloud-platform-source). Firestore platform logs include logs related to Firestore database and Firestore index. Query to get these logs is same to that of Audit logs for Firestore.
```

2023-08-29 13:40 UTC, JV0812 approved these changes
LGTM. 
index.md page will be updated once all the GCP integration docs are added, just to avoid the rework.

2023-08-29 14:19 UTC, merged