Combine Search Audit Index articles
SumoLogic/sumologic-documentation pull request #2997
Opened 2023-08-28 22:18 UTC by jpipkin1

## Purpose of this pull request

This pull request (PR) merges the [Log Search Audit Index](https://help.sumologic.com/docs/manage/security/log-search-audit-index/) article into this article:
https://help.sumologic.com/docs/manage/security/search-audit-index/

Issue number: GitHub issue #2990

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-08-28 22:23 UTC, jpipkin1 commented
Could you give this a look, @wjakelee, since this PR provides the fix for the issue you reported (#2990)?

2023-08-28 23:13 UTC, kimsauce commented on docs/manage/security/search-audit-index.md
> +The Search Audit Index provides event logs on search usage and activities for your account. The index allows you to monitor and audit the search queries being run within your account, the types of qu
```suggestion
The Search Audit Index provides event logs on search usage and activities for your account. The index allows you to monitor and audit the search queries being run within your account, the types of queries, the users running them, and more. 

To visualize your Search Audit Index data, download the [Enterprise Search Audit App](/docs/integrations/sumo-apps/enterprise-search-audit), which provides pre-built dashboards and reports to help you analyze your current search use and identify areas for improvement.
```

2023-08-28 23:13 UTC, wjakelee approved these changes
Looks Good to me!

2023-08-28 23:13 UTC, kimsauce requested changes
one suggestion

2023-08-29 15:26 UTC, kimsauce approved these changes

2023-08-29 15:45 UTC, merged