production.yml: changed Cloudfront URL to help-opensource.sumologic.com
SumoLogic/sumologic-documentation pull request #300
Opened 2022-09-19 17:40 UTC by kimsauce

## Purpose of this pull request

production.yml URL changed from Cloudfront to help.sumologic.com

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [x] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2022-09-21 10:12 UTC, swiatekm-sumo requested changes

2022-09-21 10:12 UTC, swiatekm-sumo commented on .github/workflows/production.yml
> +        - main
Why are you making this change? Also, I think the yaml identation is messed up.

2022-09-30 18:49 UTC, kimsauce commented on .github/workflows/production.yml
> +      hostname: https://help.sumologic.com
@SumoLogic/open-source-collection-team @swiatekm-sumo @mccartney , can you confirm whether this URL should be https://help-opensource.sumologic.com or https://help.sumologic.com?

2022-10-01 23:19 UTC, kimsauce commented on .github/workflows/production.yml
> +      hostname: https://help.sumologic.com
Have some urgent changes to push to prod today -- going to use https://help-opensource.sumologic.com

2022-10-01 23:32 UTC, merged