Create doc for hasura app
SumoLogic/sumologic-documentation pull request #3000
Opened 2023-08-29 06:14 UTC by hitarth-sumo

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-08-29 06:27 UTC, JV0812 commented on docs/integrations/webhooks/hasura.md
> +Hasura Cloud is a fully-managed version of GraphQL Engine that gives you a scalable, globally-distributed, secure GraphQL API over your data sources. You can use a webhook in the Hasura platform to f
```suggestion
Hasura Cloud is a fully-managed version of GraphQL Engine that provides you a scalable, globally-distributed, and secure GraphQL API over your data sources. You can use a webhook in the Hasura platform to forward logs to the Sumo Logic HTTP endpoint. Using these logs, you can monitor the insert, update, and deletion events in Sumo Logic. For more details, refer to the [Hasura Documentation](https://hasura.io/docs/latest/hasura-cloud/overview/).
```

2023-08-29 06:28 UTC, JV0812 requested changes
Minor fix

2023-08-29 15:55 UTC, kimsauce commented on docs/integrations/webhooks/hasura.md
> +Hasura Cloud is a fully-managed version of GraphQL Engine that provides you a scalable, globally-distributed, and secure GraphQL API over your data sources. You can use a webhook in the Hasura platfo
```suggestion
Hasura Cloud is a fully managed version of GraphQL Engine that provides you with a scalable, secure, and globally distributed GraphQL API over your data sources. You can use a webhook in the Hasura platform to forward logs to the Sumo Logic HTTP endpoint. Using these logs, you can monitor the insert, update, and deletion events in Sumo Logic. For more details, refer to the [Hasura Documentation](https://hasura.io/docs/latest/hasura-cloud/overview/).
```

2023-08-31 05:55 UTC, JV0812 approved these changes
LGTM

2023-08-31 09:03 UTC, merged