Tenable app doc
SumoLogic/sumologic-documentation pull request #3068
Opened 2023-09-12 16:00 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-09-12 16:17 UTC, jpipkin1 commented on docs/integrations/saas-cloud/index.md
> +  <p>Gain comprehensive visibility and actionable insights into your organization's security posture</p>
```suggestion
  <p>Gain comprehensive visibility and actionable insights into your organization's security posture.</p>
```

2023-09-12 16:29 UTC, jpipkin1 commented on docs/integrations/saas-cloud/tenable.md
> +## Viewing Tenable dashboards​
The screenshots are broken for the dashboards "Tenable - Overview" and "Tenable - Audit Activity". When I accessed the image links directly, it gave me an "Access Denied" error. Also, the URLs for both dashboards appear to be the same. Could you make sure those image URLs are correct?

2023-09-12 16:30 UTC, jpipkin1 requested changes
@JV0812 the new article looks very good. The only issue I saw was for the dashboard images.

2023-09-12 17:59 UTC, ankitgoelcmu commented on docs/integrations/saas-cloud/tenable.md
> +## Viewing Tenable dashboards​
Overview dashboard link should be https://sumologic-app-data-v2.s3.amazonaws.com/dashboards/Tenable/Tenable-Overview.png

2023-09-13 04:44 UTC, JV0812 commented
Thanks @jpipkin1, I have updated the URL and made them public in S3. It works for me now, can you check from your end.

2023-09-13 13:49 UTC, jpipkin1 approved these changes
@JV0812, the dashboard images now work for me. Thanks for fixing them!

2023-09-13 14:50 UTC, merged