Fixed
SumoLogic/sumologic-documentation pull request #3088
Opened 2023-09-19 20:46 UTC by jpipkin1

## Purpose of this pull request

This pull request (PR) fixes an error I introduced with PR #3086 in this article:
https://help.sumologic.com/docs/manage/manage-subscription/manage-org-settings/

I needed to flip the "Cloud Flex Credits" and "Cloud Flex" instructions. The kebob menu is used for Cloud Flex Credits! 🤦 

Issue number: Original issue was #3084 

## Select the type of change:

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-09-19 20:47 UTC, jpipkin1 commented
@kimsauce, I really goofed on this one.

2023-09-19 21:50 UTC, kimsauce commented on docs/manage/manage-subscription/manage-org-settings.md
> +     * Cloud Flex Credits: From the kebob menu at the top select **Change Organization Name**.
```suggestion
     * Cloud Flex Credits: From the kebab menu at the top, select **Change Organization Name**.
```

2023-09-19 21:50 UTC, kimsauce commented on docs/manage/manage-subscription/manage-org-settings.md
> +     * Cloud Flex: At the top select **Manage Organization > Change Organization Name**.
```suggestion
     * Cloud Flex: At the top, select **Manage Organization > Change Organization Name**.
```

2023-09-19 21:51 UTC, kimsauce requested changes
done!

2023-09-19 22:09 UTC, jpipkin1 commented on docs/manage/manage-subscription/manage-org-settings.md
> +     * Cloud Flex: At the top select **Manage Organization > Change Account Owner**.
```suggestion
     * Cloud Flex Credits: From the kebab menu at the top, select **Change Account Owner**.
     * Cloud Flex: At the top, select **Manage Organization > Change Account Owner**.
```

2023-09-19 22:09 UTC, jpipkin1 commented on docs/manage/manage-subscription/manage-org-settings.md
> +     * Cloud Flex: At the top select **Manage Organization > Change Account Owner**.
```suggestion
     * Cloud Flex Credits: From the kebab menu at the top, select **Change Account Subdomain**.
     * Cloud Flex: At the top, select **Manage Organization > Change Account Owner**.
```

2023-09-19 22:10 UTC, jpipkin1 commented
Thanks, @kimsauce.

2023-09-20 14:32 UTC, jpipkin1 commented
@kimsauce, could you approve this PR?

2023-09-20 16:41 UTC, kimsauce approved these changes

2023-09-20 16:56 UTC, merged