1password doc updated
SumoLogic/sumologic-documentation pull request #3102
Opened 2023-09-22 16:14 UTC by JV0812

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-09-22 16:17 UTC, kimsauce reviewed
@JV0812 , I tried running this locally and got the following error:

```
Compiled with problems:
×
ERROR in ./docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md 104:0-77
Module not found: Error: Can't resolve 'raw-loader' in '/Users/kpohas/sumologic-documentation/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework'
ERROR in ./docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md 105:0-74
Module not found: Error: Can't resolve 'raw-loader' in '/Users/kpohas/sumologic-documentation/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework'
```

2023-09-25 04:14 UTC, JV0812 commented
Can you please install the raw loaded component, using `yarn add raw loaded`

2023-09-25 16:57 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
> +| 5 min |  [Item Usage](https://support.1password.com/events-api-reference/#item-usage)
```suggestion
| 5 min |  [Sign-in Attempts](https://developer.1password.com/docs/events-api/reference/#post-apiv1signinattempts)
| 5 min |  [Item Usage](https://developer.1password.com/docs/events-api/reference/#post-apiv1itemusages)
```

2023-09-25 16:58 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
> +| 5 min |  [Audit Events](https://developer.1password.com/docs/events-api/reference/#post-apiv1auditevents)
```suggestion
| 5 min |  [Audit events](https://developer.1password.com/docs/events-api/reference/#post-apiv1auditevents)
```

2023-09-25 16:59 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
>  The 1Password Source provides a secure endpoint to receive Sign-in Attempts, Item Usage, and Audit Events from the [1Password Event API](https://support.1password.com/events-api-reference/). It secur
```suggestion
The 1Password Source provides a secure endpoint to receive sign-in attempts, item usage, and audit events from the [1Password Event API](https://support.1password.com/events-api-reference/). It securely stores the required authentication, scheduling, and state tracking information.
```

2023-09-25 17:02 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
> +Sources can be configured using UTF-8 encoded JSON files with the Collector Management API. See [how to use JSON to configure Sources](/docs/send-data/use-json-configure-sources) for more details.
```suggestion
Sources can be configured using UTF-8 encoded JSON files with the Collector Management API. See [How to Use JSON to Configure Sources](/docs/send-data/use-json-configure-sources) for more details. 
```

2023-09-25 17:08 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/1password-source.md
>  - If you're still seeing the `401 Unauthorized error` in the **Status** column, regenerate the API Token by following [these Authentication steps](#authentication) and then updating the API Token for
```suggestion
- If you're still seeing the `401 Unauthorized error` in the **Status** column, regenerate the API Token by following [these Authentication steps](#vendor-configuration) and then updating the API Token for the source.
```

2023-09-25 17:10 UTC, jpipkin1 requested changes
I have minor suggestions, @JV0812.

2023-09-25 17:12 UTC, jpipkin1 commented
@kimsauce, are we good with this PR updating the `package.json` and `yarn.lock` files?

2023-09-25 17:37 UTC, kimsauce commented
> @kimsauce, are we good with this PR updating the `package.json` and `yarn.lock` files (resulting from running `yarn add raw-loader`)?

Just ran it locally and worked for me! Yes sounds good.

2023-09-26 04:09 UTC, JV0812 commented
Thanks for your review @jpipkin1. I have fixed your comments.

2023-09-26 14:03 UTC, jpipkin1 approved these changes

2023-09-26 14:32 UTC, merged