add automation bridge with podman version
SumoLogic/sumologic-documentation pull request #3211
Opened 2023-10-16 13:25 UTC by ffelici-sumo

## Purpose of this pull request

This pull request (PR). Adds the documentation to configure and use the automation bridge with Podman.

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-10-16 18:40 UTC, jpipkin1 commented on docs/cse/automation-service/automation-service-bridge.md
> +- Run following commands:
```suggestion
1. Run the following commands:
```

2023-10-16 18:40 UTC, jpipkin1 commented on docs/cse/automation-service/automation-service-bridge.md
> +- Create a symbolic link:
```suggestion
1. Create a symbolic link:
```

2023-10-16 18:42 UTC, jpipkin1 commented on docs/cse/automation-service/automation-service-bridge.md
> +- Change automation bridge configuration file /usr/lib/systemd/system/automation-bridge-worker@.service
```suggestion
Change the automation bridge configuration file `/usr/lib/systemd/system/automation-bridge-worker@.service`.
```

2023-10-16 18:45 UTC, jpipkin1 requested changes
@ffelici-sumo, this needs just a few minor updates.

2023-10-16 20:28 UTC, kimsauce commented on docs/cse/automation-service/automation-service-bridge.md
> +##
is this line with the ## intentional?

2023-10-16 20:28 UTC, kimsauce commented on docs/cse/automation-service/automation-service-bridge.md
> +```systemd
```suggestion
```bash title="systemd"
```

2023-10-16 20:28 UTC, kimsauce requested changes
A couple of suggestions

2023-10-17 08:58 UTC, ffelici-sumo commented on docs/cse/automation-service/automation-service-bridge.md
> +### Configuring automation bridge with Podman
They confirmed that it should be replicated on [Cloud SOAR automation bridge documentation](https://help.sumologic.com/docs/cloud-soar/cloud-soar-bridge/)

2023-10-17 09:42 UTC, ffelici-sumo commented on docs/cse/automation-service/automation-service-bridge.md
> +##
removed 👍🏻

2023-10-17 09:42 UTC, ffelici-sumo commented on docs/cse/automation-service/automation-service-bridge.md
> +### Configuring automation bridge with Podman
committed 👍🏻

2023-10-17 13:41 UTC, jpipkin1 commented on docs/cse/automation-service/automation-service-bridge.md
> +### Configuring automation bridge with Podman
Thanks for adding the documentation to Cloud SOAR, @ffelici-sumo.

2023-10-17 13:53 UTC, jpipkin1 approved these changes
PR approved, @ffelici-sumo. Note I made some minor updates with commit "[Small layout adjustments](https://github.com/SumoLogic/sumologic-documentation/pull/3211/commits/a09a6fbb8c886478714c09173a545d443ee0bc82)".

2023-10-17 22:15 UTC, jpipkin1 commented
@kimsauce, before you approve this PR and we merge it, do you want to do any checks on it to ensure it won't cause problems with our search?

2023-10-17 23:41 UTC, kimsauce commented
> @kimsauce, before you approve this PR and we merge it, do you want to do any checks on it to ensure it won't cause problems with our search?

Good call. I'll do it now.

2023-10-17 23:47 UTC, kimsauce approved these changes

2023-10-17 23:47 UTC, kimsauce commented
@jpipkin1 just did a fresh `yarn install` and test on my end. merging now.

2023-10-18 00:20 UTC, merged