Split V2 App
SumoLogic/sumologic-documentation pull request #3239
Opened 2023-10-20 11:28 UTC by shivani-sumo

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [ ] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-10-20 14:22 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +The Split App for Sumo Logic enables you to seamlessly monitor feature flagging, experiment results, and user behavior, enabling data-driven decision-making and fostering a more agile and competitive
```suggestion
The Split app for Sumo Logic enables you to seamlessly monitor feature flagging, experiment results, and user behaviour, enabling data-driven decision-making and fostering a more agile and competitive development process. This app is based on Split Webhook, which provides seamless integration between Split and Sumo Logic.
```

2023-10-20 14:23 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +The Sumo Logic App for Split ingests Split events into Sumo Logic through an outgoing webhook available in Split. The following event types are ingested through the Split webhook:
```suggestion
The Sumo Logic app for Split ingests Split events into Sumo Logic through an outgoing webhook available in the Split. The following event types are ingested through the Split webhook:
```

2023-10-20 14:23 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +## Log Types
```suggestion
## Log types
```

2023-10-20 14:23 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +### Sample Log Message
```suggestion
### Sample log message
```

2023-10-20 14:24 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +### Sample Query
```suggestion
### Sample query
```

2023-10-20 14:24 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +### Installing the App
```suggestion
### Installing the Split app
```

2023-10-20 14:25 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +## Split Dashboards
```suggestion
## Viewing Split dashboards
```

2023-10-20 14:26 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +**Split - Overview** dashboard offers transparency into actions performed by both administrators and team members, delivering valuable insights into audit events, their distribution, and statistics c
```suggestion
The **Split - Overview** dashboard offers transparency into actions performed by both administrators and team members, delivering valuable insights into audit events, their distribution, and statistics categorized by their respective types.
```

2023-10-20 14:27 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +static/img/integrations/webhooks/Split-Overview.png
```suggestion
```

2023-10-20 14:27 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +<img src={useBaseUrl('img/integrations/webhooks/Split-Overview.png')} alt="Split-Overview" />
```suggestion
<img src={useBaseUrl('img/integrations/webhooks/Split-Overview.png')} style={{border: '1px solid black'}} alt="Split-Overview" />
```

2023-10-20 14:27 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +**Split - Users and Groups** dashboard offers concise statistical summaries pertaining to Split users and groups, including administrative actions taken concerning them.
```suggestion
The **Split - Users and Groups** dashboard offers concise statistical summaries pertaining to Split users and groups, including administrative actions taken concerning them.
```

2023-10-20 14:27 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +<img src={useBaseUrl('img/integrations/webhooks/Split-Users_and_Groups.png')} alt="Split-Users_and_Groups" />
```suggestion
<img src={useBaseUrl('img/integrations/webhooks/Split-Users_and_Groups.png')} style={{border: '1px solid black'}} alt="Split-Users_and_Groups" />
```

2023-10-20 14:38 UTC, JV0812 requested changes
Great work @shivani-sumo. I have some minor comments. Also, can you please crop the images and remove the extra space.

2023-10-20 17:50 UTC, kimsauce commented on docs/integrations/webhooks/split.md
> +The Split App for Sumo Logic enables you to seamlessly monitor feature flagging, experiment results, and user behavior, enabling data-driven decision-making and fostering a more agile and competitive
```suggestion
The Split App for Sumo Logic enables you to seamlessly monitor feature flagging, experiment results, and user behavior, enabling data-driven decision making and fostering a more agile and competitive development process. This app is based on Split Webhook, which provides seamless integration between Split and Sumo Logic.
```

2023-10-25 07:06 UTC, JV0812 approved these changes
LGTM

2023-10-26 05:38 UTC, JV0812 commented on docs/integrations/webhooks/postman.md
> +This section has instructions for installing the Sumo Logic app for Postman.
```suggestion
```

2023-10-26 05:38 UTC, JV0812 commented on docs/integrations/webhooks/sentry.md
> +This section has instructions for installing the Sumo Logic app for Sentry.
```suggestion
```

2023-10-26 05:39 UTC, JV0812 commented on docs/integrations/webhooks/split.md
> +This section has instructions for installing the Sumo Logic app for Split.
```suggestion
```

2023-10-26 05:39 UTC, JV0812 commented on docs/integrations/webhooks/squadcast.md
> +This section has instructions for installing the Sumo Logic app for Squadcast.
```suggestion
```

2023-10-26 05:39 UTC, JV0812 commented on docs/integrations/webhooks/stripe.md
> +This section has instructions for installing the Sumo Logic app for Stripe.
```suggestion
```

2023-12-22 12:29 UTC, JV0812 commented
The intent of this PR is covered in the PR https://github.com/SumoLogic/sumologic-documentation/pull/3437.

2023-12-22 12:29 UTC, closed without merging