On-premises SOAR end-of-life release note
SumoLogic/sumologic-documentation pull request #3272
Opened 2023-10-31 20:34 UTC by jpipkin1

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [x] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request adds a release note announcing end-of-life for the SOAR on-premises solution here:
https://help.sumologic.com/release-notes-csoar/

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2023-10-31 20:36 UTC, jpipkin1 commented
@stacykor, this PR is in draft until I get your feedback.

2023-10-31 22:00 UTC, jpipkin1 commented
This PR is now ready for review.

2023-10-31 22:13 UTC, kimsauce commented on blog-csoar/2023-11-01-23-application-update.md
> +On **December 1, 2024**, Sumo Logic’s on-premises SOAR solution reaches its end-of-life and is obsolete. Beginning on that date, it no longer receives applicable support entitled by active support co
```suggestion
Effective **December 1, 2024**, Sumo Logic’s on-premises SOAR solution reaches end-of-life and becomes obsolete. Beginning on that date, it no longer receives applicable support entitled by active support contracts or by applicable warranty terms and conditions. 
```

2023-10-31 22:13 UTC, kimsauce commented on blog-csoar/2023-11-01-23-application-update.md
> +To continue to utilize Sumo Logic’s SOAR capabilities, use our SAAS product, [Cloud SOAR](/docs/cloud-soar/).
```suggestion
To continue to utilize Sumo Logic’s SOAR capabilities, use our SaaS product, [Cloud SOAR](/docs/cloud-soar/). 
```

2023-10-31 22:13 UTC, kimsauce requested changes
couple suggestions!

2023-11-01 14:50 UTC, jpipkin1 commented
Good suggestions, @kimsauce!

2023-11-01 18:22 UTC, jpipkin1 commented
@kimsauce, could you approve this PR?

2023-11-01 19:39 UTC, kimsauce approved these changes

2023-11-01 19:52 UTC, jpipkin1 commented
Thanks, @kimsauce!

2023-11-01 19:58 UTC, merged