Fzampori csoar changelog
SumoLogic/sumologic-documentation pull request #3319
Opened 2023-11-16 16:24 UTC by fzampori

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [ ] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2023-11-16 22:20 UTC, kimsauce commented on blog-csoar/2023-11-15-application-update.md
> +tags: [cloud soar release notes,automation service , application update]
```suggestion
tags: [cloud soar release notes, automation service, application update]
```

2023-11-16 22:21 UTC, kimsauce commented on blog-csoar/2023-11-15-application-update.md
> +* Fixed ApiV3 change incident owner when using incorrect owner ID or with a Group ID.
```suggestion
* Fixed API v3 change incident owner when using incorrect owner ID or with a Group ID.
```

2023-11-16 22:21 UTC, kimsauce commented on blog-csoar/2023-11-15-application-update.md
> +title: November 15, 2023 - Application Update
Should this be 11/16?

2023-11-16 22:21 UTC, kimsauce requested changes
Question and suggestions

2023-11-17 08:00 UTC, fzampori commented on blog-csoar/2023-11-15-application-update.md
> +title: November 15, 2023 - Application Update
yes, I'm updating filename too

2023-11-17 15:10 UTC, jpipkin1 approved these changes
It looks good, @fzampori. Approved.

2023-11-17 16:19 UTC, kimsauce approved these changes

2023-11-17 16:30 UTC, merged