New Partner Apps Release notes
SumoLogic/sumologic-documentation pull request #3322
Opened 2023-11-17 08:47 UTC by JV0812

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [ ] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2023-11-17 16:27 UTC, kimsauce commented on blog-service/2023-11-18-partner-apps.md
> +- [Jamf Protect](https://github.com/SumoLogic/sumologic-public-partner-apps/tree/master/JamfProtect) app empowers security teams with in-depth visibility into Mac security events, providing integrate
```suggestion
- [Dataminr Pulse for Sumo Logic](https://github.com/SumoLogic/sumologic-public-partner-apps/tree/master/DataminrPulse) enables rapid identification and mitigation of emerging threats so you can deliver more time to detection and response.
- [Jamf Protect for Sumo Logic](https://github.com/SumoLogic/sumologic-public-partner-apps/tree/master/JamfProtect) empowers security teams with in-depth visibility into Mac security events, providing integrated visualization for enriched investigation into macOS threat alerting with tuned endpoint telemetry data streams. This app supports data streams from the macOS security and Jamf security cloud portals, resulting in one single collection point for all endpoint and network-based events that occur across your Apple device fleet. With the Jamf Protect app, Sumo Logic users can easily integrate their Apple security data, gain valuable insights into Apple's security posture, and quickly respond to security incidents.
```

2023-11-17 16:27 UTC, kimsauce requested changes
suggestion

2023-11-20 06:18 UTC, himanshu219 approved these changes

2023-11-20 17:19 UTC, kimsauce approved these changes

2023-11-21 06:29 UTC, merged