Update service.md
SumoLogic/sumologic-documentation pull request #333
Opened 2022-09-23 22:28 UTC by stacykor

missing update to Sept 22.

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2022-09-23 23:10 UTC, kimsauce commented on docs/releasenotes/service.md
> +Update - Good news! We've increased the number of Cloud-to-Cloud Sources that customers with paid Sumo Logic subscriptions can have, from 20 to 50. For users of free accounts, the limit remains 20 Cl
@stacykor  fix broken link

2022-09-23 23:10 UTC, kimsauce requested changes
Minor change

2022-09-23 23:11 UTC, kimsauce commented
@stacykor , @MariePMcGarry is assigned is migrate over August and Sept: https://app.asana.com/0/1183741177809740/1203018922431321.

2022-09-24 01:30 UTC, stacykor commented
> @stacykor , @MariePMcGarry is assigned is migrate over August and Sept: https://app.asana.com/0/1183741177809740/120301892243132

@MariePMcGarry is welcome to make any additional changes. I'm sure we'll release a few more things before 9/30.

2022-09-24 19:14 UTC, kimsauce commented on docs/releasenotes/service.md
> +Update - Good news! We've increased the number of Cloud-to-Cloud Sources that customers with paid Sumo Logic subscriptions can have, from 20 to 50. For users of free accounts, the limit remains 20 Cl
Pls fix broken link. Need to close the gap between text and URL:

```suggestion
Update - Good news! We've increased the number of Cloud-to-Cloud Sources that customers with paid Sumo Logic subscriptions can have, from 20 to 50. For users of free accounts, the limit remains 20 Cloud-to-Cloud Sources. For more information, see [Cloud-to-Cloud Integration Framework](/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework).
```

2022-09-24 19:14 UTC, kimsauce requested changes
To fix the broken link, need to close the gap between the text and URL

2022-09-26 17:46 UTC, kimsauce approved these changes

2022-09-26 23:52 UTC, kimsauce commented on docs/releasenotes/service.md
> +Update - Good news! We've increased the number of Cloud-to-Cloud Sources that customers with paid Sumo Logic subscriptions can have, from 20 to 50. For users of free accounts, the limit remains 20 Cl
Hi @stacykor , to merge this PR, you'll also need to click the "Resolve Conversation" button.

2022-09-29 16:18 UTC, merged