app doc update for 7 v2 apps - release 2
SumoLogic/sumologic-documentation pull request #3372
Opened 2023-12-06 11:26 UTC by shivani-sumo

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [ ] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2023-12-06 11:45 UTC, JV0812 commented on docs/integrations/saas-cloud/asana.md
>  This section describes how to install the Asana app for Sumo Logic and description of the dashboard. You'll also need to configure the [Asana Cloud-to-Cloud Source](/docs/send-data/hosted-collectors/
```suggestion
```

2023-12-06 11:50 UTC, JV0812 commented on docs/integrations/security-threat-detection/netskope.md
>  ## Viewing Netskope Dashboards
```suggestion
## Viewing Netskope dashboards
```

2023-12-06 11:50 UTC, JV0812 commented on docs/integrations/security-threat-detection/netskope.md
>  * **Application Usage:** Insights into application usage; specifically by devices, users, users and traffic patterns.
```suggestion
* **Application Usage**. Insights into application usage; specifically by devices, users, users and traffic patterns.
```

2023-12-06 11:50 UTC, JV0812 commented on docs/integrations/security-threat-detection/netskope.md
>  * **Security Alerts:** Visibility into Netskope security alerts and violations and the ability to identify effects of a breach.
```suggestion
* **Security Alerts**. Visibility into Netskope security alerts and violations and the ability to identify effects of a breach.  
```

2023-12-08 23:12 UTC, kimsauce commented on docs/integrations/saas-cloud/asana.md
>  ## Viewing Asana dashboard
Although there's only one Asana dashboard, I'd still make this plural (_dashboards_) for consistency with its counterpart docs. We may add more in the future.

```suggestion
## Viewing Asana dashboards
```

2023-12-08 23:13 UTC, kimsauce requested changes
1 change

2023-12-20 07:52 UTC, kimsauce approved these changes

2023-12-20 07:52 UTC, JV0812 approved these changes
LGTM

2023-12-21 12:51 UTC, JV0812 commented
The intent of this PR is covered in the PR https://github.com/SumoLogic/sumologic-documentation/pull/3433.

2023-12-21 12:51 UTC, closed without merging