cloudquery-source doc added
SumoLogic/sumologic-documentation pull request #3400
Opened 2023-12-14 14:50 UTC by JV0812

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [ ] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2023-12-14 14:55 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-source.md
> +1. **Sevices**. Enter the type of service from which the data needs to be collected.
```suggestion
1. **Services**. Enter the type of service from which the data needs to be collected.
```

2023-12-14 15:00 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-source.md
> +| 24 hours |  [Data service table data](https://developer.code42.com/api) |
This link goes to Code42. Shouldn't it go to CloudQuery?

2023-12-14 15:05 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-source.md
> +1. **AWS Secret Access Key**. Enter the Secret Access Key collected from the [AWS Management Console](#vendor-configuration).
The links on for "AWS Management Console" are broken because there is no "Vendor Configuration" section in the article.

2023-12-14 15:05 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/cloudquery-source.md
> +Sources can be configured using UTF-8 encoded JSON files with the Collector Management API. See [JSON to configure Sources](/docs/send-data/use-json-configure-sources) for details. 
```suggestion
Sources can be configured using UTF-8 encoded JSON files with the Collector Management API. See [Use JSON to configure Sources](/docs/send-data/use-json-configure-sources) for details. 
```

2023-12-14 15:09 UTC, jpipkin1 requested changes
Looks pretty good, @JV0812. I found only a few things.

2023-12-14 15:12 UTC, jpipkin1 commented
@JV0812, you should probably also add CloudQuery here:
http://localhost:3000/docs/integrations/product-list/#c

2023-12-14 15:28 UTC, jpipkin1 commented
@JV0812, I just realized this was a draft! Sorry I put in review comments when you weren't done working on it.

2023-12-18 04:50 UTC, JV0812 commented
Its okay @jpipkin1. Thanks for your quick review and feedback. I will incorporate the points you have mentioned and will submit the PR for review.

2024-03-22 05:16 UTC, merged

2024-08-14 22:53 UTC, jpipkin1 commented
@JV0812, we’re removing the CloudQuery Source beta article with PR [#4209](https://github.com/SumoLogic/sumologic-documentation/pull/4209) at the request of @Arpit Jaiswal (see [Slack](https://sumologic.slack.com/archives/C063N5N2C5U/p1723674224220399)).