Deprecate classic dashboard docs
SumoLogic/sumologic-documentation pull request #3438
Opened 2023-12-26 06:13 UTC by JV0812

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [ ] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2023-12-26 17:46 UTC, jpipkin1 commented
@JV0812, I converted this PR to a draft since the build-and-deploy check is failing. Put the PR back into review once you've got it fixed and it's ready for us to look at.

2024-01-02 17:53 UTC, jpipkin1 commented
@JV0812, you write in the PR description "This PR is to create the redirect URLs and delete the classic dashboard docs." But this PR doesn't delete the classic dashboard docs. It only removes articles from the sidebar. If you also intend for this PR to delete the classic dashboard articles, you'll have to remove all the files under https://github.com/SumoLogic/sumologic-documentation/tree/main/docs/dashboards-classic (and provide redirects for them).

2024-01-05 09:44 UTC, JV0812 commented
Thanks @jpipkin1, I have deleted the classic dashboards now, so the statement can remain the same in the PR descroption..

2024-01-05 15:53 UTC, jpipkin1 commented on docs/manage/users-roles/roles/role-capabilities.md
> +| Manage Share Dashboards Outside of Organization	| Share a dashboard with users who don't have access to Sumo Logic.|
```suggestion
| Manage Share Dashboards Outside of Organization	| [Share a dashboard](/docs/dashboards/share-dashboard-outside-org/) with users who don't have access to Sumo Logic.|
```

2024-01-05 15:58 UTC, jpipkin1 approved these changes
Wow, @JV0812! You did a wonderful job! I only found a couple of minor things. 

In addition to my suggested change above, you'll also have to update a reference to "classic dashbards" in this article:
https://help.sumologic.com/docs/search/get-started-with-search/build-search/dynamic-parsing/#use-dynamic-parsing

2024-01-05 21:47 UTC, kimsauce commented on blog-service/2017/12-31.md
> +**Share Dashboards Outside of Your Organization**. You can share your live dashboards in view-only mode with no sign-in required, with an option to restrict access to viewers connecting from IPs / CI
```suggestion
**Share Dashboards Outside of Your Organization**. You can share your live dashboards in view-only mode with no sign-in required, with an option to restrict access to viewers connecting from IPs / CIDRs specified in your service allowlist. This feature must be enabled by an administrator on the **Manage > Security > Sumo Logic Policies** page. 
```

2024-01-05 21:49 UTC, kimsauce commented on docs/contributing/glossary.md
> +**[Data Panel](/docs/dashboards/panels)**. Panels are placed on Dashboards and provide a graphical representation of your organization's data. Data Panels are created by running search queries. From
```suggestion
**[Data Panel](/docs/dashboards/panels)**. Panels are placed on Dashboards and provide a graphical representation of your organization's data. Data Panels are created by running search queries. From the resulting data in the Search page's Aggregates tab, you can display that data using different types of charts. Once Panels are created, they are saved to a Dashboard. See also, Text Panels.
```

2024-01-05 21:49 UTC, kimsauce commented on docs/contributing/glossary.md
> +**[Text Panels](/docs/dashboards/panels/#text-panel)**. Used in Dashboards, you can add Text Panels to include titles or text descriptions. See also Markdown.
```suggestion
**[Text Panel](/docs/dashboards/panels/#text-panel)**. Used in Dashboards, you can add Text Panels to include titles or text descriptions. See also Markdown.
```

2024-01-05 21:52 UTC, kimsauce commented on docs/manage/users-roles/roles/role-capabilities.md
> +| Share Washboards With The Allowlist	| [Share dashboards](/docs/dashboards/share-dashboard-new/) in view-only mode with no login required. Viewers must be connecting from IP addresses specified in y
```suggestion
| Share Dashboards with the world	| [Share dashboards](/docs/dashboards/share-dashboard-outside-org) in view-only mode with no login required. Anyone with the URL can view the dashboard without logging in.|
| Share Dashboards with your allowlist	| [Share dashboards](/docs/dashboards/share-dashboard-new/) in view-only mode with no login required. Viewers must be connecting from IP addresses specified in your [service allowlist](/docs/manage/security/create-allowlist-ip-cidr-addresses).|
```

2024-01-05 21:52 UTC, kimsauce requested changes
couple minor things!

2024-01-09 07:57 UTC, merged