Doc update for V1-v2 apps
SumoLogic/sumologic-documentation pull request #3441
Opened 2023-12-26 13:30 UTC by shivani-sumo

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [ ] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2023-12-26 16:45 UTC, jpipkin1 commented on docs/integrations/saas-cloud/slack.md
> +{@import ../../reuse/filter-dashboards.md}
```suggestion
{@import ../../reuse/app-install-v2.md}
```

2023-12-26 16:56 UTC, jpipkin1 approved these changes
@shivani-sumo, the build-and-deploy check on this PR failed, so I applied updates so the build would complete (see my commits).  Before you submit PRs in the future, [run the branches locally using yarn](https://github.com/SumoLogic/sumologic-documentation#building-locally) to ensure they build correctly.

2023-12-26 17:00 UTC, jpipkin1 commented on docs/integrations/saas-cloud/slack.md
> +{@import ../../reuse/app-install-v2.md}
```suggestion
{@import ../../reuse/apps/app-install-v2.md}
```

2023-12-26 17:04 UTC, kimsauce requested changes
One change

2023-12-26 17:04 UTC, kimsauce commented on docs/integrations/saml/onelogin.md
> +## Log Types and sample log message
For consistency with the rest of the apps docs, Log types and Sample log messages should be separate sections.

2023-12-28 13:13 UTC, JV0812 commented
The intent of this PR is covered in the PRs #3432, #3433, and #3434.

2023-12-28 13:13 UTC, closed without merging