Add triggers documentation
SumoLogic/sumologic-documentation pull request #3448
Opened 2023-12-28 22:32 UTC by jpipkin1

## Purpose of this pull request

This pull request adds the following section:
https://help.sumologic.com/docs/cloud-soar/cloud-soar-integration-framework/#trigger-action-definitions

Issue: [CSOAR-903](https://sumologic.atlassian.net/browse/CSOAR-903)

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [X] Yes, I've run `yarn install`
- [ ] No, does not apply to me

2023-12-28 22:50 UTC, kimsauce requested changes
Minor stuff!

2023-12-28 22:50 UTC, kimsauce commented on docs/cloud-soar/cloud-soar-integration-framework.md
> +Depending on the logic that you want to implement in your triggers, specify a list of one or more [hooks](#trigger-hooks) in the trigger YAML file. Each hook represents a manual event or API endpoint
```suggestion
Depending on the logic that you want to implement in your triggers, specify a list of one or more [hooks](#trigger-hooks) in the trigger YAML file. Each hook represents a manual event or API endpoint that can invoke the trigger. For example, by specifying the hook `updateIncident` inside a trigger, the trigger will fire whenever the field of any incident is updated either manually from the UI or via the API.
```

2023-12-28 22:50 UTC, kimsauce commented on docs/cloud-soar/cloud-soar-integration-framework.md
> +Triggers function as individual actions, executed in the backend, without the capability to review
Can you join this with line 530?

2023-12-28 22:50 UTC, kimsauce commented on docs/cloud-soar/cloud-soar-integration-framework.md
> +For example, if we want to display our custom action trigger button only when our custom field w ith
```suggestion
For example, if we want to display our custom action trigger button only when our custom field with
```

2023-12-28 22:50 UTC, kimsauce commented on docs/cloud-soar/cloud-soar-integration-framework.md
> +field ID `opt_15` is populated, inside the YAML file you can set:
Can you join this with line 719?

2023-12-28 22:50 UTC, kimsauce commented on docs/cloud-soar/cloud-soar-integration-framework.md
> +Triggers with the hook `webhook` specified can interact with the payload that is posted on your
Pls join with next line

2023-12-29 15:39 UTC, jpipkin1 commented on docs/cloud-soar/cloud-soar-integration-framework.md
> +the execution output in the GUI except for triggers on entities (observables). If a trigger fails, error logs printed on the `stderr` output of the trigger are exported in the audit trail (system log
```suggestion
Triggers function as individual actions, executed in the backend, without the capability to review the execution output in the GUI except for triggers on entities (observables). If a trigger fails, error logs printed on the `stderr` output of the trigger are exported in the audit trail (system log verbosity must be set to `ALL` to review trigger audit logs). Triggers cannot receive manual input, except for [triggers with the `incidentCustomActions` and `taskCustomActions`hooks](#trigger-incidentcustomaction-and-taskcustomaction) that accept a text input.
```

2023-12-29 15:40 UTC, jpipkin1 commented on docs/cloud-soar/cloud-soar-integration-framework.md
> +field ID `opt_15` is populated, inside the YAML file you can set:
```suggestion
For example, if we want to display our custom action trigger button only when our custom field with field ID `opt_15` is populated, inside the YAML file you can set:
```

2023-12-29 15:41 UTC, jpipkin1 commented on docs/cloud-soar/cloud-soar-integration-framework.md
> +webhook endpoint:
```suggestion
Triggers with the hook `webhook` specified can interact with the payload that is posted on your webhook endpoint:
```

2023-12-29 15:42 UTC, jpipkin1 commented
Thanks for the review, @kimsauce! Those odd line breaks occurred because I copied and pasted from a PDF. Thanks for catching them.

2023-12-29 17:20 UTC, kimsauce approved these changes

2023-12-29 18:24 UTC, merged