Release note for New view for child org usages
SumoLogic/sumologic-documentation pull request #3488
Opened 2024-01-10 10:12 UTC by JV0812

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [ ] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2024-01-10 19:49 UTC, kimsauce commented on blog-service/2024-01-11-manage.md
> +  - release notes
```suggestion
  - organizations
```

2024-01-10 19:50 UTC, kimsauce requested changes
one suggestion

2024-01-11 15:37 UTC, jpipkin1 approved these changes
Looks good, @JV0812.

2024-01-11 17:40 UTC, kimsauce approved these changes

2024-01-11 23:03 UTC, merged