AWSO docs update
SumoLogic/sumologic-documentation pull request #3508
Opened 2024-01-15 14:38 UTC by JV0812

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [x] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2024-01-16 23:23 UTC, kimsauce commented on docs/observability/aws/integrations/amazon-elasticache.md
> +```sql title="CloudTrail Log based"
```suggestion
```sql title="CloudTrail log-based"
```

2024-01-16 23:23 UTC, kimsauce commented on docs/observability/aws/integrations/amazon-sns.md
> +```sql title="Metric based - Messages Published"
```suggestion
```sql title="Metric-based - Messages Published"
```

2024-01-16 23:23 UTC, kimsauce commented on docs/observability/aws/integrations/amazon-sqs.md
> +```sql title="Messages Received (Metric based)"
```suggestion
```sql title="Messages Received (Metric-based)"
```

2024-01-16 23:24 UTC, kimsauce commented on docs/observability/aws/integrations/amazon-sqs.md
> +```sql title="Top 10 users (CloudTrail Log based)"
```suggestion
```sql title="Top 10 users (CloudTrail log-based)"
```

2024-01-16 23:24 UTC, kimsauce commented on docs/observability/aws/integrations/aws-api-gateway.md
> +```sql title="CloudTrail Log based"
```suggestion
```sql title="CloudTrail log-based"
```

2024-01-16 23:25 UTC, kimsauce commented on docs/observability/aws/integrations/aws-api-gateway.md
> +We highly recommend you view these dashboards in the [Explore View](../deploy-use-aws-observability/view-dashboards.md) of the AWS Observability solution.
```suggestion
We highly recommend you view these dashboards in the AWS Observability solution > [Explore View](../deploy-use-aws-observability/view-dashboards.md).
```

2024-01-16 23:25 UTC, kimsauce commented on docs/observability/aws/integrations/aws-api-gateway.md
> +We highly recommend you view these dashboards in the [Explore View](../deploy-use-aws-observability/view-dashboards.md) of the AWS Observability solution.
```suggestion
We highly recommend you view these dashboards in the [Explore View](../deploy-use-aws-observability/view-dashboards.md) of our AWS Observability solution.
```

2024-01-16 23:26 UTC, kimsauce commented on docs/observability/aws/integrations/aws-classic-load-balancer.md
> +* The logs are stored in a `.gzip` format in the specified S3 bucket and contain these fields in this order: timestamp, elb client:port, backend:port, request_processing_time, backend_processing_time
```suggestion
* The logs are stored in a `.gzip` format in the specified S3 bucket and contain these fields in this order: timestamp, elb client:port, backend:port, request_processing_time, backend_processing_time, response_processing_time, elb_status_code, backend_status_code, received_bytes, sent_bytes, request, user_agent, ssl_cipher, ssl_protocol. For more details on the Classic Load Balancer Access log, see [Classic Load Balancer Access Logs](https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/access-log-collection.html).
```

2024-01-16 23:26 UTC, kimsauce commented on docs/observability/aws/integrations/aws-classic-load-balancer.md
> +We highly recommend you view these dashboards in the [Explore View](../deploy-use-aws-observability/view-dashboards.md) of the AWS Observability solution.
```suggestion
We highly recommend you view these dashboards in the [Explore View](../deploy-use-aws-observability/view-dashboards.md) of our AWS Observability solution.
```

2024-01-16 23:26 UTC, kimsauce commented on docs/observability/aws/integrations/aws-dynamodb.md
> +latency and help you plan the capacity of DynamoDB instances in your environment.
```suggestion
The Sumo Logic app for AWS Observability DynamoDB is a unified logs and metrics (ULM) app that provides operational insights into DynamoDB instances across your infrastructure. Preconfigured app dashboards allow you to monitor key metrics, view the throttle events, errors, latency and help you plan the capacity of DynamoDB instances in your environment.
```

2024-01-16 23:27 UTC, jpipkin1 commented
FYI, I made an update to the app-install.md file in this PR with the "[Fix indenting of note in app-install.md](https://github.com/SumoLogic/sumologic-documentation/pull/3508/commits/e810f316acdc8bde6773a2b93505177977a83299)" commit.

2024-01-16 23:27 UTC, kimsauce commented on docs/observability/aws/integrations/aws-dynamodb.md
> +We highly recommend you view these dashboards in the [Explore View](../deploy-use-aws-observability/view-dashboards.md) of the AWS Observability solution.
```suggestion
We highly recommend you view these dashboards in the [Explore View](../deploy-use-aws-observability/view-dashboards.md) of our AWS Observability solution.
```

2024-01-16 23:28 UTC, kimsauce commented on docs/observability/aws/integrations/aws-network-load-balancer.md
> +The **AWS Network Load Balancer - Reset (RST) Packets** dashboard provides detailed insights into the number reset (RST) packets received by the network load balancer. The dashboard shows the informa
```suggestion
The **AWS Network Load Balancer - Reset (RST) Packets** dashboard provides detailed insights into the number reset (RST) packets received by the network load balancer. The dashboard shows the information for the total number of reset (RST) packets sent from a client to a target, the total number of reset (RST) packets generated by the load balancer, and the total number of reset (RST) packets sent from a target to a client.
```

2024-01-16 23:29 UTC, kimsauce requested changes
formatting stuff

2024-01-18 18:49 UTC, kimsauce approved these changes

2024-01-19 05:13 UTC, merged