AWS RDS - adding postgresql dashboard and collection instruction
SumoLogic/sumologic-documentation pull request #3556
Opened 2024-01-23 07:20 UTC by sumoanema

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [ ] Yes, I've run `yarn install`
- [X] No, does not apply to me

## Purpose of this pull request

This pull request is to add information around the newly added dashboard to the existing AWS RDS app. These dashboard are developed around postgresql in AWS RDS.

JIRA: 
https://sumologic.atlassian.net/browse/SUMO-234809

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [X] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2024-01-23 08:29 UTC, JV0812 approved these changes
LGTM

2024-01-23 21:01 UTC, kimsauce commented on docs/integrations/amazon-aws/rds.md
> +```json title ="Authentication Failure (Postgresql Log)"
```suggestion
```json title ="Authentication Failure (PostgreSQL Log)"
```

2024-01-23 21:02 UTC, kimsauce commented on docs/integrations/amazon-aws/rds.md
> +```json title ="Slow Queries (Postgresql Log)"
```suggestion
```json title ="Slow Queries (PostgreSQL Log)"
```

2024-01-23 21:02 UTC, kimsauce commented on docs/integrations/amazon-aws/rds.md
> +Use this dashboard to :
```suggestion
Use this dashboard to: 
```

2024-01-23 21:02 UTC, kimsauce commented on docs/integrations/amazon-aws/rds.md
> +Use this dashboard to :
```suggestion
Use this dashboard to: 
```

2024-01-23 21:02 UTC, kimsauce commented on docs/integrations/amazon-aws/rds.md
> +Use this dashboard to :
```suggestion
Use this dashboard to: 
```

2024-01-23 21:03 UTC, kimsauce commented on docs/integrations/amazon-aws/rds.md
> +Use this dashboard to :
```suggestion
Use this dashboard to: 
```

2024-01-23 21:03 UTC, kimsauce requested changes
formatting

2024-01-24 11:49 UTC, kimsauce approved these changes

2024-01-25 22:58 UTC, merged