Update year2018.md
SumoLogic/sumologic-documentation pull request #356
Opened 2022-09-27 01:52 UTC by nmohantyctr

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ x] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2022-09-27 02:34 UTC, kimsauce commented on docs/releasenotes/archive/service/year2018.md
> +Comparison value must be "exact"
```suggestion
SAML authentication request's RequestedAuthenticationContext's Comparison value must be "exact"
```

2022-09-27 02:36 UTC, kimsauce commented on docs/releasenotes/archive/service/year2018.md
> +NoteDeprecated - The Sumo Logic App for Kubernetes was deprecated September 6, 2019, and replaced with the current Kubernetes App.
Add line break here and format the "Note" as an admonition

2022-09-27 02:37 UTC, kimsauce commented on docs/releasenotes/archive/service/year2018.md
> +Bug Fix - Some dashboards were not responding after selecting Open in a New Browser Tab. This has been fixed.
needs line break

2022-09-27 02:37 UTC, kimsauce requested changes
a few minor fixes

2022-09-27 18:37 UTC, kimsauce commented
Hi @nmohantyctr  , per our convo this morning, I would close out this PR, since you're working on the correctly formatted version in Atom and pushing that as a PR.

2022-09-29 17:20 UTC, nmohantyctr commented
Updating file locally.

2022-09-29 17:20 UTC, closed without merging