Updates the New visualization info
SumoLogic/sumologic-documentation pull request #3603
Opened 2024-02-01 05:45 UTC by JV0812

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [ ] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2024-02-01 07:20 UTC, kimsauce commented on docs/search/get-started-with-search/search-basics/chart-search-results.md
>  <img src={useBaseUrl('img/search/get-started-search/search-basics/log-query-charts-properties.png')} alt="log-query-charts-properties" style={{border:'1px solid black'}} width="800" />
```suggestion
The **New Visualization** feature enables the new chart visualizations for your log search, allowing you customize each chart by modifying the available settings and providing a unified experience across the Sumo Logic platforms.

* **Data**. This section represents the data that has been used to plot the chart. Toggle the **Round data point** ON/OFF the round off to the value in tooltip,.
* **Visual Settings**. These options allow you to further customize your chart: **Color Palette**, **Fill Opacity**, **Marker Type**, and **Dimensions** (x, y, and z).

<! -- insert New Visualizations screenshot -->
```

2024-02-01 07:26 UTC, kimsauce commented on docs/search/get-started-with-search/search-basics/chart-search-results.md
> +Charts will appear in new visualization style by default. If you prefer to use the classic visualizations UI, you can do so by clicking the **Classic Visualizations** button. You'll be asked to confi
```suggestion
Charts will appear in **New Visualization** style by default. If you prefer to use the **Classic Visualization** UI, click the **Classic Visualizations** button, then in the popup window, click **Switch to Classic Visualizations** to proceed.  

:::tip
If you choose **Classic Visualization**, your selection will be remembered, and any further searches in the same or new tab will always render with the classic visualization.
:::
```

2024-02-01 07:30 UTC, kimsauce commented on docs/search/get-started-with-search/search-basics/chart-search-results.md
> +* **Visual Settings**. These options allow you to further customize your chart: **Color Palette**, **Fill Opacity**, **Marker Type**, and **Dimensions** (x, y, and z).
```suggestion
* **Visual Settings**. These options allow you to further customize your chart: [**Color Palette**](/docs/dashboards/panels/modify-chart/#modifydisplay-settings), [**Fill Opacity**](/docs/dashboards/panels/modify-chart/#modifydisplay-settings), [**Marker Type**](/docs/dashboards/panels/modify-chart/#modifydisplay-settings), and [**Dimensions**](/docs/dashboards/panels/modify-chart/#modifychart-axes) (x, y, and z).
```

2024-02-01 07:31 UTC, kimsauce requested changes
Please ignore my comment about the screenshot - yours is all good! Sorry for the confusion. I just had one last comment...

2024-02-01 07:32 UTC, JV0812 commented
its okay Kim. Thanks for your review.

2024-02-01 07:32 UTC, kimsauce approved these changes

2024-02-01 07:33 UTC, kimsauce commented on docs/search/get-started-with-search/search-basics/chart-search-results.md
>  ### New Visualizations
```suggestion
### New Visualization
```

2024-05-23 08:26 UTC, JV0812 commented on docs/search/get-started-with-search/search-basics/chart-search-results.md
> +* **Visual Settings**. These options allow you to further customize your chart: [**Color Palette**](/docs/dashboards/panels/modify-chart/#modifydisplay-settings), [**Fill Opacity**](/docs/dashboards/
```suggestion
* **Visual Settings**. Allows you to further customize your chart. The other customizing properties include: [**Color Palette**](/docs/dashboards/panels/modify-chart/#modifydisplay-settings), [**Fill Opacity**](/docs/dashboards/panels/modify-chart/#modifydisplay-settings), [**Marker Type**](/docs/dashboards/panels/modify-chart/#modifydisplay-settings), and [**Dimensions**](/docs/dashboards/panels/modify-chart/#modifychart-axes) (x, y, and z).
```

2024-05-24 08:37 UTC, merged