Indicators for POV Trial Period Expiry
SumoLogic/sumologic-documentation pull request #3606
Opened 2024-02-01 08:25 UTC by JV0812

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [ ] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2024-02-01 09:39 UTC, kimsauce approved these changes

2024-02-03 01:23 UTC, kimsauce requested changes
@JV0812 Release note is dated 2/4, which is a Sunday. Should it be 2/5?

2024-02-05 07:00 UTC, JV0812 commented
@kimsauce The update was planned to release on 2nd Feb. But due to some production issues the release has been postponed and we are still not sure with the latest release date.

2024-02-06 04:54 UTC, kimsauce approved these changes

2024-02-06 05:19 UTC, merged