New enhancements to the Accounts page
SumoLogic/sumologic-documentation pull request #3657
Opened 2024-02-12 12:11 UTC by JV0812

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [ ] Yes, I've run `yarn install`
- [ ] No, does not apply to me

## Purpose of this pull request

This pull request...

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2024-02-12 16:07 UTC, jpipkin1 approved these changes
Looks good, @JV0812.

2024-02-26 17:25 UTC, kimsauce commented on docs/manage/manage-subscription/cloud-flex-credits-accounts.md
> +* **Usage Categories**. Table displaying the credits used, % of credits used, usgae % change, and units by usage categories ingest type and promotional credits usage.
```suggestion
* **Usage Categories**. Table displaying the credits used, % of credits used, usage % change, units by usage categories ingest type, and promotional credits usage.
```

2024-02-26 17:26 UTC, kimsauce requested changes
one fix

2024-02-27 23:16 UTC, kimsauce commented on blog-service/2024-03-01-manage.md
> +title: New Enhancements for Accounts page (Manage)
```suggestion
title: Accounts page enhancements (Manage)
```

2024-02-27 23:18 UTC, kimsauce commented on blog-service/2024-03-01-manage.md
> +  - release notes
No need to put 'release notes'
```suggestion
  - accounts
  - manage account
  - cloud flex credits
```

2024-02-27 23:18 UTC, kimsauce approved these changes

2024-03-04 11:31 UTC, merged