Remove beta article "Grant Access to Data in Audit Indexes'
SumoLogic/sumologic-documentation pull request #3734
Opened 2024-02-26 16:29 UTC by jpipkin1

## Purpose of this pull request

This pull request removes this article:
https://help.sumologic.com/docs/manage/security/audit-indexes/audit-index-access/

The beta article is no longer needed because the feature is replaced when this "RBAC for Indexes" article goes live (with PR #3393):
https://help.sumologic.com/docs/manage/users-roles/roles/rbac-for-indexes/

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## PLEASE READ

Following a recent back-end update, all contributors with a local clone or fork of our repository are required to run `yarn install`. This does not apply to [direct page edits](https://help.sumologic.com/docs/contributing/edit-doc/#minor-edits).

- [x] Yes, I've run `yarn install`
- [ ] No, does not apply to me

2024-02-26 17:35 UTC, kimsauce requested changes
question about redirecting an existing doc

2024-02-26 19:25 UTC, jpipkin1 commented on cid-redirects.json
> +  "/docs/manage/security/audit-index-access": "/docs/manage/users-roles/roles/rbac-for-indexes",
@kimsauce, that isn't a parent page. It's the old location of the beta article before a reworking of the Audit Indexes section.

2024-02-28 15:51 UTC, jpipkin1 commented on cid-redirects.json
> +  "/docs/manage/security/audit-index-access": "/docs/manage/users-roles/roles/rbac-for-indexes",
That last one is the most recent location of the beta to be removed. We can do a quick Zoom or Slack huddle if you need me to explain it

2024-02-29 16:28 UTC, kimsauce approved these changes

2024-02-29 17:37 UTC, kimsauce commented on cid-redirects.json
> +  "/docs/manage/security/audit-index-access": "/docs/manage/users-roles/roles/rbac-for-indexes",
thank you for explaining this! gotcha.

2024-02-29 18:05 UTC, closed without merging

2024-02-29 18:05 UTC, jpipkin1 commented
Closing this PR because it's replaced by this commit on PR #3393: "[Remove 'Grant Access to Data in Audit Indexes' article](https://github.com/SumoLogic/sumologic-documentation/pull/3393/commits/c38e2f0c82dea705ba4c800dff73a4153d25e71a)"