PR template edits
SumoLogic/sumologic-documentation pull request #3799
Opened 2024-03-07 20:14 UTC by kimsauce

## Purpose of this pull request

This pull request updates and streamlines PR template.

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions, .clabot
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2024-03-07 20:23 UTC, jpipkin1 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Enter the GitHub Issue number or the Jira ticket number (e.g., SUMO-12345) -->
Could you move this comment line about ticket numbers down to the section about tickets?

2024-03-07 20:23 UTC, jpipkin1 commented on .github/PULL_REQUEST_TEMPLATE.md
> +## Asana ticket (if applicable)
```suggestion
## Ticket (if applicable)
```

2024-03-07 20:26 UTC, jpipkin1 requested changes
@kimsauce, I have just a couple of comments.

2024-03-08 22:20 UTC, kimsauce commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- populates in this space automatically when you add this PR link to Asana ticket -->
```suggestion
<!-- enter your Jira, Asana, or GitHub ticket number -->
```

2024-03-08 22:20 UTC, kimsauce commented
> @kimsauce, I have just a couple of comments.

thank u!

2024-03-08 22:40 UTC, jpipkin1 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Enter the GitHub Issue number or the Jira ticket number (e.g., SUMO-12345) -->
```suggestion
```

2024-03-08 22:41 UTC, jpipkin1 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!-- Enter the GitHub Issue number or the Jira ticket number (e.g., SUMO-12345) -->
You can remove this line since you have the "Ticket (if applicable)" section below.

2024-03-08 22:43 UTC, jpipkin1 approved these changes
Approved, @kimsauce, contingent on your addressing one more comment.

2024-03-09 00:02 UTC, merged