Update hash-rules.md
SumoLogic/sumologic-documentation pull request #393
Opened 2022-09-30 18:54 UTC by stacykor

Hash 256 updates.

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2022-09-30 19:01 UTC, kimsauce commented on docs/send-data/collection/processing-rules/hash-rules.md
> +* The hash algorithm is MD5 (default) or 256. Open Telemetry collectors only support 256.
```suggestion
* The hash algorithm is MD5 (default) or 256. OpenTelemetry collectors only support 256.
```

2022-09-30 19:01 UTC, kimsauce requested changes
minor change!

2022-09-30 19:04 UTC, stacykor commented
Disabling Auto merge. Waiting on Maise

2022-09-30 19:08 UTC, stacykor commented
Team decided to wait until Monday.

2022-10-03 19:18 UTC, MariePMcGarry approved these changes

2022-10-03 19:40 UTC, closed without merging