CSOAR-1861: Add csoar cloud execution egress topic
SumoLogic/sumologic-documentation pull request #3939
Opened 2024-04-02 14:49 UTC by ffelici-sumo

Signed-off-by: Fabio Felici <ffelici@sumologic.com>

## Purpose of this pull request

This pull request mention the egress topic for cloud executions and how ask the ip address

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-04-03 15:20 UTC, jpipkin1 commented on docs/cloud-soar/architecture.md
> +Cloud Soar provides static egress for Cloud Executions. IP addresses can be entered into the allowlist. For a list of cloud soar addresses by region, contact [support](https://support.sumologic.com/h
```suggestion
Cloud Soar provides static egress for Cloud executions. IP addresses can be entered into the allowlist. For a list of Cloud Soar addresses by region, contact [support](https://support.sumologic.com/hc/en-us).
```

2024-04-03 15:20 UTC, jpipkin1 requested changes
I have a few suggestions, @ffelici-sumo.

2024-04-03 15:31 UTC, jpipkin1 approved these changes

2024-04-03 21:36 UTC, jpipkin1 commented
@ffelici-sumo, when you are ready to publish the PR, click **Merge when ready**.

2024-04-03 21:37 UTC, kimsauce commented on docs/cloud-soar/architecture.md
> +Cloud Soar provides static egress for Cloud executions. IP addresses can be entered into the allowlist. For a list of Cloud Soar addresses by region, contact [support](https://support.sumologic.com/h
```suggestion
Cloud SOAR provides static egress for Cloud executions. IP addresses can be entered into the allowlist. For a list of Cloud SOAR addresses by region, contact [Support](https://support.sumologic.com/hc/en-us).
```

2024-04-05 16:44 UTC, jpipkin1 commented on docs/cloud-soar/architecture.md
> +Cloud SOAR provides static egress for Cloud executions. IP addresses can be entered into the allowlist. For a list of Cloud SOAR addresses by region, contact [Support](https://support.sumologic.com/h
```suggestion
Cloud SOAR provides static egress for Cloud executions. IP addresses can be entered into the allowlist. For a list of Cloud SOAR addresses by region, contact [Support](https://support.sumologic.com/support/s/).
```

2024-04-08 13:24 UTC, merged