SUMO-239067: doc for v1-v2 10 apps
SumoLogic/sumologic-documentation pull request #3986
Opened 2024-04-17 13:14 UTC by shivani-sumo

## Purpose of this pull request

This pull request... 

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-04-18 13:44 UTC, himanshu219 requested changes
google cloud firewall seems missing

2024-04-18 14:05 UTC, himanshu219 commented
LGTM

2024-04-19 15:33 UTC, himanshu219 approved these changes

2024-04-19 15:41 UTC, JV0812 approved these changes
LGTM

2024-04-19 15:56 UTC, merged