Monitor Enhancements release notes
SumoLogic/sumologic-documentation pull request #4093
Opened 2024-05-15 11:33 UTC by JV0812

## Purpose of this pull request

This pull request is to create release notes for the Monitor updates.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

https://sumologic.atlassian.net/browse/SUMO-240929

2024-05-15 14:36 UTC, jpipkin1 commented on blog-service/2024-04-16-apps.md
> +We're excited to announce an update of all our terraform based monitors. Below are the list of enhancements that were a part of this update.
```suggestion
We're excited to announce an update of all our Terraform based monitors. Below are the list of enhancements that were a part of this update.
```

2024-05-15 14:40 UTC, jpipkin1 approved these changes
@JV0812, approved contingent on addressing my comments. You'll also have to change the date of the release note.

2024-05-18 02:14 UTC, kimsauce commented on blog-service/2024-04-16-apps.md
> +title: Monitor Enhancements (Apps)
```suggestion
title: Enhancements to Terraform-Based Monitors (Apps)
```

2024-05-18 02:17 UTC, kimsauce commented on blog-service/2024-04-16-apps.md
> +- Upgraded AWS and Sumologic provider versions for CVE fixes.
I have a couple edits on top of John's

```suggestion
- Updated Kubernetes monitors for compatibility with new Helm chart versions.
- Upgraded AWS and Sumo Logic provider versions to address CVE fixes.
```

2024-05-18 02:17 UTC, kimsauce requested changes
made some edits for clarity

2024-05-20 12:23 UTC, merged