Azure Blob Storage Collection Update release note
SumoLogic/sumologic-documentation pull request #4094
Opened 2024-05-15 12:46 UTC by JV0812

## Purpose of this pull request

This pull request is to create release note for Azure Blob Storage Collection Update.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

[Release notes for Azure Blob storage](https://sumologic.atlassian.net/browse/SUMO-240929)

2024-05-15 14:22 UTC, jpipkin1 commented on blog-service/2024-02-09-apps.md
> +For details on upgrade instructions, refer to the [changelog](https://github.com/SumoLogic/sumologic-azure-function/releases/tag/v4.0.0). Also, for more information on metrics collection from Azure M
```suggestion
For details on upgrade instructions, refer to the [changelog](https://github.com/SumoLogic/sumologic-azure-function/releases/tag/v4.0.0). Also, for more information on metrics collection from Azure Monitor, see our [documentation](/docs/send-data/collect-from-other-data-sources/azure-blob-storage/collect-logs-azure-blob-storage/).
```

2024-05-15 14:23 UTC, jpipkin1 approved these changes
Looks good, @JV0812. You'll need to change the date on the release note.

2024-05-17 22:28 UTC, kimsauce commented on blog-service/2024-02-09-apps.md
> +For details on upgrade instructions, refer to the [changelog](https://github.com/SumoLogic/sumologic-azure-function/releases/tag/v4.0.0). Also, for more information on metrics collection from Azure M
thanks for confirming!

2024-05-17 22:29 UTC, kimsauce commented on blog-service/2024-02-09-apps.md
> +For details on upgrade instructions, refer to the [changelog](https://github.com/SumoLogic/sumologic-azure-function/releases/tag/v4.0.0). Also, for more information on metrics collection from Azure M
```suggestion
For details on upgrade instructions, refer to the [changelog](https://github.com/SumoLogic/sumologic-azure-function/releases/tag/v4.0.0). For more information on logs collection from Azure Blob Storage, see our [documentation](/docs/send-data/collect-from-other-data-sources/azure-blob-storage/collect-logs-azure-blob-storage).
```

2024-05-17 22:31 UTC, kimsauce commented on blog-service/2024-02-09-apps.md
> +For details on upgrade instructions, refer to the [changelog](https://github.com/SumoLogic/sumologic-azure-function/releases/tag/v4.0.0). For more information on logs collection from Azure Blob Stora
```suggestion
For upgrade instructions, refer to the [changelog](https://github.com/SumoLogic/sumologic-azure-function/releases/tag/v4.0.0). For information on collecting logs from Azure Blob Storage, see our [documentation](/docs/send-data/collect-from-other-data-sources/azure-blob-storage/collect-logs-azure-blob-storage).
```

2024-05-17 22:31 UTC, kimsauce approved these changes

2024-05-17 23:00 UTC, jpipkin1 requested changes
Looks good, @JV0812. You'll need to change the date on the release note.

2024-05-20 14:10 UTC, jpipkin1 approved these changes

2024-05-20 14:39 UTC, merged