Query updated
SumoLogic/sumologic-documentation pull request #4114
Opened 2024-05-21 14:26 UTC by JV0812

## Purpose of this pull request

This pull request is to update the query from "parse regex" and promote using "json" operator in our documentation examples.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

https://sumologic.atlassian.net/browse/SUMO-241245

2024-05-21 15:18 UTC, jpipkin1 approved these changes

2024-05-27 09:19 UTC, AyanGhatak requested changes

2024-05-27 09:19 UTC, AyanGhatak commented on docs/alerts/monitors/alert-grouping.md
> +   | json field=data "sizeInBytes", "count" as bytes, count
```suggestion
   | parse regex "\"(?<collector>[^\"]*)\"\:(?<data>\{[^\}]*\})" multi
   | json field=data "sizeInBytes", "count" as bytes, count
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/alerts/scheduled-searches/faq.md
> +    | parse regex "\"(?<collector>[^\"]*)\"\:(?<data>\{[^\]}*\)" multi
```suggestion
    | parse regex "\"(?<collector>[^\"]*)\"\:(?<data>\{[^\}]*\})" multi
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/manage/ingestion-volume/data-volume-index/log-tracing-data-volume-index.md
> +| json field=data "billedBytes", "spansCount" as bytes, count
```suggestion
| parse regex "\"(?<sourcecategory>[^\"]+)\"\:(?<data>\{[^\}]*\})" multi
| json field=data "billedBytes", "spansCount"
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/manage/ingestion-volume/data-volume-index/log-tracing-data-volume-index.md
> +| json field=data "billedBytes", "spansCount" as bytes, count
```suggestion
| parse regex "\"(?<collector>[^\"]+)\"\:(?<data>\{[^\}]*\})" multi
| json field=data "billedBytes", "spansCount"
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/manage/ingestion-volume/data-volume-index/log-tracing-data-volume-index.md
> +| json field=data "billedBytes", "spansCount" as bytes, count
```suggestion
| parse regex "\"(?<collector>[^\"]+)\"\:(?<data>\{[^\}]*\})" multi
| json field=data "billedBytes", "spansCount"
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/manage/ingestion-volume/data-volume-index/log-tracing-data-volume-index.md
>  | parse regex "\"(?<collector>[^\"]+)\"\:\{\"billedBytes\"\:(?<billedBytes>\d+)\,\"spansCount\"\:(?<spansCount>\d+)\}" multi
```suggestion
| parse regex "\"(?<sourcecategory>[^\"]+)\"\:(?<data>\{[^\}]*\})" multi
| json field=data "billedBytes", "spansCount"
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/manage/ingestion-volume/data-volume-index/log-tracing-data-volume-index.md
> +| json field=data "billedBytes", "spansCount" as bytes, count
```suggestion
| parse regex "\"(?<sourcecategory>[^\"]+)\"\:(?<data>\{[^\}]*\})" multi
| json field=data "billedBytes", "spansCount"
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/manage/ingestion-volume/data-volume-index/metrics-data-volume-index.md
> +| json field=data "billedBytes", "spansCount" as bytes, count
```suggestion
| parse regex "\"(?<sourcecategory>[^\"]+)\"\:(?<data>\{[^\}]*\})" multi
| json field=data "billedBytes", "spansCount"
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/manage/ingestion-volume/data-volume-index/metrics-data-volume-index.md
> +| json field=data "dataPoints" as bytes
```suggestion
| parse regex "\"(?<sourcecategory>[^\"]+)\"\:(?<data>\{[^\}]*\})" multi
| json field=data "dataPoints"
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/manage/ingestion-volume/data-volume-index/metrics-data-volume-index.md
> +| json field=data "dataPoints" as bytes
```suggestion
| parse regex "\"(?<collector>[^\"]+)\"\:(?<data>\{[^\}]*\})" multi
| json field=data "dataPoints"
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/manage/ingestion-volume/data-volume-index/metrics-data-volume-index.md
> +| json field=data "dataPoints" as bytes
```suggestion
| parse regex "\"(?<collector>[^\"]+)\"\:(?<data>\{[^\}]*\})"
| json field=data "dataPoints"
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/manage/ingestion-volume/data-volume-index/metrics-data-volume-index.md
> +| json field=data "dataPoints" as bytes
```suggestion
| parse regex "\"(?<sourcecategory>[^\"]+)\"\:(?<data>\{[^\}]*\})" multi
| json field=data "dataPoints"
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/manage/ingestion-volume/data-volume-index/metrics-data-volume-index.md
> +| json field=data "dataPoints" as bytes
```suggestion
| parse regex "\"(?<sourcecategory>[^\"]+)\"\:(?<data>\{[^\}]*\})" multi
| json field=data "dataPoints"
```

2024-05-27 09:19 UTC, AyanGhatak commented on docs/search/search-query-language/math-expressions/round.md
> +| json field=data "sizeInBytes", "count" as bytes, count
```suggestion
| parse regex "\"(?<sourcehost>[^\"]*)\"\:(?<data>\{[^\}]*\})" multi
| json field=data "sizeInBytes", "count" as bytes, count
```

2024-05-27 09:19 UTC, AyanGhatak commented on i18n/ja/alerts/alerts/scheduled-searches/faqs/email-alert-data-usage-exceeded.md
> +    | json field=data "sizeInBytes", "count" as bytes, count
```suggestion
    | parse regex "\"(?<collector>[^\"]*)\"\:(?<data>\{[^\}]*\})" multi
    | json field=data "sizeInBytes", "count" as bytes, count
```

2024-05-27 10:16 UTC, AyanGhatak approved these changes

2024-05-27 11:16 UTC, merged