Updated RDS Doc for MSSQL dashboards
SumoLogic/sumologic-documentation pull request #4118
Opened 2024-05-22 10:25 UTC by akhil-sumologic

## Purpose of this pull request

Added new dashboards for MSSQL in Amazon RDS section.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

https://sumologic.atlassian.net/browse/SUMO-239934

2024-05-22 11:03 UTC, JV0812 commented on docs/integrations/amazon-aws/rds.md
> +The Sumo Logic Amazon RDS app dashboards provide visibility into the performance and operations of your Amazon Relational Database Service (RDS). Preconfigured dashboards allow you to monitor critica
```suggestion
The Sumo Logic Amazon RDS app dashboards provide visibility into the performance and operations of your Amazon Relational Database Service (RDS). Preconfigured dashboards allow you to monitor critical metrics of your RDS instance(s) or cluster(s) including CPU, memory, storage, network transmits and receive throughput, read and write operations, database connection count, disk queue depth, and more. CloudTrail Audit dashboards help you monitor activities performed on your RDS infrastructure. MySQL Logs dashboards helps you monitor database errors, slow queries, audit sql queries and generic activities. PostgreSQL logs dashboard help you to monitor database errors, slow queries, database security, and query execution timings. MSSQL Logs dashboards helps you monitor error logs and basic infrastructure details. 
```

2024-05-22 11:54 UTC, JV0812 commented on docs/integrations/amazon-aws/rds.md
> +The **Amazon RDS - MSSQL Logs - Error Logs - Logon Analysis** dashboard provides details for error logs, including failed authentications, logon error. This dashboard relies on MSSQL error logs, whic
```suggestion
The **Amazon RDS - MSSQL Logs - Error Logs - Logon Analysis** dashboard provides information about the error logs, including failed authentications and logon errors. This dashboard relies on MSSQL error logs, which need to be [enabled](#collect-amazon-rds-cloudwatch-logs) for the Amazon MSSQL. You need to first ingest MSSQL logs into Sumo Logic to view data on the dashboard panels.
```

2024-05-22 11:56 UTC, JV0812 commented on docs/integrations/amazon-aws/rds.md
> +* Identify the authentication failures along with reason for user, client host, and client location that are used to connect.
```suggestion
* Identify authentication failures, including the user, client host, and location used for connection.
```

2024-05-22 11:57 UTC, JV0812 commented on docs/integrations/amazon-aws/rds.md
> +* Detect logon errors along with their associated error codes, severity levels, and states.
```suggestion
* Detect logon errors, including error codes, severity levels, and states.
```

2024-05-22 11:57 UTC, JV0812 commented on docs/integrations/amazon-aws/rds.md
> +<img src={useBaseUrl('img/integrations/amazon-aws/Amazon-RDS-MSSQL-Logs-Error-Logs-Logon Analysis.png')} alt="Amazon RDS dashboard" />
```suggestion
<img src={useBaseUrl('img/integrations/amazon-aws/Amazon-RDS-MSSQL-Logs-Error-Logs-Logon Analysis.png')} style={{border:'1px solid gray’}} alt="Amazon RDS dashboard" />
```

2024-05-22 11:57 UTC, JV0812 commented on docs/integrations/amazon-aws/rds.md
> +<img src={useBaseUrl('img/integrations/amazon-aws/Amazon-RDS-MSSQL-Logs-Error-Logs-Infrastructure-Overview.png')} alt="Amazon RDS dashboard" />
```suggestion
<img src={useBaseUrl('img/integrations/amazon-aws/Amazon-RDS-MSSQL-Logs-Error-Logs-Infrastructure-Overview.png')} style={{border:'1px solid gray’}} alt="Amazon RDS dashboard" />
```

2024-05-22 11:59 UTC, JV0812 commented on docs/integrations/amazon-aws/rds.md
> +The **Amazon RDS - MSSQL Logs - Error Logs - Infrastructure Overview** dashboard provides details for hardware, authentications mode, collation, process, recent termination of SQL server and recent c
```suggestion
The **Amazon RDS - MSSQL Logs - Error Logs - Infrastructure Overview** dashboard provides about the hardware, authentication mode, collation, process, recent termination of SQL server, and recent creation of databases. This dashboard relies on MSSQL error logs, which need to be [enabled](#collect-amazon-rds-cloudwatch-logs) and ingested into Sumo Logic.
```

2024-05-22 12:00 UTC, JV0812 commented on docs/integrations/amazon-aws/rds.md
> +* Get a high-level overview of your MSSQL infrastructure like instance type, version.
```suggestion
* Get a high-level overview of your MSSQL infrastructure like instance type and version.
```

2024-05-22 12:01 UTC, JV0812 commented on docs/integrations/amazon-aws/rds.md
> +* Get configuration details such as authentication mode, collation settings and process details.
```suggestion
* Get configuration details such as authentication mode, collation settings, and process details.
```

2024-05-22 12:01 UTC, JV0812 requested changes
Minor fix

2024-05-23 04:56 UTC, akhil-sumologic commented on docs/integrations/amazon-aws/rds.md
> +* Track recent terminations of SQL Server instances and monitor the creation of new databases.
> Track recent terminations of SQL Server instances and monitor the creation of new databases.

what is correction here ?

2024-05-23 07:12 UTC, JV0812 commented on docs/integrations/amazon-aws/rds.md
> +* Track recent terminations of SQL Server instances and monitor the creation of new databases.
Nothing to change here.

2024-05-24 11:02 UTC, merged