Jamf C2C doc and release notes
SumoLogic/sumologic-documentation pull request #4165
Opened 2024-06-05 06:59 UTC by JV0812

## Purpose of this pull request

This pull request is to create a new doc for Jamf C2C and the respective release notes.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

[JAMF C2C - Documentation](https://sumologic.atlassian.net/browse/CONN-3257)

2024-06-05 10:48 UTC, shivani-sumo commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jamf-source.md
> +| schemaRef | JSON Object  | `{"type":"Jmaf"}` | Yes | Define the specific schema type. |
Correct the typo to Jamf instead jmaf.

2024-06-05 10:48 UTC, shivani-sumo commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jamf-source.md
> +- The Base URL is used to retrieve the source data from the Jamf. The **Base URL** for Jamf is `https://yourServer.jamfcloud.com`.
Could you please add below line after the URL?
`Replace "yourServer" with your organization server.`

2024-06-05 11:24 UTC, shivani-sumo approved these changes

2024-06-05 15:18 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jamf-source.md
> +- The Base URL is used to retrieve the source data from the Jamf. The **Base URL** for Jamf is `https://yourServer.jamfcloud.com`, replace `yourServer` with your organization server.
```suggestion
- The Base URL is used to retrieve the source data from Jamf. The **Base URL** for Jamf is `https://yourServer.jamfcloud.com`. Replace `yourServer` with your organization server.
```

2024-06-05 15:20 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/jamf-source.md
> +Sources can be configured using UTF-8 encoded JSON files with the Collector Management API. See [How to Use JSON to Configure Sources](/docs/send-data/use-json-configure-sources) for details. 
```suggestion
Sources can be configured using UTF-8 encoded JSON files with the Collector Management API. See [Use JSON to Configure Sources](/docs/send-data/use-json-configure-sources) for details. 
```

2024-06-05 15:28 UTC, jpipkin1 approved these changes
Looks good @JV0812! I have only minor comments. And I added the new article to the Product List article (see commit "[Add Jamf Source to product list](https://github.com/SumoLogic/sumologic-documentation/pull/4165/commits/a9462215fdd184d977abe6904119bb0b28418810)").

2024-06-05 15:37 UTC, kimsauce commented on blog-service/2024-06-07-collection.md
> +  - collection
```suggestion
  - collection
  - jamf
```

2024-06-05 15:40 UTC, kimsauce commented on blog-service/2024-06-07-collection.md
> +title: Jamf (Collection)
```suggestion
title: Jamf C2C Source (Collection) 
```

2024-06-05 15:42 UTC, kimsauce requested changes
Nice work! Had a couple minor edits to help boost SEO.

2024-06-06 05:29 UTC, JV0812 commented
@jpipkin1 Sorry, I missed it. Thanks for helping me with that and for your review.

2024-06-06 06:56 UTC, kimsauce approved these changes

2024-06-10 14:44 UTC, merged