Format updated for download example button
SumoLogic/sumologic-documentation pull request #4199
Opened 2024-06-11 13:13 UTC by JV0812

## Purpose of this pull request

This pull request is to update the format of the download example button in all the C2C source docs.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

https://sumologic.atlassian.net/browse/DOCS-271

2024-06-11 14:52 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/okta-source.md
> +<a href="/files/c2c/okta/example.tf" target="_blank">Download example</a>
```suggestion
<a href="/files/c2c/okta/example.json" target="_blank">Download example</a>
```

2024-06-11 15:04 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/webex-source.md
> +<a href="/files/c2c/webex/example.tf)" target="_blank">Download example</a>
```suggestion
<a href="/files/c2c/webex/example.tf" target="_blank">Download example</a>
```

2024-06-11 15:04 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/workday-source.md
> +<a href="/files/c2c/workday/example.json)" target="_blank">Download example</a>
```suggestion
<a href="/files/c2c/workday/example.json" target="_blank">Download example</a>
```

2024-06-11 15:05 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/workday-source.md
> +<a href="/files/c2c/workday/example.tf)" target="_blank">Download example</a>
```suggestion
<a href="/files/c2c/workday/example.tf" target="_blank">Download example</a>
```

2024-06-11 15:06 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/zero-networks-segment-source.md
> +<a href="/files/c2c/zero-networks-segment/example.tf)" target="_blank">Download example</a>
```suggestion
<a href="/files/c2c/zero-networks-segment/example.tf" target="_blank">Download example</a>
```

2024-06-11 15:30 UTC, jpipkin1 requested changes
It looks great, @JV0812! I found a few things you need to fix. I also found and updated some other download links (see commit "[Fix a few more instances](https://github.com/SumoLogic/sumologic-documentation/pull/4199/commits/7450511f0fa4166245753849ac5be2671416e97a)"). 

I don't think you need code anymore at the top of the articles to import the files. It's not causing any problems, but you might want to remove it. For example:
>import MyComponentSource from '!!raw-loader!/files/c2c/airtable/example.json';
>import TerraformExample from '!!raw-loader!/files/c2c/airtable/example.tf';

2024-06-12 04:23 UTC, JV0812 commented
@jpipkin1 I thought these will be required to the <codeblocks> to display the json or .tf example. Let me cross check it and if not required i will remove this too.

2024-06-12 14:04 UTC, jpipkin1 approved these changes

2024-06-12 14:27 UTC, merged