Ingest Budgets v2 release notes
SumoLogic/sumologic-documentation pull request #4216
Opened 2024-06-18 06:44 UTC by JV0812

## Purpose of this pull request

This pull request is to create a release note for Ingest budget V1 deprecation.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-06-18 07:18 UTC, kimsauce requested changes
a few changes!

2024-06-18 07:18 UTC, kimsauce commented on blog-service/2024-06-22-manage.md
> +title: Ingest Budgets (Manage)
```suggestion
title: Deprecation of Legacy Ingest Budgets V1 – Action Required by September 9, 2024 (Manage) 
```

2024-06-18 07:18 UTC, kimsauce commented on blog-service/2024-06-22-manage.md
> +In November 2020, Sumo Logic announced the release of a product enhancement to our Ingest Budget feature (v2) that allowed greater flexibility and granularity in the metadata and fields, which is def
```suggestion
In November 2020, we introduced Ingest Budgets V2, offering greater flexibility and granularity in metadata and fields within the Ingest Budget Definition. Despite this update, existing V1 budgets continued to function as originally defined when creating new V2 budgets was not possible.
```

2024-06-18 07:18 UTC, kimsauce commented on blog-service/2024-06-22-manage.md
> +**On September 9. 2024**, Sumo Logic will deprecate and remove the existing v1 Ingest Budgets that remain defined in customer Instances.
```suggestion
**On September 9. 2024**, Sumo Logic will deprecate and remove the existing V1 Ingest Budgets that remain defined in customer Instances. 
```

2024-06-18 07:18 UTC, kimsauce commented on blog-service/2024-06-22-manage.md
> +Prior to September 9, 2024, review your current Ingest Budgets located in **Manage Data > Collection > Ingest Budgets** and any budgets tagged as v1. If these budgets are still needed and valid, you
```suggestion
To ensure uninterrupted service, please review your current Ingest Budgets under **Manage Data > Collection > Ingest Budgets**. Identify any budgets tagged as V1 and, if still needed, [edit and upgrade them to V2](https://github.com/docs/manage/ingestion-volume/ingest-budgets/daily-volume/#versions) before the deprecation date.
```

2024-06-18 07:18 UTC, kimsauce commented on blog-service/2024-06-22-manage.md
> +After the deprecation date, these legacy Ingest Budgets will be automatically removed, and if not migrated you can no longer limit ingestion.
```suggestion
After September 9, 2024, any legacy Ingest Budgets that are not migrated will be automatically removed, resulting in the loss of ingestion limitation functionality.
```

2024-06-19 21:51 UTC, kimsauce approved these changes

2024-06-20 17:20 UTC, jschwegler-sumo requested changes
**Update this sentence:**
continued to function as originally defined when creating new V2 budgets was not possible.

**With:**
continued to function as originally defined while only allowing v2 budgets for all new configurations going forward.

**Can we also just uncapitalize instances here?**

Ingest Budgets that remain defined in customer Instances

2024-06-20 18:04 UTC, kimsauce commented on blog-service/2024-06-22-manage.md
> +In November 2020, we introduced Ingest Budgets V2, offering greater flexibility and granularity in metadata and fields within the Ingest Budget Definition. Despite this update, existing V1 budgets co
```suggestion
In November 2020, we introduced Ingest Budgets V2, offering greater flexibility and granularity in metadata and fields within the Ingest Budget Definition. Despite this update, existing V1 budgets continued to function as originally defined while only allowing v2 budgets for all new configurations going forward.
```

2024-06-20 18:05 UTC, kimsauce commented on blog-service/2024-06-22-manage.md
> +To ensure uninterrupted service, review your current Ingest Budgets under **Manage Data > Collection > Ingest Budgets**. Identify any budgets tagged as V1 and, if still needed, [edit and upgrade them
```suggestion
To ensure uninterrupted service, review your current ingest budgets under **Manage Data > Collection > Ingest Budgets**. Identify any budgets tagged as V1 and, if still needed, [edit and upgrade them to V2](https://github.com/docs/manage/ingestion-volume/ingest-budgets/daily-volume/#versions) before the deprecation date.
```

2024-06-20 18:05 UTC, kimsauce commented on blog-service/2024-06-22-manage.md
> +After September 9, 2024, any legacy Ingest Budgets that are not migrated will be automatically removed, resulting in the loss of ingestion limitation functionality.
```suggestion
After September 9, 2024, any legacy ingest budgets that are not migrated will be automatically removed, resulting in the loss of ingestion limitation functionality.
```

2024-06-20 18:06 UTC, kimsauce commented
> **Update this sentence:** continued to function as originally defined when creating new V2 budgets was not possible.
> 
> **With:** continued to function as originally defined while only allowing v2 budgets for all new configurations going forward.
> 
> **Can we also just uncapitalize instances here?**
> 
> Ingest Budgets that remain defined in customer Instances

@jschwegler-sumo , done!

2024-06-20 18:09 UTC, jschwegler-sumo commented
> > **Update this sentence:** continued to function as originally defined when creating new V2 budgets was not possible.
> > **With:** continued to function as originally defined while only allowing v2 budgets for all new configurations going forward.
> > **Can we also just uncapitalize instances here?**
> > Ingest Budgets that remain defined in customer Instances
> 
> @jschwegler-sumo , done!

@kimsauce All good from my side.

2024-06-24 06:35 UTC, merged