DOCS-282 - Add Cloud SIEM example for Copilot
SumoLogic/sumologic-documentation pull request #4218
Opened 2024-06-18 17:29 UTC by jpipkin1

## Purpose of this pull request

This pull request adds a Cloud SIEM example section to the Copilot preview article: https://help.sumologic.com/docs/search/copilot

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

[DOCS-282](https://sumologic.atlassian.net/browse/DOCS-282)

2024-06-19 04:54 UTC, JV0812 commented on docs/search/copilot.md
> +   Notice the system translated this suggestion to a log query and rendered results as a bar graph with no user input. <br/><img src={useBaseUrl('img/search/copilot/copilot-cloud-siem-2.png')} alt="C
```suggestion
   Notice the system translated suggestion to a log query and rendered results as a bar graph with no user input. <br/><img src={useBaseUrl('img/search/copilot/copilot-cloud-siem-2.png')} alt="Copilot tab" style={{border: '1px solid gray'}} width="800" />
```

2024-06-19 04:56 UTC, JV0812 approved these changes
Great work, @jpipkin1.

2024-06-19 15:06 UTC, jpipkin1 commented on docs/search/copilot.md
> +   Notice the system translated this suggestion to a log query and rendered results as a bar graph with no user input. <br/><img src={useBaseUrl('img/search/copilot/copilot-cloud-siem-2.png')} alt="C
```suggestion
   Notice the system translated the suggestion to a log query and rendered results as a bar graph with no user input. <br/><img src={useBaseUrl('img/search/copilot/copilot-cloud-siem-2.png')} alt="Copilot tab" style={{border: '1px solid gray'}} width="800" />
```

2024-06-19 15:07 UTC, jpipkin1 commented
Thanks for the review, @JV0812!

@kimsauce, could you review this PR, since you own the article?

2024-06-19 21:49 UTC, kimsauce requested changes
Hi @jpipkin1 ! In my previous examples, I rewrote them so that they don't mention a person's name and instead I use "you" or "we". What do you think?

2024-06-20 14:16 UTC, jpipkin1 commented
Great suggestion, @kimsauce. It's updated now.

2024-06-20 16:12 UTC, kimsauce approved these changes

2024-06-20 16:58 UTC, merged