App central incident tool integration
SumoLogic/sumologic-documentation pull request #4239
Opened 2024-06-24 13:06 UTC by rishav-sumo-dev

## Purpose of this pull request

This pull request... 

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-06-24 19:12 UTC, kimsauce commented on docs/platform-services/automation-service/app-central/integrations/servicenow-v2.md
> +tags: []
We're no longer inserting this `tags` line in metadata

```suggestion
```

2024-06-24 19:17 UTC, kimsauce commented on docs/platform-services/automation-service/app-central/integrations/incident-tools.md
> +* June 24, 2024 (v1.8) - Removed the requirement for ***Field ID*** and ***Field Value*** fields in the **Update Incident Fields** action (the fields are now optional).
```suggestion
* June 24, 2024 (v1.8) - The **Field ID** and **Field Value** fields are now optional in the **Update Incident Fields** action.
```

2024-06-24 19:17 UTC, kimsauce requested changes
one suggestion

2024-06-26 05:34 UTC, JV0812 approved these changes
LGTM

2024-06-26 06:10 UTC, kimsauce approved these changes

2024-06-27 21:06 UTC, merged