Updated RDS Doc for MSSQL dashboards for AWSO 2.9.0
SumoLogic/sumologic-documentation pull request #4257
Opened 2024-06-28 09:40 UTC by akhil-sumologic

## Purpose of this pull request

Added new dashboards for MSSQL in Amazon RDS section for awso

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

https://sumologic.atlassian.net/browse/SUMO-240446

2024-06-28 10:26 UTC, JV0812 commented on docs/integrations/amazon-aws/rds.md
> +* Identify number of Slow queries by user, host and command type along with slow queries over time by user and database.
```suggestion
* Identify number of Slow queries by user, host, and command type along with slow queries over time by user and database.
```

2024-06-28 10:32 UTC, JV0812 commented on docs/observability/aws/deploy-use-aws-observability/configure-alerts.md
> +| Amazon RDS MSSQL - Database observing authentication failures from multiple client IPs | This alert fires when we detect more than or equal to 10 client IPs attempting authentication failures on th
```suggestion
| Amazon RDS MSSQL - Database observing authentication failures from multiple client IPs | This alert fires when we detect more than or equal to 10 client IPs attempting authentication failures on the database over a 15 minute time-period. | &#62;&#61;1 | &#60;1 |
```

2024-06-28 10:35 UTC, JV0812 commented on docs/observability/aws/integrations/amazon-rds.md
> +* [Publishing RDS CloudWatch logs, RDS Database logs for Aurora PostgreSQL, RDS PostgreSQL](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.PostgreSQL.html#USER_LogAcce
```suggestion
* [Publishing RDS CloudWatch logs, RDS Database logs for Aurora PostgreSQL, and RDS PostgreSQL](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.PostgreSQL.html#USER_LogAccess.Concepts.PostgreSQL.PublishtoCloudWatchLogs)
```

2024-06-28 10:35 UTC, JV0812 commented on docs/observability/aws/integrations/amazon-rds.md
> +* Identify number of Slow queries by user, host and command type along with slow queries over time by user and database.
```suggestion
* Identify number of slow queries by user, host, and command type along with slow queries over time by user and database.
```

2024-06-28 10:37 UTC, JV0812 commented on docs/observability/aws/integrations/amazon-rds.md
> +* Identify number of Slow queries by user, host and command type along with slow queries over time by user and database.
There is no UI support here to capitalize "S" here. Slow Query Overview is the dashboard title and that is covered in the first paragraph.

2024-06-28 10:40 UTC, JV0812 commented on docs/observability/aws/integrations/amazon-rds.md
> +The **Amazon RDS - MSSQL Logs - Error Logs - Infrastructure Overview** dashboard provides about the hardware, authentication mode, collation, process, recent termination of SQL server, and recent cre
```suggestion
The **Amazon RDS - MSSQL Logs - Error Logs - Infrastructure Overview** dashboard provides information about the hardware, authentication mode, collation, process, recent termination of SQL server, and recent creation of databases. This dashboard relies on MSSQL error logs, which need to be [enabled](#collect-amazon-rds-cloudwatch-logs) and ingested into Sumo Logic.
```

2024-06-28 10:40 UTC, JV0812 requested changes
Minor fixes

2024-06-28 11:30 UTC, JV0812 approved these changes
LGTM

2024-06-29 03:12 UTC, kimsauce approved these changes

2024-07-19 06:03 UTC, JV0812 commented
Merged the PR: https://github.com/SumoLogic/sumologic-documentation/pull/4290 in order to maintain a single PR for AWSO 2.9.0 docs changes.

2024-07-22 19:58 UTC, kimsauce commented on docs/observability/aws/deploy-use-aws-observability/changelog.md
> +### This version has been Yanked. Please deploy/ update to AWS Observabilty v2.9.0 or latest version.
```suggestion
### This version has been Yanked. Please deploy/update to AWS Observabilty v2.9.0 or latest version.
```

2024-07-22 19:59 UTC, kimsauce commented on docs/observability/aws/deploy-use-aws-observability/changelog.md
> +* Amazon RDS app - New monitors added for RDS MS SQL CloudWatch logs. Solution now supports 70 out of box monitors.
```suggestion
* Amazon RDS app - New monitors added for RDS MS SQL CloudWatch logs. Solution now supports 70 out-of-box monitors.
```

2024-07-22 20:00 UTC, kimsauce commented on docs/observability/aws/deploy-use-aws-observability/changelog.md
> +* Resolved an issue where updating from versions lower than v2.8.0 to v2.8.0 was not functioning correctly. Users are now recommended to update directly to v2.9.0 without needing to go through v2.8.0
```suggestion
* Resolved an issue where updating from versions lower than v2.8.0 to v2.8.0 was not functioning correctly. Users are now recommended to update directly to v2.9.0, bypassing v2.8.0.
```

2024-08-02 07:15 UTC, merged