Update Copilot icon
SumoLogic/sumologic-documentation pull request #4380
Opened 2024-07-31 20:59 UTC by kimsauce

## Purpose of this pull request

This pull request:
- Updates the Copilot icon
- Applies /get-started edits that I came across in reviewing the AI and Copilot docs

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

2024-07-31 20:59 UTC, kimsauce commented on docs/get-started/library.md
> +1. Click **Unpin**.
```suggestion
1. Click **Unpin**. 
```

2024-07-31 21:00 UTC, kimsauce commented on docs/get-started/library.md
> +1. Click **Add New > New Folder**.
```suggestion
1. Click **Add New > New Folder**. 
```

2024-07-31 21:00 UTC, kimsauce commented on docs/get-started/library.md
> +Open the **Library** page to expose additional search options and to organize and manage Library contents.
```suggestion
Open the **Library** page to expose additional search options and to organize and manage Library contents. 
```

2024-07-31 22:46 UTC, jpipkin1 requested changes
@kimsauce, the old icon still appears in the upper left of many screenshots in the Copilot article. You'll want to update those.

<img width="866" alt="source-category" src="https://github.com/user-attachments/assets/b4ac953e-7038-4945-8046-65c8d530d2f4">

2024-07-31 23:21 UTC, kimsauce commented
> @kimsauce, the old icon still appears in the upper left of many screenshots in the Copilot article. You'll want to update those.
> 
> <img alt="source-category" width="866" src="https://private-user-images.githubusercontent.com/127961815/354018883-b4ac953e-7038-4945-8046-65c8d530d2f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NjgzNjQsIm5iZiI6MTcyMjQ2ODA2NCwicGF0aCI6Ii8xMjc5NjE4MTUvMzU0MDE4ODgzLWI0YWM5NTNlLTcwMzgtNDk0NS04MDQ2LTY1YzhkNTMwZDJmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQyMzIxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMTlmMzc3ODFiMTM0N2ZlYTJiODQzYjU5NzVjMDA0N2VjNzYyZWE1NWQwM2RiMmQ0MDY2MmNiNTJiOTkyYzdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qjIFjhnrZo9eIIwHA7qaVguWBECw3sAdym-yKsbHqqE">

Oh, good call! I completely missed that. I'll fix and resubmit.

2024-08-01 21:29 UTC, kimsauce commented
Thanks again for catching those images, @jpipkin1 ! I've fixed them all except for the video and gif. Since the product is so in flux, those will likely be updated anyway.

2024-08-01 22:16 UTC, jpipkin1 approved these changes
Looks great, @kimsauce!

2024-08-01 22:27 UTC, merged