Azure application gateway doc
SumoLogic/sumologic-documentation pull request #4444
Opened 2024-08-20 06:43 UTC by sachin-sumologic

## Purpose of this pull request

This pull request is for Azure application gateway document

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [x] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-08-20 14:37 UTC, jpipkin1 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +Now that you have set up data collection, install the Azure Application Gateway Sumo Logic app to use the pre-configured dashboards that provide visibility into your environment for real-time analysi
You refer to dashboards, but there is no section for dashboards in this article. Do you need to add it?

2024-08-20 14:37 UTC, jpipkin1 requested changes
@sachin-sumologic, I made some minor changes (see commit "[Updates from review](https://github.com/SumoLogic/sumologic-documentation/pull/4444/commits/8f2a40533be5193cd7bb2bbbbf469f04c5c3c564)").

2024-08-20 18:41 UTC, kimsauce commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +### Configure fields in field schema
```suggestion
### Configure field in field schema
```

2024-08-21 04:44 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +   - `resource_name`. The name of the resource (for example, storage account name).
lets add service_type, service_name also similar to Azure SQL

2024-08-21 04:47 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +|------------------|----------------|
refer the format `|:------------------|:----------------|` in sql.md

2024-08-21 04:54 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
lets add a screenshot of diagnostic settings similar to azure sql.

2024-08-21 04:55 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> -   * Use the Event hub namespace and Event hub name configured in previous step in destination details section. You can use the default policy `RootManageSharedAccessKey` as the policy name.
lets add a screenshot similar to azure sql for logs diagnostic settings

2024-08-21 04:57 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +
need to add steps on how to enable health metrics or security metrics where additional efforts were required.

2024-08-23 09:45 UTC, JV0812 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +   - `service_type`. Type of the service that can be accessed from with a azure resource.
```suggestion
   - `service_type`. Type of the service that can be accessed with a Azure resource.
```

2024-08-23 09:46 UTC, JV0812 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +   - `service_name`. Services that can be accessed from within an Azure resource (for example, Azure SQL databases in Azure SQL Server).
```suggestion
   - `service_name`. Services that can be accessed with an Azure resource (for example, Azure SQL databases in Azure SQL Server).
```

2024-08-23 09:49 UTC, JV0812 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +2. To create the diagnostic settings in Azure portal, refer to the [Azure documentation](https://learn.microsoft.com/en-gb/azure/data-factory/monitor-configure-diagnostics). Perform the steps below f
```suggestion
2. To create the **Diagnostic setting** in Azure portal, refer to the [Azure documentation](https://learn.microsoft.com/en-gb/azure/data-factory/monitor-configure-diagnostics). Perform the steps below for each Azure application gateway account that you want to monitor.
```

2024-08-23 09:50 UTC, JV0812 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +   * Choose **Stream to an event hub** as the destination.
Please add numbered bulletins since these are series of steps.

2024-08-23 09:52 UTC, JV0812 requested changes
Dashboards info missing and some minor formatting issues.

2024-08-28 11:02 UTC, himanshu219 requested changes
lets puts all the screenshots in s3 otherwise the github repo becomes too large

2024-08-28 11:19 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +Rule Name: AzureObservabilityMetadataExtractionServiceLevel
this rule is not needed for application gateways since we it does not use service_name and service_type.

2024-08-28 14:14 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +For Security events, make sure you enable [Microsoft Defender for Cloud](https://learn.microsoft.com/en-us/azure/azure-sql/database/azure-defender-for-sql?view=azuresql#enable-microsoft-defender-for-
this link is for sql

2024-08-28 14:18 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-storage.md
> -<img src={useBaseUrl('img/integrations/microsoft-azure/Azure-Storage-Overview.png')} alt="Azure Storage Overview dashboard" style={{border: '1px solid gray'}} width="800" />
add the enable defender for azure storage https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-storage-azure-portal-enablement?tabs=enable-storage-account

2024-08-28 14:20 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +
need to add a note that WAF metrics or WAF logs will come only after enabling policies and for WAF v2 tier right ?

2024-08-29 07:36 UTC, JV0812 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +### Configure field extraction rules
```suggestion
### Configure Field Extraction Rules
```

2024-08-29 10:20 UTC, himanshu219 approved these changes

2024-08-29 10:56 UTC, JV0812 commented on docs/integrations/microsoft-azure/azure-application-gateway.md
> +This app support only Application Gateway v2 as  Application Gateway V1 will soon be deprecated
```suggestion
This app supports only Application Gateway V2 since Application Gateway V1 will soon be deprecated.
```

2024-08-29 10:56 UTC, JV0812 commented on docs/integrations/microsoft-azure/sql.md
> +In **Defender Plans** Settings page toggle the **Databases** status under **Cloud Workload Protection** section.
```suggestion
In **Defender Plans** settings page turn on the **Databases** status under **Cloud Workload Protection** section.
```

2024-08-29 10:57 UTC, JV0812 commented on docs/integrations/microsoft-azure/azure-storage.md
> +##### Enabling Microsoft Defender for Cloud
```suggestion
##### Enabling Microsoft Defender for Cloud

```

2024-08-29 11:00 UTC, JV0812 approved these changes
LGTM

2024-08-29 11:43 UTC, merged