Otel collector configuration page update
SumoLogic/sumologic-documentation pull request #4457
Opened 2024-08-22 10:36 UTC by JV0812

## Purpose of this pull request

This pull request is to update the Otel collector configuration page.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-08-22 15:27 UTC, jpipkin1 commented on docs/send-data/opentelemetry-collector/install-collector/windows.md
> +1. (Optional) In the **Collector Settings**, select **Ephemeral** checkbox to auto-delete your collector after 12 hours and select **Locally Manage Collector** checkbox if you want to configure, main
```suggestion
1. (Optional) In the **Collector Settings**, select the **Ephemeral** checkbox to auto-delete your collector after 12 hours and select the **Locally Manage Collector** checkbox if you want to configure, maintain, and monitor the collector locally.
```

2024-08-22 15:27 UTC, jpipkin1 approved these changes

2024-08-22 15:45 UTC, kimsauce requested changes
Looks good, just minor stuff

2024-08-22 15:45 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/install-collector/linux.md
> +1. (Optional) In the **Collector Settings**, select **Ephemeral** checkbox to auto-delete your collector after 12 hours and select **Locally Manage Collector** checkbox if you want to configure, main
```suggestion
1. (Optional) In the **Collector Settings**, select the **Ephemeral** checkbox to auto-delete your collector after 12 hours, and select the **Locally Manage Collector** checkbox if you want to configure, maintain, and monitor your collector locally.
```

2024-08-22 15:45 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/install-collector/macos.md
> +1. (Optional) In the **Collector Settings**, select **Ephemeral** checkbox to auto-delete your collector after 12 hours and select **Locally Manage Collector** checkbox if you want to configure, main
```suggestion
1. (Optional) In the **Collector Settings**, select the **Ephemeral** checkbox to auto-delete your collector after 12 hours, and select the **Locally Manage Collector** checkbox if you want to configure, maintain, and monitor your collector locally.
```

2024-08-28 07:20 UTC, JV0812 commented on docs/send-data/opentelemetry-collector/install-collector/chef.md
> +7. 7. On the next screen, you will see a list of available Source Templates. Select the required Source Template and proceed with the data configuration.
```suggestion
7. On the next screen, you will see a list of available Source Templates. Select the required Source Template and proceed with the data configuration.
```

2024-08-28 07:21 UTC, JV0812 commented on docs/send-data/opentelemetry-collector/install-collector/macos.md
```suggestion
1. On the next screen, you will see a list of available Source Templates. Select the required Source Template and proceed with the data configuration.

If you choose to close this Source template creation screen, you can navigate back. <!--Kanso [**Classic UI**](/docs/get-started/sumo-logic-ui/). Kanso--> In the main Sumo Logic menu, select **Manage Data > Collection > Source Template**. <!--Kanso <br/>[**New UI**](/docs/get-started/sumo-logic-ui-new/). In the Sumo Logic top menu select **Configuration**, and then under **Data Collection** select **Source Template**.  Kanso--> 
```

2024-08-29 07:10 UTC, kimsauce approved these changes

2024-09-20 19:23 UTC, jpipkin1 commented
@JV0812, I made updates for Kanso with commits "[Kanso fixes](https://github.com/SumoLogic/sumologic-documentation/pull/4457/commits/df44eac554c72d7134151782eefb7dde46c8a09e)" and "[Small fix](https://github.com/SumoLogic/sumologic-documentation/pull/4457/commits/8d2bd928a869e57723aa44adc13359b93525517b)" ([DOCS-207](https://sumologic.atlassian.net/browse/DOCS-207)).

2025-04-25 03:29 UTC, kimsauce commented
Hi @JV0812 , I'm going to merge this as I've reviewed your new steps and confirmed they're up to date.

2025-04-25 03:29 UTC, soc-service-agent commented
![](https://res.cloudinary.com/snyk/image/upload/r-d/scm-platform/snyk-pull-requests/pr-banner-default.svg)

### :tada: **Snyk checks have passed. No issues have been found so far.**

:white_check_mark: **security/snyk** check is complete. No issues have been found. [(View Details)](https://app.snyk.io/org/sumologic/pr-checks/cfcc7044-ce72-4c10-902a-3cabd99f2bdd?refs=5ec8568fabb9ec63f8b12c380f971150658f33af&source=prChecksComment)

:white_check_mark: **license/snyk** check is complete. No issues have been found. [(View Details)](https://app.snyk.io/org/sumologic/pr-checks/cfcc7044-ce72-4c10-902a-3cabd99f2bdd/license?refs=5ec8568fabb9ec63f8b12c380f971150658f33af&source=prChecksComment)

2025-04-25 03:55 UTC, merged