Update index.md
SumoLogic/sumologic-documentation pull request #4459
Opened 2024-08-22 22:23 UTC by wjakelee

Adding some additional context and examples for python instrumentation

## Purpose of this pull request

This pull request... 

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-08-22 22:32 UTC, kimsauce commented on docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
> +For Auto-instrumentation to work, you will need to include `opentelemetry-instrument` at the beginning of your application execution. If this is not an option for you, then you will need to follow th
```suggestion
To enable auto-instrumentation, you'll need to include `opentelemetry-instrument` at the beginning of your application execution. If this is not an option for you, you’ll need to follow the usage instructions for each instrumentation library you install.  For example, for Django instrumentation, you will need to add the following two lines to your code (outlined in the [Usage section](https://opentelemetry-python-contrib.readthedocs.io/en/latest/instrumentation/django/django.html#id1) of the library documentation):
```

2024-08-22 22:34 UTC, kimsauce commented on docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
> +Adding these lines prevents you from having to use the `opentelemetry-instrument` command in the execution of your app.
```suggestion
Adding these lines eliminates the need to use the `opentelemetry-instrument` command in the execution of your app.
```

2024-08-22 22:36 UTC, kimsauce commented on docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
> +[This article](https://opentelemetry-python.readthedocs.io/en/stable/examples/django/README.html#django-instrumentation) will show you how to use the `opentelemetry-instrumentation-django` library to
```suggestion
[This article](https://opentelemetry-python.readthedocs.io/en/stable/examples/django/README.html#django-instrumentation) will show you how to use the `opentelemetry-instrumentation-django` library to automatically instrument a Django app. It covers how to reference the library manually within your code, as well as how to use [Auto-instrumentation](https://opentelemetry-python.readthedocs.io/en/stable/examples/django/README.html#auto-instrumentation) without having to edit your code.
```

2024-08-22 22:37 UTC, kimsauce commented on docs/apm/traces/get-started-transaction-tracing/opentelemetry-instrumentation/python/index.md
> +[This article](https://opentelemetry.io/docs/languages/python/getting-started/) will walk you through deploying your own simple Flask app and configuring instrumentation on that app. The example will
```suggestion
[This article](https://opentelemetry.io/docs/languages/python/getting-started/) walks you through deploying a simple Flask app and configuring instrumentation for it. The example demonstrates how to log traces to the console for basic testing.
```

2024-08-22 22:37 UTC, kimsauce requested changes
Looks great! I noted some suggestions.

2024-08-23 23:11 UTC, wjakelee commented
Love it, thank you!

2024-08-23 23:24 UTC, kimsauce approved these changes

2024-08-23 23:48 UTC, merged