OpenTelemetry Remote Management V2
SumoLogic/sumologic-documentation pull request #4482
Opened 2024-08-29 05:54 UTC by JV0812

## Purpose of this pull request

This pull request is to add upgrade, edit, and delete information to the OpenTelemetry Remote Management doc.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

[Create Beta page for OpenTelemetry Remote Management](https://sumologic.atlassian.net/browse/DOCS-401)

2024-08-29 06:57 UTC, kimsauce requested changes
This is so well written, @JV0812 ! Just had a few small tweaks.

2024-08-29 06:57 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/remote-management/remote-management-v2.md
> +The Sumo Logic distribution for OpenTelemetry Collector facilitates remote management of data collection configurations, enabling seamless setup from the Sumo Logic UI and deployment to one or more c
```suggestion
The Sumo Logic Distribution for OpenTelemetry Collector facilitates remote management of data collection configurations, enabling seamless setup from the Sumo Logic UI and deployment to one or more collectors.
```

2024-08-29 06:57 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/remote-management/remote-management-v2.md
> +Follow the below steps to instal the collector and add uniquely identifiable tags:
```suggestion
Follow the below steps to install the collector and add uniquely identifiable tags:
```

2024-08-29 06:57 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/remote-management/remote-management-v2.md
> +< Add the auto-discovery page screenshot >
Commented this out until you have the screenshot ready.

```suggestion
<!-- Add the auto-discovery page screenshot -->
```

2024-08-29 06:57 UTC, kimsauce commented on docs/send-data/opentelemetry-collector/remote-management/remote-management-v2.md
> +A new source template will always be created with the latest verion of the source template.
```suggestion
A new source template will always be created with the latest version of the source template.
```

2024-08-30 15:02 UTC, jpipkin1 commented on docs/send-data/opentelemetry-collector/remote-management/remote-management-v2.md
> +    - Create a new source template and link the required collectors by collector name and collector tags. Also, delink the collectors added in the new source template to the existing source template.
```suggestion
    - Create a new source template and link the required collectors by collector name and collector tags. Also, unlink the collectors added in the new source template to the existing source template.
```

2024-09-20 18:53 UTC, jpipkin1 commented
@JV0812, I removed the hidden Kanso directions with commit "[Fixes for Kanso](https://github.com/SumoLogic/sumologic-documentation/pull/4482/commits/98b0b393c4491e9f23235488e24ff1e93b791854)".

2024-10-22 13:32 UTC, jpipkin1 commented on docs/send-data/opentelemetry-collector/remote-management/remote-management-v2.md
> +1. For **Collector Settings**, leave them as default to configure collectore as remotely managed.
```suggestion
1. For **Collector Settings**, leave them as default to configure collectors as remotely managed.
```

2024-10-22 13:37 UTC, jpipkin1 requested changes
This looks really good, @JV0812. I think you should make "source template" and "remote management" lowercase everywhere (including headings) except when documenting screen commands.

2024-10-23 06:44 UTC, JV0812 commented
@jpipkin1 thanks for pointing on this. I will d that updates.

2024-10-23 14:32 UTC, jpipkin1 approved these changes
Looks good, @JV0812!

2024-10-25 07:09 UTC, merged