Suggestion Update faq.md
SumoLogic/sumologic-documentation pull request #4487
Opened 2024-08-30 08:40 UTC by manashar4

@JV0812 - Sharing this suggestion as a generic reference for any administrators interested in understanding how the system optimizes the query. 

Could you please improve the experience of the same and add it to the help documentation.

## Purpose of this pull request

This pull request... 

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-08-31 21:21 UTC, kimsauce commented on docs/manage/partitions/flex/faq.md
> +Given all partition definitions and the user query, SUMO performs automatic query rewriting optimizations by rewriting the query by including _view/_index clauses and tries to use the minimal list of
```suggestion
:::note 
Given all partition definitions and the user's query, Sumo Logic automatically optimizes query execution by rewriting the query to include `_view` and `_index` clauses. The system then identifies the minimal list of views required to serve the query, which ultimately contributes to the scanned volume, whether actual or estimated.
:::
```

2024-08-31 21:22 UTC, kimsauce commented on docs/manage/partitions/flex/faq.md
> +Given all partition definitions and the user query, SUMO performs automatic query rewriting optimizations by rewriting the query by including _view/_index clauses and tries to use the minimal list of
@manashar4 lmk what you think

2024-08-31 21:22 UTC, kimsauce requested changes
Minor tweaks. @manashar4, thanks for submitting!

2024-09-04 15:31 UTC, jpipkin1 approved these changes

2024-09-10 14:40 UTC, jpipkin1 commented
@kimsauce, your comments have been addressed. Could you approve?

2024-09-10 17:29 UTC, kimsauce approved these changes

2024-09-10 17:47 UTC, merged