Created 301 Redirects and OTEL apps index page
SumoLogic/sumologic-documentation pull request #4557
Opened 2024-09-19 23:32 UTC by kimsauce

## Purpose of this pull request

This pull request adds 301 redirects for legacy docs, and an index page for OTEL apps (which users were searching for, but didn't exist).

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-09-20 15:12 UTC, jpipkin1 requested changes
What you have here is good, @kimsauce. 

But we should also add an index page for the "OpenTelemetry" subsections found under each of the following:
- https://help.sumologic.com/docs/integrations/microsoft-azure/
- https://help.sumologic.com/docs/integrations/app-development/
- https://help.sumologic.com/docs/integrations/cloud-security-monitoring-analytics/
- https://help.sumologic.com/docs/integrations/databases/
- https://help.sumologic.com/docs/integrations/hosts-operating-systems/
- https://help.sumologic.com/docs/integrations/pci-compliance/
- https://help.sumologic.com/docs/integrations/web-servers/

2024-09-20 19:34 UTC, jpipkin1 commented
@kimsauce, I can create a separate PR to add the index pages for those OpenTelemetry sections.

2024-09-20 19:35 UTC, jpipkin1 approved these changes

2024-09-23 02:06 UTC, kimsauce commented
> What you have here is good, @kimsauce.
> 
> But we should also add index pages for the "OpenTelemetry" sections under each of the following:
> 
> * https://help.sumologic.com/docs/integrations/microsoft-azure/
> * https://help.sumologic.com/docs/integrations/app-development/
> * https://help.sumologic.com/docs/integrations/cloud-security-monitoring-analytics/
> * https://help.sumologic.com/docs/integrations/databases/
> * https://help.sumologic.com/docs/integrations/hosts-operating-systems/
> * https://help.sumologic.com/docs/integrations/pci-compliance/
> * https://help.sumologic.com/docs/integrations/web-servers/

Thank you, John!! Just created a separate PR for this: https://github.com/SumoLogic/sumologic-documentation/pull/4567.

2024-09-23 02:28 UTC, merged