Digital Guardian Source doc
SumoLogic/sumologic-documentation pull request #4619
Opened 2024-10-04 11:30 UTC by JV0812

## Purpose of this pull request

This pull request is to create a beta page for the Digital Guardian C2C Source.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

[C2C Digital Guardian ARC: Create Public Doc](https://sumologic.atlassian.net/browse/DOCS-470)

2024-10-04 11:44 UTC, JV0812 commented on cid-redirects.json
> +  "/cid/21343": "/docs/send-data/hosted-collectors/microsoft-source/digital-guardian-source",
```suggestion
  "/cid/21343": "/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/digital-guardian-source",
```

2024-10-04 16:16 UTC, kimsauce approved these changes

2024-10-14 19:01 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/digital-guardian-source.md
> +The Digital Guardian integration ingests the export data using the [Export API](https://accessgw.msp.digitalguardian.com/rest/1.0/export_profiles/{Export_Profile}/export) and uses [Acknowledge API](h
The links for "Export API" and "Acknowledge API" are broken.

2024-10-14 19:02 UTC, jpipkin1 requested changes
Looks good, @JV0812. I found only one thing that needs to be updated.

2024-10-17 12:50 UTC, jpipkin1 approved these changes

2024-10-22 18:25 UTC, merged