Azure CosmosDB for NoSQL
SumoLogic/sumologic-documentation pull request #4714
Opened 2024-10-30 05:17 UTC by himanshu219

## Purpose of this pull request

This pull request includes updates to collection steps and new section for install apps & dashboards.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-10-30 09:33 UTC, JV0812 commented on docs/integrations/microsoft-azure/azure-cosmos-db.md
> +This app has been tested with MongoDB, Cassandra and NoSQL database account types.
```suggestion
This app is tested with MongoDB, Cassandra, and NoSQL database account types.
```

2024-10-30 10:07 UTC, JV0812 commented on docs/integrations/microsoft-azure/azure-cosmos-db.md
> +
Dashboard info needs to be added.

2024-10-30 10:08 UTC, JV0812 requested changes
@himanshu219 can you please add the dashboard info. Rest everything is fine.

2024-10-30 16:45 UTC, jpipkin1 commented
@himanshu219, I made some minor changes (see commit "[Updates from review](https://github.com/SumoLogic/sumologic-documentation/pull/4714/commits/c426920094ee3313d9f86ddb12eff2ab731bedfa)").

2024-11-06 10:50 UTC, JV0812 commented on docs/integrations/microsoft-azure/azure-cosmos-db.md
> +Currently only Azure Cosmos DB for NoSQL database account type supports exporting metrics using diagnostic settings.
```suggestion
Currently, only Azure Cosmos DB for NoSQL database account type supports exporting metrics using diagnostic settings.
```

2024-11-06 10:54 UTC, JV0812 approved these changes
LGTM

2024-11-06 11:13 UTC, merged