Azure Database for PostgreSQL doc and old doc location tag fix
SumoLogic/sumologic-documentation pull request #4755
Opened 2024-11-13 05:01 UTC by sachin-sumologic

## Purpose of this pull request

This pull request... 

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-11-13 10:26 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-cosmos-db.md
> +2. If you want to audit Azure Cosmos DB control plane operations, [disable the key based metadata write access](https://learn.microsoft.com/en-us/azure/cosmos-db/audit-control-plane-logs#disable-key-
no need to change numbering in future in markdown it automatically does the numbering if one puts `1.`

2024-11-13 10:36 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-database-for-postgresql.md
> +Rule Name: AzureObservabilityMetadataExtractionAzureDatabaseForPostgreSQLLevel
resourceId=/SUBSCRIPTIONS/*/RESOURCEGROUPS/*/PROVIDERS/MICROSOFT. DBFORPOSTGRESQL/FLEXIBLESERVERS/*

replace $resourceId._3  with MICROSOFT. DBFORPOSTGRESQL
relace $resourceId._4 with  $resourceId._3

need to do the same for azure database for mysql

2024-11-13 10:37 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-database-for-postgresql.md
> +1. Tag the location field in the source with right location value. <br/><img src={useBaseUrl('img/integrations/microsoft-azure/Azure-Storage-Tag-Location.png')} alt="Azure Redis Cache Tag Location" s
alt text for all of them should be different here it should be Azure Database for Postgresql

2024-11-13 10:39 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-database-for-postgresql.md
> +Now that you have set up data collection, install the Azure Load Balancer Sumo Logic app to use the pre-configured dashboards that provide visibility into your environment for real-time analysis of o
Azure Load Balancer -> Azure Database for PostgreSQL

2024-11-13 10:43 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-database-for-postgresql.md
> +<img src={useBaseUrl('https://sumologic-app-data.s3.amazonaws.com/dashboards/AzureDatabaseForPostgresql/Azure-Database-for-PostgreSQL-Autovacuum.png')} alt="Azure Database for PostgreSql - Autovacuum
the bucket name should be sumologic-app-data-v2 in S3.
Need to check for other apps as well. 
sumologic-app-data bucket contains deprecated data.

2024-11-13 10:43 UTC, himanshu219 requested changes
minor changes needed, the doc format should follow. You can use chatgpt to upload the screenshot and get the bulleted points summary for all the dashboards. 
Use dashboard to (bullet format)
1.
2.

In Azure Database for MySQL and Azure Application Gateway also we missed following this convention, in rest of the azure apps we are following it.

2024-11-13 16:28 UTC, jpipkin1 approved these changes
@sachin-sumologic, your updates look very good! I have no corrections. 

By the way, you can start each item in a numbered list with "1." because they will be numbered automatically. See our [Style Guide](https://help.sumologic.com/docs/contributing/style-guide/#numbered-lists).

2024-11-14 05:47 UTC, himanshu219 approved these changes

2024-11-14 05:58 UTC, merged