Updated docs for cloudTrail dashboard
SumoLogic/sumologic-documentation pull request #4782
Opened 2024-11-20 12:54 UTC by himsharma01

## Purpose of this pull request

This pull request... 

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-11-20 15:35 UTC, jpipkin1 commented on docs/integrations/amazon-aws/application-load-balancer.md
> +<img src={useBaseUrl('img/integrations/amazon-aws/AWS-Application_Load_Balancer-Threat_Intel.png')} alt="AWS Application Load Balancer dashboard" />
@himsharma01, this is not the correct screen image.

2024-11-20 15:38 UTC, jpipkin1 requested changes
@himsharma01, you need to correct some of the screen images.

2024-11-21 09:49 UTC, JV0812 approved these changes
LGTM

2024-11-21 16:06 UTC, jpipkin1 approved these changes
Thanks for updating the screen images, @himsharma01. It looks good now.

2024-11-22 10:48 UTC, merged