Added documentation for azure api management
SumoLogic/sumologic-documentation pull request #4839
Opened 2024-12-04 11:40 UTC by sachin-sumologic

## Purpose of this pull request

This pull request... 

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [x] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-12-04 14:57 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-api-management.md
> +### Configure metric rules
we need another metric rule which extracts service "Azure Observability Metadata Extraction Service Level" https://help.sumologic.com/docs/integrations/microsoft-azure/azure-storage/#configure-metric-rules

2024-12-04 14:57 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-api-management.md
> +2. [Configure an HTTP Source](/docs/send-data/collect-from-other-data-sources/azure-monitoring/collect-metrics-azure-monitor/#step-1-configure-an-http-source).
lets use 1. everywhere

2024-12-04 14:59 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-api-management.md
> +Since this source contains logs from multiple regions, make sure that you do not tag this source with the location tag.
instructions for enabling cloud defender ?
Also instructions for recommendation alert ?

2024-12-04 15:00 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-api-management.md
> +<img src={useBaseUrl('https://sumologic-app-data-v2.s3.amazonaws.com/dashboards/AzureApiManagement/Azure-API-Management-Subscriptions.png')} alt="Azure Database for PostgreSql - Overview" style={{bor
Remove "Azure Database for PostgreSql" from every alt text for image

2024-12-04 15:01 UTC, himanshu219 requested changes
minor changes requested

2024-12-05 09:53 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-api-management.md
> +import AppInstallNoDataSourceV2 from '../../reuse/apps/app-install-index-apps-v2.md';
why importing  AppInstallNoDataSourceV2 multiple times?

2024-12-05 09:53 UTC, himanshu219 commented on docs/integrations/microsoft-azure/azure-api-management.md
> +* **Gateway Logs**. Resource Logs for Azure API Management Gateway. To learn more about the resource log schema for Azure API Management, refer to the [Azure documentation](https://learn.microsoft.co
To learn more about the resource log schema for Azure API Management
-> To learn more about its schema, refer to the Azure documentation

2024-12-05 09:57 UTC, sachin-sumologic commented on docs/integrations/microsoft-azure/azure-api-management.md
> +import AppInstallNoDataSourceV2 from '../../reuse/apps/app-install-index-apps-v2.md';
Happened by mistakenly, removed.

2024-12-05 10:01 UTC, himanshu219 approved these changes

2024-12-05 11:14 UTC, JV0812 commented on docs/integrations/microsoft-azure/azure-api-management.md
> +For Security events, make sure you enable [Microsoft Defender for Cloud](https://learn.microsoft.com/en-us/azure/defender-for-cloud/tutorial-enable-app-service-plan#enable-the-defender-for-app-servic
```suggestion
For Security events, make sure you enable [Microsoft Defender for Cloud](https://learn.microsoft.com/en-us/azure/defender-for-cloud/tutorial-enable-app-service-plan#enable-the-defender-for-app-service-plan). In Defender Plans Settings page toggle the **APIs** status under **Cloud Workload Protection (CWP)** section.
```

2024-12-05 11:15 UTC, JV0812 approved these changes
LGTM

2024-12-05 11:17 UTC, amee-sumo approved these changes
LGTM

2024-12-05 11:38 UTC, merged