New doc- CrowdStrike Falcon FileVantage (Apps)
SumoLogic/sumologic-documentation pull request #4849
Opened 2024-12-06 13:37 UTC by amee-sumo

## Purpose of this pull request

This pull request is to create a new apps doc - CrowdStrike Falcon FileVantage

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

https://sumologic.atlassian.net/browse/DOCS-586

2024-12-06 15:12 UTC, jpipkin1 commented on docs/integrations/saas-cloud/crowdstrike-falcon-filevantage.md
> +This App uses Sumo Logic’s [CrowdStrike FileVantage Source](https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-filevantage-source/) to collec
```suggestion
This App uses Sumo Logic’s [CrowdStrike FileVantage Source](/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/crowdstrike-filevantage-source/) to collect the FileVantage logs from CrowdStrike.
```

2024-12-06 15:16 UTC, jpipkin1 commented on docs/integrations/saas-cloud/crowdstrike-falcon-filevantage.md
> +The dashboard also shows the monitoring rules that triggered the most changes, assisting in policy refinement. A detailed table of recent file activities, including timestamps, hostnames, file paths,
```suggestion
The dashboard also shows the monitoring rules that triggered the most changes, assisting in policy refinement. A detailed table of recent file activities, including timestamps, hostnames, file paths, severities, and associated policies, is provided. Overall, the dashboard strengthens the detection and response to unauthorized or suspicious file activities. <br/> <img src={useBaseUrl('https://sumologic-app-data-v2.s3.us-east-1.amazonaws.com/dashboards/Crowdstrike+Falcon+FileVantage/Crowdstrike+Falcon+FileVantage+dashboard.png')} alt="CrowdStrike Falcon FileVantage Overview" style={{border: '1px solid gray'}} width="800" />
```

2024-12-06 15:16 UTC, jpipkin1 commented on docs/integrations/saas-cloud/crowdstrike-falcon-filevantage.md
> +While the dashboard provides placeholders for tracking malicious file changes and directory changes, data in these sections requires specific configuration based on the environment. Finally, the **Ho
```suggestion
While the dashboard provides placeholders for tracking malicious file changes and directory changes, data in these sections requires specific configuration based on the environment. Finally, the **Host-Based Change Monitoring** table offers detailed insights into the hosts and host groups involved in file changes, assisting in pinpointing areas that need further investigation. Overall, this dashboard is a vital tool for ensuring file integrity and effectively mitigating risks. <br/> <img src={useBaseUrl('https://sumologic-app-data-v2.s3.us-east-1.amazonaws.com/dashboards/Crowdstrike+Falcon+FileVantage/Crowdstrike+Falcon+FileVantage+Security.png')} alt="CrowdStrike Falcon FileVantage Security" style={{border: '1px solid gray'}} width="800" />
```

2024-12-09 08:50 UTC, JV0812 requested changes
LGTM, except the images uploaded to the S3 bucket. The dashboard images do not have the required clarity while viewing the file. Can you please export the dashboard image from the platform and upload it to S3?
<img width="948" alt="Screenshot 2024-12-09 at 2 20 36 PM" src="https://github.com/user-attachments/assets/5d78566c-6ec1-467d-97ab-325ddcdf1c9b">

2024-12-09 11:49 UTC, JV0812 approved these changes
LGTM

2024-12-09 20:08 UTC, jpipkin1 commented
Publishing this PR at the request of @ankitgoelcmu.

2024-12-09 20:33 UTC, merged