Dragos C2C (Source)
SumoLogic/sumologic-documentation pull request #4873
Opened 2024-12-12 13:33 UTC by amee-sumo

## Purpose of this pull request

This pull request is to create a new doc on Dragos.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

https://sumologic.atlassian.net/browse/DOCS-593

2024-12-12 19:34 UTC, jpipkin1 commented
@amee-sumo, I changed the name of the release note file to `2024-12-13-collection.md` so it wouldn't result in a merge conflict. You'll have to change the file name again to the date it will actually be published.

2024-12-12 21:39 UTC, jpipkin1 commented on docs/integrations/product-list/product-list-a-l.md
> +|  <img src={useBaseUrl('img/send-data/dragos-logo.png')} alt="Thumbnail icon" width="60"/> | [Dragos](https://www.dragos.com//) | Collector: [Dragos](/docs/send-data/hosted-collectors/cloud-to-cloud
```suggestion
|  <img src={useBaseUrl('img/send-data/dragos-logo.png')} alt="Thumbnail icon" width="60"/> | [Dragos](https://www.dragos.com//) | Collector: [Dragos Source](/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source) |
```

2024-12-12 21:41 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +When you create a Dragos Source, you add it to a Hosted Collector. Before creating the Source, identify the Hosted Collector you want to use or create a new Hosted Collector. For instructions, see [C
```suggestion
When you create a Dragos Source, you add it to a Hosted Collector. Before creating the Source, identify the Hosted Collector you want to use or create a new Hosted Collector. For instructions, see [Configure a Hosted Collector and Source](/docs/send-data/hosted-collectors/configure-hosted-collector).
```

2024-12-12 21:44 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +Sources can be configured using UTF-8 encoded JSON files with the Collector Management API. See [how to use JSON to configure Sources](/docs/send-data/use-json-configure-sources) for details. 
```suggestion
Sources can be configured using UTF-8 encoded JSON files with the Collector Management API. See [Use JSON to Configure Sources](/docs/send-data/use-json-configure-sources) for details. 
```

2024-12-12 21:45 UTC, jpipkin1 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +| fields | JSON Object | No | `null` | JSON map of key-value fields (metadata) to apply to the collector or source. Use the boolean field _siemForward to enable forwarding to SIEM.| `{"_siemForward":
```suggestion
| fields | JSON Object | No | `null` | JSON map of key-value fields (metadata) to apply to the collector or source. Use the boolean field `_siemForward` to enable forwarding to SIEM.| `{"_siemForward": false, "fieldA": "valueA"}` |
```

2024-12-12 21:47 UTC, jpipkin1 approved these changes
This PR looks great, @amee-sumo! I have only a few suggestions.

2024-12-16 05:18 UTC, JV0812 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +1. Open the Dragos platform and navigate to the **Admin** > **User**.
```suggestion
1. Sign in to the Dragos platform.
1.  Navigate to the **Admin** > **User**.
```

2024-12-16 05:27 UTC, JV0812 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +1. Enter the **Endpoint URL** of Dragos platform. For example, `https://test.cxc.dragos.cloud/`.
```suggestion
1. **Endpoint URL**. Enter the Dragos platform endpoint URL. For example, `https://test.cxc.dragos.cloud/`.
```

2024-12-16 05:30 UTC, JV0812 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +1. Enter the following details for authorization:
```suggestion
1. **API ID**. Enter the API ID of your account collected from the [Dragos platform](#vendor-configuration). For example, `036fxxxx-b642-xxxx-99d3-fcxxxx2exxxx`.
1. **API Secret**. Enter the API Secret of your account collected from the [Dragos platform](#vendor-configuration).. For example, `xxxU1TxxxxxxxxKSJwHYOpK37xxxxxxxxrEHAkU91xxxxxxxxxFrrJ06xxx`.
```

2024-12-16 05:30 UTC, JV0812 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +    1. **API ID**. API ID of your account. For example, `036fxxxx-b642-xxxx-99d3-fcxxxx2exxxx`.
```suggestion
```

2024-12-16 05:30 UTC, JV0812 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +    1. **API Secret**. API Secret of your account. For example, `xxxU1TxxxxxxxxKSJwHYOpK37xxxxxxxxrEHAkU91xxxxxxxxxFrrJ06xxx`.
```suggestion
```

2024-12-16 05:34 UTC, JV0812 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +1. Check the following boxes to collect the required data:
```suggestion
1. Select the checkbox depending on the type of data that you wish to collect.
```

2024-12-16 05:34 UTC, JV0812 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +    1. **Collect Vulnerability**
```suggestion
```

2024-12-16 05:35 UTC, JV0812 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +    1. **Collect Addresses**
```suggestion
```

2024-12-16 05:35 UTC, JV0812 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +    1. **Collect Zones**
```suggestion
```

2024-12-16 05:35 UTC, JV0812 commented on docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source.md
> +    1. **Collect Assets**
```suggestion
```

2024-12-16 05:48 UTC, JV0812 commented on sidebars.ts
> +                'send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source',
```suggestion
                'send-data/hosted-collectors/cloud-to-cloud-integration-framework/dropbox-source',
                'send-data/hosted-collectors/cloud-to-cloud-integration-framework/dragos-source',
```

2024-12-16 05:54 UTC, JV0812 requested changes
Minor fixes

2024-12-16 07:54 UTC, JV0812 approved these changes
LGTM

2024-12-16 19:05 UTC, yleiferman commented
Dragos 1.0.0 is being GAed today

2024-12-16 19:16 UTC, merged