DOCS-604 - Test Wistia video embedding
SumoLogic/sumologic-documentation pull request #4874
Opened 2024-12-12 19:10 UTC by jpipkin1

## Purpose of this pull request

This pull request tests embedding a video from Wistia into this article: https://help.sumologic.com/docs/cse/administration/mitre-coverage/

## Select the type of change

- [x] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

[DOCS-604](https://sumologic.atlassian.net/browse/DOCS-604)

2024-12-13 02:21 UTC, kimsauce commented on docs/cse/administration/mitre-coverage.md
> +<script src="https://fast.wistia.net/player.js" async></script><iframe src="https://fast.wistia.net/embed/iframe/yebz0v90tx?web_component=true&seo=true&videoFoam=false" title="Micro Lesson: Cloud SIE
Could you change to this format? This allows the video embedding to be responsive in desktop/mobile when users resize the window.

```suggestion
<Iframe url="https://fast.wistia.net/embed/iframe/yebz0v90tx?web_component=true&seo=true&videoFoam=false"
  width="854px"
  height="480px"
  id="wistiaVideo"
  className="video-container"
  display="initial"
  position="relative"
  allow="autoplay; fullscreen"
  allowfullscreen
/>
```

Here's what it looks like, not-responsive code vs responsive code.

https://github.com/user-attachments/assets/14576fa7-9560-4582-b3e2-eae2cfe95452

https://github.com/user-attachments/assets/aa8c08a6-1231-4279-8704-17c03857a64a

2024-12-13 02:23 UTC, kimsauce requested changes
change to code

2024-12-16 15:26 UTC, jpipkin1 commented
Thanks, @kimsauce! Your new code works great.

2024-12-19 22:25 UTC, jpipkin1 commented
@kimsauce, could you take another look?

2024-12-20 03:41 UTC, kimsauce approved these changes
Perfect!

2024-12-20 03:57 UTC, merged