Updated AWSO v2.11 in docs
SumoLogic/sumologic-documentation pull request #4886
Opened 2024-12-17 14:53 UTC by himsharma01

## Purpose of this pull request

This pull request... 

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

2024-12-17 15:29 UTC, jpipkin1 commented on docs/observability/aws/deploy-use-aws-observability/changelog.md
> +* AWS Observability solution now supports Sumologic Korea deployment.
```suggestion
* AWS Observability solution now supports Sumo Logic Korea deployment.
```

2024-12-17 15:31 UTC, jpipkin1 approved these changes
Approved, @himsharma01. I have only a couple of suggestions.

2024-12-18 05:05 UTC, JV0812 commented on docs/observability/aws/deploy-use-aws-observability/changelog.md
> +* Amazon Load Balancer apps - Added support to analyze and monitor Cloudtrail audit event logs for Application Load Balancer, Classic Load Balancer and Network Load Balancer.
```suggestion
* Amazon Load Balancer apps - Added support to analyze and monitor Cloudtrail audit event logs for Application Load Balancer, Classic Load Balancer, and Network Load Balancer.
```

2024-12-18 05:05 UTC, JV0812 commented on docs/observability/aws/deploy-use-aws-observability/changelog.md
> +* Added out of the box Monitors for RDS Oracle DB, Application Load Balancer, Classic Load Balancer and Network Load Balancer. Solution now supports 78 out-of-box monitors.
```suggestion
* Added out of the box monitors for RDS Oracle DB, Application Load Balancer, Classic Load Balancer, and Network Load Balancer. Solution now supports 78 out-of-box monitors.
```

2024-12-18 05:06 UTC, JV0812 commented on docs/observability/aws/deploy-use-aws-observability/changelog.md
> +* Updated cloudformation helper function with Python Runtime to v3.13 .
```suggestion
* Updated cloudformation helper function with Python Runtime to v3.13.
```

2024-12-18 05:07 UTC, JV0812 commented on docs/observability/aws/deploy-use-aws-observability/changelog.md
> +* Updated SAM apps with python lambda runtime v3.13 and library updates to handle any CVE’s .
```suggestion
* Updated SAM apps with Python Lambda runtime v3.13 and library updates to handle any CVE’s.
```

2024-12-18 05:08 UTC, JV0812 requested changes
Minor fixes

2024-12-26 11:49 UTC, JV0812 approved these changes
LGTM

2025-01-14 05:30 UTC, amee-sumo approved these changes
LGTM

2025-01-24 09:21 UTC, merged