Release Note Dec 2024 (Apps)
SumoLogic/sumologic-documentation pull request #4907
Opened 2024-12-30 07:46 UTC by amee-sumo

## Purpose of this pull request

This pull request is to create a consolidated Release Note for December.

## Select the type of change

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions, updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - .clabot, version updates, maintenance, dependencies, new packages for the site (Docusaurus, Gatsby, React, etc.)

## Ticket (if applicable)

https://sumologic.atlassian.net/browse/SUMO-252821

2024-12-30 08:17 UTC, JV0812 commented on blog-service/2024-12-24-apps.md
> +- Flex app - Minor changes in the variable name.
```suggestion
- **Flex app**. Minor changes in the variable name.
```

2024-12-30 08:19 UTC, JV0812 commented on blog-service/2024-12-24-apps.md
> +- **AWS Serverless Application Models**. Released the following four SAM’s with Python v3.13 AWS Lambda runtime update with latest libraries.
```suggestion
- **AWS Serverless Application Models**. Released the following four SAM’s with Python `v3.13` AWS Lambda runtime update with latest libraries.
```

2024-12-30 08:21 UTC, JV0812 commented on blog-service/2024-12-24-apps.md
> +    - **IIS - OpenTelemetry**. Added 10 new monitors for IIS - OpenTelemetry app that will be triggered for different pre-defined conditions. [Learn more](https://help.sumologic.com/docs/integrations
```suggestion
    - **IIS - OpenTelemetry**. Added 10 new monitors that will be triggered for different pre-defined conditions. [Learn more](https://help.sumologic.com/docs/integrations/web-servers/iis-10).
```

2024-12-30 08:22 UTC, JV0812 commented on blog-service/2024-12-24-apps.md
> +    - **IIS - OpenTelemetry**. Added 10 new monitors for IIS - OpenTelemetry app that will be triggered for different pre-defined conditions. [Learn more](https://help.sumologic.com/docs/integrations
Follow the same for other apps listed in this list. This is just to avoid using the app name multiple times.

2024-12-30 08:23 UTC, JV0812 commented on blog-service/2024-12-24-apps.md
> +- **Block Blob**. Updated the Block Blob collection to support collection for Network Flow logs. The Network Security Group (NSG) flow logs will be removed on 30 September 2027. From 30 June 2025, yo
```suggestion
- **Block Blob**. Updated the Block Blob collection to support collection for Network Flow logs. The Network Security Group (NSG) flow logs will be removed on 30 September 2027. **From 30 June 2025, you will no longer be able to generate new NSG flow logs as part of this retirement**. For more details refer to Azure [docs](https://learn.microsoft.com/en-us/azure/network-watcher/flow-logs-read?tabs=nsg).
```

2024-12-30 08:27 UTC, JV0812 commented on blog-service/2024-12-24-apps.md
> +- The 28 apps listed below have been updated, and as part of the app installation flow, customers can now create Cloud to Cloud sources:
```suggestion
- The 28 apps listed below have been updated, and as part of the app installation flow, you can now create Cloud-to-Cloud sources:
```

2024-12-30 08:28 UTC, JV0812 commented on blog-service/2024-12-24-apps.md
> +    - 1Password
Add the respective app docs link.

2024-12-30 08:29 UTC, JV0812 commented on blog-service/2024-12-24-apps.md
> +    - sumologic-securityhub-connector-aws-org - SAM SemanticVersion: 1.0.8.
```suggestion
    - `sumologic-securityhub-connector-aws-org`. Upgraded the SAM SemanticVersion to `v1.0.8`.
```

2024-12-30 08:30 UTC, JV0812 commented on blog-service/2024-12-24-apps.md
> +    - sumologic-securityhub-connector-aws-org - SAM SemanticVersion: 1.0.8.
Remove the linespace between the bullets and follow the same changes to other points.

2024-12-30 08:34 UTC, JV0812 commented on blog-service/2024-12-24-apps.md
> +
Remove the linespace between the bullet points.

2024-12-30 08:34 UTC, JV0812 requested changes
Minor fixes.

2024-12-30 17:42 UTC, jpipkin1 submitted a review, later dismissed
@amee-sumo, I have a couple of suggestions:
* Remove "https://help.sumologic.com" from documentation links so that clicking a link launches the target article in the same window instead of a new window.
* Put the items in bullet lists into alphabetical order. This will help readers quickly find items in the list.

2024-12-31 04:10 UTC, JV0812 commented on blog-service/2024-12-24-apps.md
> +- **Azure Event Grid**. Azure Event Grid is a highly scalable, fully managed Pub Sub message distribution service that offers flexible message consumption patterns using the MQTT and HTTP protocols.
```suggestion
- **Azure Event Grid**. Azure Event Grid is a highly scalable, fully managed Pub Sub message distribution service that offers flexible message consumption patterns using the MQTT and HTTP protocols. This integration helps in monitoring data plane requests, delivery failures and publish failures of Event Grid resources - custom topics, system topics, and domains. [Learn more](/docs/integrations/microsoft-azure/azure-event-grid/).
```

2024-12-31 04:11 UTC, JV0812 approved these changes
LGTM

2024-12-31 05:09 UTC, amee-sumo commented
Thanks for your suggestions @jpipkin1 and @JV0812 
I've made the required changes. Please acknowledge

2024-12-31 11:50 UTC, himanshu219 approved these changes

2024-12-31 11:52 UTC, himanshu219 approved these changes

2024-12-31 12:18 UTC, merged