custom inv, rel note, eval
SumoLogic/sumologic-documentation pull request #576
Opened 2022-10-10 21:24 UTC by MariePMcGarry

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2022-10-10 22:20 UTC, kimsauce requested changes
* In **docs/cse/administration/custom-inventory-sources.md**, the header "### Webhook payload for Computer Entity" is displayed as code. Code snippet above that is missing the bottom backticks.
* In the same file, italics is broken in this sentence: The type key specifies what type of inventory data the webhook sends. Set the value to user or _computer. _.

2022-10-11 19:45 UTC, kimsauce commented on docs/cse/administration/custom-inventory-sources.md
> +```
Code below and above are JSON, so I would enable syntax highlighting for them. 

```suggestion
```json
```

2022-10-11 19:46 UTC, kimsauce requested changes
minor changes

2022-10-11 20:04 UTC, MariePMcGarry commented on docs/cse/administration/custom-inventory-sources.md
> +| count by os_version, hostname, ip, mac, username,email, role</code>
Updated file in PR

2022-10-11 20:30 UTC, MariePMcGarry commented on docs/cse/administration/custom-inventory-sources.md
> +| count by os_version, hostname, ip, mac, username,email, role</code>
fixed

2022-10-11 20:50 UTC, kimsauce requested changes
1 small change

2022-10-11 20:50 UTC, kimsauce commented on docs/cse/administration/custom-inventory-sources.md
> +```
Can you push json here after the first three backticks(all lowercase)?

2022-10-11 20:53 UTC, kimsauce requested changes
Sorry, also line 280 needs json after backticks

2022-10-11 21:47 UTC, kimsauce approved these changes

2022-10-11 21:48 UTC, merged