google workspace app
SumoLogic/sumologic-documentation pull request #766
Opened 2022-10-26 20:08 UTC by MariePMcGarry

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2022-10-26 20:14 UTC, kimsauce commented on docs/integrations/google/workspace/collect-logs-legacy.md
> +Sumo Logic provides a serverless solution which pulls logs from Google Workspace with API calls. You can configure the list alerts to be collected, but by default all alerts are collected. The alerts
```suggestion
Sumo Logic provides a serverless solution which pulls logs from Google Workspace with API calls. You can configure the list alerts to be collected, but by default all alerts are collected. The alerts  are then forwarded to Sumo Logic’s HTTP endpoint in JSON format. By default the collection starts from the current date and time, but this setting is also configurable as detailed in the [Advanced configuration](#Advanced-configuration) section.
```

2022-10-26 20:15 UTC, kimsauce commented on docs/integrations/google/workspace/collect-logs-legacy.md
> +6. Copy the **Client ID** displayed at the end of the script output. You will use the Client Name field when you [configure Google Workspace Alert Center to allow client API access](#Configure_Google
```suggestion
6. Copy the **Client ID** displayed at the end of the script output. You will use the Client Name field when you [configure Google Workspace Alert Center to allow client API access](#configure-google-workspace-alert-center-to-allow-client-api-acce) in the following task.
```

2022-10-26 20:16 UTC, kimsauce commented on docs/integrations/google/workspace/collect-logs-legacy.md
> +If you're using the [Configure Google Cloud Platform Collection for Google Workspace Alert Center](#Configure_Google_Cloud_Platform_Collection_for_Google_Workspace_Alert_Center), use the **Client ID*
What should that last link be pointing to?

2022-10-26 20:17 UTC, kimsauce commented on docs/integrations/google/workspace/collect-logs-legacy.md
> +1. Enter the **Client ID** for the service account copied in Step 2, then in the **OAuth Scopes** field enter the following: [https://www.googleapis.com/auth/apps.alerts ](https://www.googleapis.com/
```suggestion
1. Enter the **Client ID** for the service account copied in Step 2, then in the **OAuth Scopes** field enter the following: [https://www.googleapis.com/auth/apps.alerts](https://www.googleapis.com/auth/apps.alerts). <br/><img src={useBaseUrl('img/integrations/google/GSuite_Step5.png')} alt="google workspace" width="400"/>
```

2022-10-26 20:18 UTC, kimsauce commented on docs/integrations/google/workspace/collect-logs.md
> +Configure one [Google Workspace Source](/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-source.md) for each Google App from which you want to collect events:
```suggestion
Configure one [Google Workspace Source](/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-source) for each Google App from which you want to collect events:
```

2022-10-26 20:18 UTC, kimsauce requested changes
some suggestions

2022-10-31 22:11 UTC, kimsauce approved these changes

2022-10-31 22:12 UTC, kimsauce commented
Hi @MariePMcGarry , added some more changes and did a slight reorg.

2022-11-02 15:46 UTC, kimsauce commented
@MariePMcGarry , edited your PR and obtained Mohit's approval (see https://jasklabs.atlassian.net/browse/CON-1133).

@stacykor , will merge this.

2022-11-02 16:27 UTC, merged

2022-11-08 22:28 UTC, duchatran commented on docs/integrations/google/workspace/collect-logs.md
> -## Configure Collection for Google Workspace Audit Source
Actually we need to keep "Audit" as we are using the "G Suite Apps Audit" source, not the "Google Workspace" source. The latter only collects user data and it's for CSE mostly (I know it's confusing).

2022-11-08 22:28 UTC, duchatran commented on docs/integrations/google/workspace/collect-logs.md
> -This section provides instructions for configuring log collection for Google Workspace with Audit Source.
Same comment as above

2022-11-08 22:29 UTC, duchatran commented on docs/integrations/google/workspace/collect-logs.md
> -[Google Workspace](#configure-collection-for-google-workspace-audit-source): Monitors and analyzes the activity across all the Google Workspace Apps in one place. You can configure collection for eac
Same comment

2022-11-08 22:30 UTC, duchatran commented on docs/integrations/google/workspace/collect-logs.md
> -Configure one [G Suite Apps Audit Source](/docs/send-data/hosted-collectors/google-source/g-suite-apps-audit-source) for each Google App from which you want to collect events:
I don't know when we will rename this source ( to "Google Workspace Audit Source"?), right now it's shown as "G Suite Apps Audit Source"

2022-11-08 22:43 UTC, duchatran commented on docs/integrations/google/workspace/collect-logs.md
> -**One Single Source Category for all Sources.** For users who are setting up the Google Workspace Apps Audit Source for the first time, we suggest that you use the same single Source Category for eac
"Apps Audit" is  actually correct

2022-11-08 22:43 UTC, duchatran commented on docs/integrations/google/workspace/collect-logs.md
> -A Google Workspace Apps Audit Source uses the [Google Apps Reports API](https://developers.google.com/admin-sdk/reports/v1/get-start/getting-started) to ingest all audit logs via watchpoints. Activit
The old text is actually correct

2022-11-08 22:44 UTC, duchatran commented on docs/integrations/google/workspace/collect-logs.md
> -When creating or modifying a Google Apps Audit Source, you will be required to authenticate with Google using the credentials of a user that has access rights to the account, and to the Reports API.
All the old texts on "Apps Audit" (and below) are actually correct.

2022-11-08 22:44 UTC, duchatran commented on docs/integrations/google/workspace/collect-logs.md
>  ```
This removal is correct. We just need to point to the new C2C source page, currently at https://help.sumologic.com/docs/send-data/hosted-collectors/cloud-to-cloud-integration-framework/google-workspace-alertcenter/