added sqs information (#872)
SumoLogic/sumologic-documentation pull request #966
Opened 2022-11-17 18:34 UTC by kimsauce

* added sqs information

* Update docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md

* Update docs/observability/aws/faq.md

* Update docs/observability/aws/faq.md

* Update docs/observability/aws/integrations/amazon-sqs.md

* Update docs/observability/aws/integrations/amazon-sqs.md

* Update docs/observability/aws/integrations/amazon-sqs.md

* Update docs/observability/aws/integrations/amazon-sqs.md

* updated FER

* removed commas

* Update docs/observability/aws/deploy-use-aws-observability/deploy-with-terraform.md

* Update docs/integrations/amazon-aws/sqs.md

* Update docs/integrations/amazon-aws/sqs.md

* Update docs/observability/aws/faq.md

* Update docs/observability/aws/integrations/amazon-sqs.md

* Update amazon-sqs.md

Co-authored-by: Kim <56411016+kimsauce@users.noreply.github.com>

## Purpose of this pull request

This pull request (PR) ...

Issue number: 

## Select the type of change:

- [ ] Minor Changes - Typos, formatting, slight revisions
- [ ] Update Content - Revisions and updating sections
- [ ] New Content - New features, sections, pages, tutorials
- [ ] Site and Tools - Updates, maintenance, and new packages for the site, Gatsby, React, etc

2022-11-17 19:29 UTC, stacykor commented on docs/observability/aws/integrations/amazon-sqs.md
> +Login to Sumo Logic,  go to Manage Data > Logs > Fields. Search for the “queuename” field. If not present, create it. Learn how to create and manage fields [here](https://help.sumologic.com/Manage/Fi
Login to Sumo Logic, go to **Manage Data** > **Logs** > **Fields**. Search for the “queuename” field. If not present, create it. Learn how to create and manage fields [here](/docs/manage/fields/#manage-fields).

2022-11-17 19:30 UTC, stacykor requested changes
Two fixes:

1) the manage fields reference looks off, suggested a local file path.
2) there's an extra space

2022-11-17 21:01 UTC, kimsauce commented on docs/integrations/amazon-aws/sqs.md
>  Login to Sumo Logic,  go to Manage Data > Logs > Fields. Search for the “queuename” field. If not present, create it. Learn how to create and manage fields [here](https://help.sumologic.com/Manage/Fi
```suggestion
Log in to Sumo Logic, go to **Manage Data** > **Logs** > **Fields**. Search for the “queuename” field. If not present, create it. Learn how to create and manage fields [here](https://help.sumologic.com/Manage/Fields#manage-fields).
```

2022-11-17 21:02 UTC, kimsauce commented on docs/observability/aws/integrations/amazon-sqs.md
> +Login to Sumo Logic,  go to Manage Data > Logs > Fields. Search for the “queuename” field. If not present, create it. Learn how to create and manage fields [here](https://help.sumologic.com/Manage/Fi
```suggestion
Log in to Sumo Logic, go to **Manage Data** > **Logs** > **Fields**. Search for the “queuename” field. If not present, create it. Learn how to create and manage fields [here](https://help.sumologic.com/Manage/Fields#manage-fields).
```

2022-11-17 21:03 UTC, kimsauce commented on docs/observability/aws/integrations/amazon-sqs.md
> +Create a Field Extraction Rule for CloudTrail Logs. Learn how to create a Field Extraction Rule [here](https://help.sumologic.com/Manage/Field-Extractions/Create-a-Field-Extraction-Rule).
This is a link to our legacy docs -- replace with current version

2022-11-17 21:04 UTC, kimsauce commented on docs/integrations/amazon-aws/sqs.md
> +Log in to Sumo Logic, go to **Manage Data** > **Logs** > **Fields**. Search for the “queuename” field. If not present, create it. Learn how to create and manage fields [here](https://help.sumologic.c
This is a link to our legacy docs -- replace with current version

2022-11-17 21:04 UTC, kimsauce commented on docs/integrations/amazon-aws/sqs.md
>  Create a Field Extraction Rule for CloudTrail Logs. Learn how to create a Field Extraction Rule [here](https://help.sumologic.com/Manage/Field-Extractions/Create-a-Field-Extraction-Rule).
This is a link to our legacy docs -- replace with current version

2022-11-17 21:05 UTC, kimsauce commented
Hi @JKashyap96 and @zjiawei3 , I've assigned your PR back to you -- @stacykor and I have added some edits.

2022-11-18 00:29 UTC, zjiawei3 commented
> Hi @JKashyap96 and @zjiawei3 , I've assigned your PR back to you -- @stacykor and I have added some edits.

Hi @kimsauce , I dont think I have any context about this PR. Did you tag the wrong person?

2022-11-18 03:24 UTC, kimsauce commented on docs/integrations/amazon-aws/sqs.md
> +Log in to Sumo Logic, go to **Manage Data** > **Logs** > **Fields**. Search for the “queuename” field. If not present, create it. Learn how to create and manage fields [here](https://help.sumologic.c
```suggestion
Log in to Sumo Logic, go to **Manage Data** > **Logs** > **Fields**. Search for the “queuename” field. If not present, create it. Learn how to create and manage fields [here](/docs/manage/fields/#manage-fields).
```

2022-11-18 03:24 UTC, kimsauce commented on docs/observability/aws/integrations/amazon-sqs.md
> +Log in to Sumo Logic, go to **Manage Data** > **Logs** > **Fields**. Search for the “queuename” field. If not present, create it. Learn how to create and manage fields [here](https://help.sumologic.c
```suggestion
Log in to Sumo Logic, go to **Manage Data** > **Logs** > **Fields**. Search for the “queuename” field. If not present, create it. Learn how to create and manage fields [here](/docs/manage/fields/#manage-fields).
```

2022-11-18 03:25 UTC, kimsauce commented on docs/observability/aws/integrations/amazon-sqs.md
> +Create a Field Extraction Rule for CloudTrail Logs. Learn how to create a Field Extraction Rule [here](https://help.sumologic.com/Manage/Field-Extractions/Create-a-Field-Extraction-Rule).
```suggestion
Create a Field Extraction Rule for CloudTrail Logs. Learn how to create a Field Extraction Rule [here](/docs/manage/field-extractions/create-field-extraction-rule).
```

2022-11-18 03:25 UTC, kimsauce commented on docs/integrations/amazon-aws/sqs.md
>  Create a Field Extraction Rule for CloudTrail Logs. Learn how to create a Field Extraction Rule [here](https://help.sumologic.com/Manage/Field-Extractions/Create-a-Field-Extraction-Rule).
```suggestion
Create a Field Extraction Rule for CloudTrail Logs. Learn how to create a Field Extraction Rule [here](/docs/manage/field-extractions/create-field-extraction-rule).
```

2022-11-18 03:26 UTC, kimsauce commented on docs/observability/aws/integrations/amazon-sqs.md
> +```
```suggestion
```sql
```

2022-11-18 03:28 UTC, kimsauce commented
Hi @kimsauce , I dont think I have any context about this PR. Did you tag the wrong person?

Ah, sorry! Please ignore.

2022-11-18 12:22 UTC, JKashyap96 commented on docs/observability/aws/integrations/amazon-sqs.md
> +```
Looks good how it is.

2022-11-18 12:23 UTC, JKashyap96 approved these changes
LGTM, will merge this when we release AWSO 2.6 next quarter

2022-11-29 20:41 UTC, kimsauce commented on docs/observability/aws/faq.md
> +See [AWS Observability Apps](/docs/observability/aws/integrations) for detailed information on all supported apps including Application, Classic, and Network Load Balancer, DynamoDB, EC2, RDS, API Ga
```suggestion
See [AWS Observability Apps](/docs/observability/aws/integrations) for detailed information on all supported apps including Application, Classic, and Network Load Balancer, DynamoDB, EC2, RDS, API Gateway, ECS, ElastiCache, Lambda, SNS, and SQS.
```

2022-12-19 17:30 UTC, kimsauce commented
@JKashyap96 checking in - do you have an update when we can merge this?

2022-12-19 18:14 UTC, JKashyap96 commented
@kimsauce Will find out and get back to you.

2022-12-20 11:49 UTC, JKashyap96 commented
@kimsauce We are planning to release AWSO 2.6 by the end of January 2023, so would need to be merged by then. We might have more commits to this PR later as well.

2023-01-19 21:03 UTC, kimsauce commented
@JKashyap96 , is this ready to publish? cc: @stacykor @nmohantyctr

2023-01-23 06:51 UTC, kimsauce commented
Spoke with Jayanta, who's handing this off to NPande. @nmohantyctr reassigning to you as it's App-related and created an Asana ticket for you.

2023-01-24 22:21 UTC, kimsauce commented
> Spoke with Jayanta, who's handing this off to NPande. @nmohantyctr reassigning to you as it's App-related and created an Asana ticket for you. cc @stacykor

@nmohantyctr did you get a chance to check with Nitin on the release date? cc: @stacykor

2023-01-30 08:47 UTC, nmohantyctr commented
Hello, @kimsauce Spoke to Nitin, Jayanta, and Himanshu Sharma about this feature. All the changes are in place. However, the release (for AWSO 2.6) is now currently due around the end of February.
cc @stacykor @JKashyap96

2023-04-06 17:13 UTC, merged